import FepSketches.finite_information

/-!
# Finite collective inference under explicit product and coupling laws

This module separates independent product constructions from a specified
two-agent stochastic consensus operator. Additivity is proved only for product
laws and additive costs. Consensus conclusions are proved only for the concrete
coupling matrix encoded by `consensusStep`.
-/

namespace FEP.CollectiveInference

open FEP Finset Filter
open FEP.FiniteInformation
open scoped BigOperators Topology

variable {State₁ State₂ Observation₁ Observation₂ : Type*}
  [Fintype State₁] [Fintype State₂]
  [Fintype Observation₁] [Fintype Observation₂]

/-! ## Independent product agents -/

/-- Product of two finite generative kernels. Independence is structural: each
output coordinate depends only on its corresponding input coordinate. -/
def productKernel
    (left : FiniteKernel State₁ Observation₁)
    (right : FiniteKernel State₂ Observation₂) :
    FiniteKernel (State₁ × State₂) (Observation₁ × Observation₂) where
  mass state observation :=
    left state.1 observation.1 * right state.2 observation.2
  nonneg state observation :=
    mul_nonneg (left.nonneg state.1 observation.1)
      (right.nonneg state.2 observation.2)
  sum_one state := by
    classical
    rw [Fintype.sum_prod_type]
    simp_rw [← Finset.mul_sum, right.sum_one, mul_one]
    exact left.sum_one state.1

/-- Every row of the product kernel is normalized. -/
theorem productKernel_sum_one
    (left : FiniteKernel State₁ Observation₁)
    (right : FiniteKernel State₂ Observation₂)
    (state : State₁ × State₂) :
    ∑ observation, productKernel left right state observation = 1 :=
  (productKernel left right).sum_one state

/-- The joint law generated by product priors and product kernels factors
pointwise into the two component generative laws. -/
theorem productAgent_joint_mass
    (priorLeft : FiniteLaw State₁) (priorRight : FiniteLaw State₂)
    (kernelLeft : FiniteKernel State₁ Observation₁)
    (kernelRight : FiniteKernel State₂ Observation₂)
    (stateLeft : State₁) (stateRight : State₂)
    (observationLeft : Observation₁) (observationRight : Observation₂) :
    (productKernel kernelLeft kernelRight).joint
        (FiniteLaw.product priorLeft priorRight)
        ((stateLeft, stateRight), (observationLeft, observationRight)) =
      kernelLeft.joint priorLeft (stateLeft, observationLeft) *
        kernelRight.joint priorRight (stateRight, observationRight) := by
  change
    (priorLeft stateLeft * priorRight stateRight) *
        (kernelLeft stateLeft observationLeft *
          kernelRight stateRight observationRight) =
      (priorLeft stateLeft * kernelLeft stateLeft observationLeft) *
        (priorRight stateRight * kernelRight stateRight observationRight)
  ring

/-- Expected finite cost. -/
noncomputable def expectedCost
    {State : Type*} [Fintype State]
    (law : FiniteLaw State) (cost : State → ℝ) : ℝ :=
  ∑ state, law state * cost state

/-- An additive cost has additive expectation under an independent product
law. -/
theorem productExpectedCost_additive
    (left : FiniteLaw State₁) (right : FiniteLaw State₂)
    (leftCost : State₁ → ℝ) (rightCost : State₂ → ℝ) :
    expectedCost (FiniteLaw.product left right)
        (fun state => leftCost state.1 + rightCost state.2) =
      expectedCost left leftCost + expectedCost right rightCost := by
  classical
  simp only [expectedCost, FiniteLaw.product, Fintype.sum_prod_type]
  calc
    (∑ x, ∑ y,
        left x * right y * (leftCost x + rightCost y)) =
        (∑ x, ∑ y, left x * right y * leftCost x) +
          ∑ x, ∑ y, left x * right y * rightCost y := by
      simp_rw [mul_add, Finset.sum_add_distrib]
    _ = (∑ x, left x * leftCost x) +
          ∑ y, right y * rightCost y := by
      congr 1
      · calc
          (∑ x, ∑ y, left x * right y * leftCost x) =
              ∑ x, (left x * leftCost x) * ∑ y, right y := by
            apply Finset.sum_congr rfl
            intro x _
            calc
              (∑ y, left x * right y * leftCost x) =
                  ∑ y, (left x * leftCost x) * right y := by
                apply Finset.sum_congr rfl
                intro y _
                ring
              _ = (left x * leftCost x) * ∑ y, right y := by
                rw [Finset.mul_sum]
          _ = ∑ x, left x * leftCost x := by
            rw [right.sum_one]
            simp
      · calc
          (∑ x, ∑ y, left x * right y * rightCost y) =
              ∑ x, left x * ∑ y, right y * rightCost y := by
            apply Finset.sum_congr rfl
            intro x _
            calc
              (∑ y, left x * right y * rightCost y) =
                  ∑ y, left x * (right y * rightCost y) := by
                apply Finset.sum_congr rfl
                intro y _
                ring
              _ = left x * ∑ y, right y * rightCost y := by
                rw [Finset.mul_sum]
          _ = (∑ x, left x) * ∑ y, right y * rightCost y := by
            rw [Finset.sum_mul]
          _ = ∑ y, right y * rightCost y := by
            rw [left.sum_one, one_mul]

/-- Finite variational free energy: divergence from a supported reference plus
an expected cost. -/
noncomputable def variationalFreeEnergy
    {State : Type*} [Fintype State]
    (actual reference : FiniteLaw State) (cost : State → ℝ) : ℝ :=
  finiteKL actual reference + expectedCost actual cost

/-- Collective VFE evaluated on the independent product construction. -/
noncomputable def collectiveVFE
    (actualLeft referenceLeft : FiniteLaw State₁)
    (actualRight referenceRight : FiniteLaw State₂)
    (leftCost : State₁ → ℝ) (rightCost : State₂ → ℝ) : ℝ :=
  variationalFreeEnergy
    (FiniteLaw.product actualLeft actualRight)
    (FiniteLaw.product referenceLeft referenceRight)
    (fun state => leftCost state.1 + rightCost state.2)

/-- Collective VFE is additive when both actual and reference laws factor and
the cost is additive. Full support is explicit because finite KL is reduced by
the logarithmic product theorem. -/
theorem collectiveVFE_additive
    (actualLeft referenceLeft : FiniteLaw State₁)
    (actualRight referenceRight : FiniteLaw State₂)
    (leftCost : State₁ → ℝ) (rightCost : State₂ → ℝ)
    (referenceLeftPositive : ∀ state, 0 < referenceLeft state)
    (referenceRightPositive : ∀ state, 0 < referenceRight state) :
    collectiveVFE actualLeft referenceLeft actualRight referenceRight
        leftCost rightCost =
      variationalFreeEnergy actualLeft referenceLeft leftCost +
        variationalFreeEnergy actualRight referenceRight rightCost := by
  rw [collectiveVFE, variationalFreeEnergy,
    FiniteInformation.finiteKL_product actualLeft referenceLeft
      actualRight referenceRight referenceLeftPositive referenceRightPositive,
    productExpectedCost_additive]
  simp only [variationalFreeEnergy]
  ring

/-- A finite expected-free-energy objective with an explicit predictive law,
preference law, and statewise ambiguity cost. -/
noncomputable def expectedFreeEnergy
    {State : Type*} [Fintype State]
    (predictive preference : FiniteLaw State) (ambiguity : State → ℝ) : ℝ :=
  finiteKL predictive preference + expectedCost predictive ambiguity

/-- Product-agent expected free energy. -/
noncomputable def independentCollectiveEFE
    (predictiveLeft preferenceLeft : FiniteLaw State₁)
    (predictiveRight preferenceRight : FiniteLaw State₂)
    (ambiguityLeft : State₁ → ℝ) (ambiguityRight : State₂ → ℝ) : ℝ :=
  expectedFreeEnergy
    (FiniteLaw.product predictiveLeft predictiveRight)
    (FiniteLaw.product preferenceLeft preferenceRight)
    (fun state => ambiguityLeft state.1 + ambiguityRight state.2)

/-- Expected free energy is additive only under the stated product predictive
and preference laws and additive ambiguity. -/
theorem independentEFE_additive
    (predictiveLeft preferenceLeft : FiniteLaw State₁)
    (predictiveRight preferenceRight : FiniteLaw State₂)
    (ambiguityLeft : State₁ → ℝ) (ambiguityRight : State₂ → ℝ)
    (preferenceLeftPositive : ∀ state, 0 < preferenceLeft state)
    (preferenceRightPositive : ∀ state, 0 < preferenceRight state) :
    independentCollectiveEFE predictiveLeft preferenceLeft
        predictiveRight preferenceRight ambiguityLeft ambiguityRight =
      expectedFreeEnergy predictiveLeft preferenceLeft ambiguityLeft +
        expectedFreeEnergy predictiveRight preferenceRight ambiguityRight := by
  rw [independentCollectiveEFE, expectedFreeEnergy,
    FiniteInformation.finiteKL_product predictiveLeft preferenceLeft
      predictiveRight preferenceRight preferenceLeftPositive
      preferenceRightPositive,
    productExpectedCost_additive]
  simp only [expectedFreeEnergy]
  ring

/-! ## Normalized unit-weight products of experts -/

/-- Normalizing constant for a unit-weight product of two finite experts. -/
noncomputable def productOfExpertsNormalizer
    {State : Type*} [Fintype State]
    (left right : FiniteLaw State) : ℝ :=
  ∑ state, left state * right state

/-- Unit-weight product-of-experts pool. A positive normalizer excludes
disjoint-support inputs and makes normalization well-defined. This is the
normalized pointwise product `left * right`; it does not apply the one-half
exponents required by an equal-weight logarithmic pool. -/
noncomputable def unitWeightProductOfExpertsPool
    {State : Type*} [Fintype State]
    (left right : FiniteLaw State)
    (normalizerPositive : 0 < productOfExpertsNormalizer left right) :
    FiniteLaw State where
  mass state := left state * right state / productOfExpertsNormalizer left right
  nonneg state := div_nonneg
    (mul_nonneg (left.nonneg state) (right.nonneg state)) normalizerPositive.le
  sum_one := by
    rw [← Finset.sum_div, productOfExpertsNormalizer]
    exact div_self (ne_of_gt normalizerPositive)

/-- The supported unit-weight product-of-experts pool is normalized. -/
theorem unitWeightProductOfExpertsPool_sum_one
    {State : Type*} [Fintype State]
    (left right : FiniteLaw State)
    (normalizerPositive : 0 < productOfExpertsNormalizer left right) :
    ∑ state, unitWeightProductOfExpertsPool left right normalizerPositive state = 1 :=
  (unitWeightProductOfExpertsPool left right normalizerPositive).sum_one

/-! ## A concrete strictly stochastic two-agent consensus law -/

/-- Convex mixture of two finite laws. -/
def convexMixture
    {State : Type*} [Fintype State]
    (weight : ℝ) (weightNonnegative : 0 ≤ weight) (weightAtMostOne : weight ≤ 1)
    (left right : FiniteLaw State) : FiniteLaw State where
  mass state := weight * left state + (1 - weight) * right state
  nonneg state := add_nonneg
    (mul_nonneg weightNonnegative (left.nonneg state))
    (mul_nonneg (sub_nonneg.mpr weightAtMostOne) (right.nonneg state))
  sum_one := by
    rw [Finset.sum_add_distrib, ← Finset.mul_sum, ← Finset.mul_sum,
      left.sum_one, right.sum_one]
    ring

/-- First row of the strictly stochastic consensus matrix
`[[3/4, 1/4], [1/4, 3/4]]`. -/
noncomputable def consensusLeft
    {State : Type*} [Fintype State]
    (left right : FiniteLaw State) : FiniteLaw State :=
  convexMixture (3 / 4) (by norm_num) (by norm_num) left right

/-- Second row of the strictly stochastic consensus matrix. -/
noncomputable def consensusRight
    {State : Type*} [Fintype State]
    (left right : FiniteLaw State) : FiniteLaw State :=
  convexMixture (1 / 4) (by norm_num) (by norm_num) left right

/-- Consensus preserves the two-agent mass pointwise, hence also globally. -/
theorem consensusMass_conserved
    {State : Type*} [Fintype State]
    (left right : FiniteLaw State) (state : State) :
    consensusLeft left right state + consensusRight left right state =
      left state + right state := by
  simp only [consensusLeft, consensusRight, convexMixture]
  ring

/-- Pointwise absolute disagreement between two finite beliefs. -/
noncomputable def beliefGap
    {State : Type*} [Fintype State]
    (left right : FiniteLaw State) (state : State) : ℝ :=
  |left state - right state|

/-- One consensus step contracts every pointwise disagreement by exactly one
half. The coefficient is strict and nonzero. -/
theorem consensus_gap_contracts
    {State : Type*} [Fintype State]
    (left right : FiniteLaw State) (state : State) :
    beliefGap (consensusLeft left right) (consensusRight left right) state =
      (1 / 2 : ℝ) * beliefGap left right state := by
  have difference :
      consensusLeft left right state - consensusRight left right state =
        (1 / 2 : ℝ) * (left state - right state) := by
    simp only [consensusLeft, consensusRight, convexMixture]
    ring
  simp only [beliefGap, difference, abs_mul]
  norm_num

/-- One synchronous consensus step on a pair of finite beliefs. -/
noncomputable def consensusStep
    {State : Type*} [Fintype State]
    (beliefs : FiniteLaw State × FiniteLaw State) :
    FiniteLaw State × FiniteLaw State :=
  (consensusLeft beliefs.1 beliefs.2, consensusRight beliefs.1 beliefs.2)

/-- Repeated synchronous consensus. -/
noncomputable def consensusIterate
    {State : Type*} [Fintype State]
    (initial : FiniteLaw State × FiniteLaw State) :
    ℕ → FiniteLaw State × FiniteLaw State
  | 0 => initial
  | iterations + 1 => consensusStep (consensusIterate initial iterations)

/-- Exact finite-time disagreement after repeated consensus. -/
theorem consensusIterate_gap
    {State : Type*} [Fintype State]
    (left right : FiniteLaw State) (state : State) (iterations : ℕ) :
    beliefGap (consensusIterate (left, right) iterations).1
        (consensusIterate (left, right) iterations).2 state =
      (1 / 2 : ℝ) ^ iterations * beliefGap left right state := by
  induction iterations with
  | zero => simp [consensusIterate]
  | succ iterations inductionHypothesis =>
      rw [consensusIterate]
      simp only [consensusStep]
      rw [consensus_gap_contracts, inductionHypothesis, pow_succ]
      ring

/-- Repeated consensus drives every pointwise belief gap to zero. -/
theorem consensus_gap_tendsto_zero
    {State : Type*} [Fintype State]
    (left right : FiniteLaw State) (state : State) :
    Tendsto
      (fun iterations =>
        beliefGap (consensusIterate (left, right) iterations).1
          (consensusIterate (left, right) iterations).2 state)
      atTop (nhds 0) := by
  have powerLimit :=
    tendsto_pow_atTop_nhds_zero_of_lt_one
      (by norm_num : 0 ≤ (1 / 2 : ℝ)) (by norm_num : (1 / 2 : ℝ) < 1)
  have scaledLimit := powerLimit.mul_const (beliefGap left right state)
  have scaledLimitZero :
      Tendsto
        (fun iterations =>
          (1 / 2 : ℝ) ^ iterations * beliefGap left right state)
        atTop (nhds 0) := by
    simpa using scaledLimit
  exact scaledLimitZero.congr' (Filter.Eventually.of_forall fun iterations =>
    (consensusIterate_gap left right state iterations).symm)

/-- Closed nonvacuity witness: distinct Boolean point masses retain a positive
gap after one step, while that gap strictly contracts from one to one half. -/
theorem boolConsensus_nonzero_strict_witness :
    beliefGap (FiniteLaw.pointMass true) (FiniteLaw.pointMass false) true = 1 ∧
      beliefGap
          (consensusLeft (FiniteLaw.pointMass true) (FiniteLaw.pointMass false))
          (consensusRight (FiniteLaw.pointMass true) (FiniteLaw.pointMass false))
          true = 1 / 2 ∧
      0 < beliefGap
          (consensusLeft (FiniteLaw.pointMass true) (FiniteLaw.pointMass false))
          (consensusRight (FiniteLaw.pointMass true) (FiniteLaw.pointMass false))
          true ∧
      beliefGap
          (consensusLeft (FiniteLaw.pointMass true) (FiniteLaw.pointMass false))
          (consensusRight (FiniteLaw.pointMass true) (FiniteLaw.pointMass false))
          true <
        beliefGap (FiniteLaw.pointMass true) (FiniteLaw.pointMass false) true := by
  norm_num [beliefGap, consensusLeft, consensusRight, convexMixture,
    FiniteLaw.pointMass]

/-- Atomwise quadratic disagreement potential for the specified coupling. -/
noncomputable def coupledPotential
    {State : Type*} [Fintype State]
    (left right : FiniteLaw State) (state : State) : ℝ :=
  (left state - right state) ^ 2

/-- The coupled quadratic potential contracts by exactly one quarter per
consensus step. -/
theorem coupledPotential_contracts
    {State : Type*} [Fintype State]
    (left right : FiniteLaw State) (state : State) :
    coupledPotential (consensusLeft left right) (consensusRight left right) state =
      (1 / 4 : ℝ) * coupledPotential left right state := by
  have difference :
      consensusLeft left right state - consensusRight left right state =
        (1 / 2 : ℝ) * (left state - right state) := by
    simp only [consensusLeft, consensusRight, convexMixture]
    ring
  rw [coupledPotential, coupledPotential, difference]
  ring

/-- If the two agents disagree at an atom, the coupled potential descends
strictly after one consensus step. -/
theorem coupledPotential_strict_descent
    {State : Type*} [Fintype State]
    (left right : FiniteLaw State) (state : State)
    (separated : left state ≠ right state) :
    coupledPotential (consensusLeft left right) (consensusRight left right) state <
      coupledPotential left right state := by
  rw [coupledPotential_contracts]
  have positive : 0 < coupledPotential left right state := by
    simp only [coupledPotential]
    exact sq_pos_of_ne_zero (sub_ne_zero.mpr separated)
  linarith

end FEP.CollectiveInference
