#!/usr/bin/env python3
"""Deterministic fep_lean -> GNN continuous-family projector (bridge P4b).

Emits the scalar-OU linear-Gaussian instance of the H2.7 composition
module (P4 boundary-record extraction table, `specs/gnn-bridge-p4b-continuous-emission/README.md`)
as a GNN v1 continuous document under bridge contract v0.2:

- terminating decimals emit exactly (H, R, prior_mean, prior_cov);
- non-terminating exact Lean reals (exp(-1), 1 - exp(-2)) emit as
  float64 shortest round-trip reprs, with the exact formula recorded
  verbatim in provenance (contract v0.2 rounding row).

Deterministic: same repo heads -> byte-identical document. `--check`
gates freshness (regenerated bytes vs on-disk artifact).
"""

from __future__ import annotations

import argparse
import subprocess
import sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
FEP_LEAN_ROOT = SCRIPT_DIR.parents[1]
GNN_ROOT = FEP_LEAN_ROOT.parent / "GeneralizedNotationNotation"
ARTIFACT_PATH = SCRIPT_DIR / "gnn-input" / "FepLeanContinuousOU.md"

FEP_LEAN_LEAN_MODULE = "lean/FepSketches/compositions/smooth_reference_kernel.lean"
LEAN_DEFINITION = (
    "selectedDynamics / selectedPrior / selectedFilter"
    " (smooth_reference_kernel.lean:49-75)"
)
GENERATOR_IDENTITY = (
    "specs/gnn-bridge-p4b-continuous-emission/projection_continuous.py"
    " (bridge P4b, contract v0.2)"
)
SYNTAX_TARGET = "GNN v1 (doc/gnn/gnn_syntax.md v1.1 surface)"
ROUNDING_POLICY = (
    "contract v0.2: terminating decimals emit exactly;"
    " non-terminating exact Lean reals emit as float64 (shortest"
    " round-trip repr) with the exact formula recorded verbatim in"
    " provenance; consumers treat the float as an approximation, never"
    " as the Lean value"
)

# --- Lean-extracted values (exact; see README extraction table) ---
#
# lean/FepSketches/compositions/smooth_reference_kernel.lean:49-54 —
# selectedDynamics: rate := 1, center := 0, diffusionVarianceRate := 2.
# :66-68 — selectedPrior: mean := 0.
# :72-75 — selectedFilter: stepDuration := 1, observationNoise :=
# selectedGaussianFamily (posterior_convergence.lean:38-40, variance 1).
#
# One-step fields (t = 1, rate = 1):
#   F = decay(1) = exp(-rate*t) = exp(-1)
#     [scalar_gaussian_semigroup.lean:42-43]
#   Q = transitionVariance(1) = rate^-1 * (1 - exp(-2*rate*t))
#     = 1 - exp(-2) [linear_gaussian_semigroup.lean:1217-1233]
#   H = identity readout [gaussian_filter.lean:46-49]
#   R = observation noise variance = 1
#     [posterior_convergence.lean:38-40]
#   prior_cov = stationary variance = 1 (proved,
#     smooth_reference_kernel.lean:96-101)
#
# Contract v0.2 rounding: F and Q are non-terminating exact reals ->
# float64 shortest round-trip repr of the exact Lean value
# Real.exp(-1) / 1 - Real.exp(-2), evaluated in IEEE 754 double
# precision as the emission witness.
F_VALUE = repr(2.718281828459045**-1)  # exp(-1) -> 0.36787944117144233
Q_VALUE = repr(1 - 2.718281828459045**-2)  # 1 - exp(-2) -> 0.8646647167633873
H_VALUE = "1.0"
R_VALUE = "1.0"
PRIOR_MEAN_VALUE = "0.0"
PRIOR_COV_VALUE = "1.0"


def repo_head(repo: str) -> str:
    """Return `git rev-parse HEAD` for *repo* (read-only query)."""
    result = subprocess.run(
        ["git", "rev-parse", "HEAD"],
        cwd=repo,
        capture_output=True,
        text=True,
        check=True,
    )
    return result.stdout.strip()


def build_document(fep_lean_head: str, gnn_head: str) -> str:
    """Render the continuous-family GNN document for the pinned instance."""
    lines = [
        "# GNN Bridge: FepLean Continuous OU Linear-Gaussian Model",
        "# GNN Version: 1.0",
        "# Deterministic projection of the compiled Lean scalar-OU",
        "#   instance (fep_lean,",
        "#   lean/FepSketches/compositions/smooth_reference_kernel.lean:49-75).",
        "# Contract v0.2 rounding: F and Q are non-terminating exact",
        "#   Lean reals emitted as float64 (shortest round-trip repr);",
        "#   their exact formulas are recorded in Signature. Terminating",
        "#   values emit exactly.",
        "",
        "## GNNSection",
        "FepLeanContinuousOU continuous",
        "",
        "## GNNVersionAndFlags",
        "GNN v1",
        "",
        "## ModelName",
        "FepLean Continuous OU Linear-Gaussian Model",
        "",
        "## ModelAnnotation",
        "Bridge P4b slice: the fep_lean scalar OU filter instance",
        "(rate=1, center=0, diffusionVarianceRate=2, stepDuration=1,",
        "observation noise variance=1) projected deterministically to",
        "GNN v1 continuous linear-Gaussian syntax under contract v0.2",
        "rounding. Extraction record (file:line in the fep_lean",
        "checkout at the commit recorded under Signature):",
        "- F one-step decay = exp(-rate*t) = exp(-1)",
        "  [scalar_gaussian_semigroup.lean:42-43]",
        "- Q one-step transition covariance = rate^-1*(1 - exp(-2*rate*t))",
        "  = 1 - exp(-2) [linear_gaussian_semigroup.lean:1217-1233]",
        "- H identity readout [gaussian_filter.lean:46-49]",
        "- R observation noise variance = 1",
        "  [posterior_convergence.lean:38-40]",
        "- prior_mean = 0, prior_cov = stationary variance = 1 (proved)",
        "  [smooth_reference_kernel.lean:66-68, 96-101]",
        "",
        "## StateSpaceBlock",
        "# Linear-Gaussian state-space (continuous family)",
        "x[1,1,type=float]      # latent scalar state",
        "y[1,1,type=float]      # observation",
        "F[1,1,type=float]      # one-step transition (drift decay)",
        "Q[1,1,type=float]      # process noise covariance",
        "H[1,1,type=float]      # observation matrix (identity readout)",
        "R[1,1,type=float]      # observation noise covariance",
        "prior_mean[1,1,type=float]   # x_1 mean",
        "prior_cov[1,1,type=float]    # x_1 covariance",
        "u[1,1,type=float]      # control input (passive: zero)",
        "# Time",
        "t[1,type=int]          # discrete step index",
        "",
        "## Connections",
        "F>x",
        "Q>x",
        "x-H",
        "H>y",
        "R>y",
        "prior_mean>x",
        "prior_cov>x",
        "",
        "## InitialParameterization",
        "# Contract v0.2 rounding: terminating decimals exact;",
        "# non-terminating exact Lean reals as float64 shortest",
        "# round-trip repr, exact formula in Signature.",
        "# F: one-step decay, exact Lean value exp(-1) [Real.exp(-1),",
        "#    scalar_gaussian_semigroup.lean:42-43]; float64 emission.",
        "F={",
        f"  (({F_VALUE}))",
        "}",
        "",
        "# Q: one-step transition covariance, exact Lean value",
        "#    1 - exp(-2) [linear_gaussian_semigroup.lean:1217-1233];",
        "#    float64 emission.",
        "Q={",
        f"  (({Q_VALUE}))",
        "}",
        "",
        "# H: identity readout, exact.",
        "H={",
        f"  (({H_VALUE}))",
        "}",
        "",
        "# R: observation noise variance, exact.",
        "R={",
        f"  (({R_VALUE}))",
        "}",
        "",
        "# prior_mean: exact vector (n=1).",
        "prior_mean={",
        f"  ({PRIOR_MEAN_VALUE})",
        "}",
        "",
        "# prior_cov: proved stationary variance, exact matrix (n=1).",
        "prior_cov={",
        f"  (({PRIOR_COV_VALUE}))",
        "}",
        "",
        "## Equations",
        "# Lean-defined one-step linear-Gaussian dynamics (file:line in",
        "# lean/FepSketches/):",
        "# decay(model, t) = Real.exp(-rate*t)",
        "#   [scalar_gaussian_semigroup.lean:42-43]",
        "# transitionVariance(t) = rate^-1 * (1 - Real.exp(-2*rate*t))",
        "#   [linear_gaussian_semigroup.lean:1217-1233]",
        "# x_t = F x_{t-1} + u_{t-1} + N(0, Q)",
        "# y_t = H x_t + N(0, R)",
        "",
        "## Time",
        "Time=t",
        "Dynamic",
        "Continuous",
        "ModelTimeHorizon=1",
        "",
        "## ActInfOntologyAnnotation",
        "F=StateTransitionMatrix",
        "H=ObservationMatrix",
        "Q=ProcessNoiseCovariance",
        "R=ObservationNoiseCovariance",
        "prior_mean=PriorMean",
        "prior_cov=PriorCovariance",
        "x=ContinuousHiddenState",
        "y=ContinuousObservation",
        "t=Time",
        "",
        "## ModelParameters",
        "ou_rate: 1             # selectedDynamics.rate",
        "ou_center: 0           # selectedDynamics.center",
        "diffusion_variance_rate: 2  # selectedDynamics.diffusionVarianceRate",
        "step_duration: 1       # selectedFilter.stepDuration",
        "observation_noise_variance: 1  # selectedGaussianFamily.variance",
        "num_timesteps: 1",
        "",
        "## Footer",
        "FepLean bridge P4b slice: scalar OU linear-Gaussian model",
        "projected from fep_lean smooth_reference_kernel.lean",
        "selectedDynamics/selectedPrior/selectedFilter under contract",
        "v0.2 rounding. One-step horizon, passive (no control input).",
        "",
        "## Signature",
        "source_repository: fep_lean",
        f"source_commit: {fep_lean_head}",
        "pipeline_repository: GeneralizedNotationNotation",
        f"pipeline_commit: {gnn_head}",
        f"lean_module: {FEP_LEAN_LEAN_MODULE}",
        "lean_structure: FEP.SmoothReferenceKernel composition instance",
        "lean_instance: selectedDynamics/selectedPrior/selectedFilter",
        "exact_formulas: F = exp(-1); Q = 1 - exp(-2)  # recorded verbatim per contract v0.2",
        "projection_tool: " + GENERATOR_IDENTITY,
        f"target_syntax: {SYNTAX_TARGET}",
        f"rounding_policy: {ROUNDING_POLICY}",
    ]
    return "\n".join(lines) + "\n"


def write_document() -> int:
    """Emit from the explicit W2 source pin (never implicitly move HEAD)."""
    from fep_lean.bridge.operations import emit

    emit(FEP_LEAN_ROOT, GNN_ROOT, "continuous")
    return 0


def check_document() -> int:
    """Read-only check of pinned owners and artifact bytes."""
    from fep_lean.bridge.operations import emit

    return 0 if emit(FEP_LEAN_ROOT, GNN_ROOT, "continuous", check=True) else 1


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description=(
            "Deterministic fep_lean -> GNN projector for the bridge P4b"
            " continuous emission; --check gates freshness."
        )
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit non-zero when the artifact is missing or stale",
    )
    args = parser.parse_args(argv)
    if args.check:
        return check_document()
    return write_document()


if __name__ == "__main__":
    sys.exit(main())
