"""Q5 concrete PyMDP artifact-proof slice contracts.

Covers the fail-closed static-AST extractor, the deterministic probe
generator, the hash manifest, and (serially) the two slice-local Lean
probes compiled from the committed generated bytes.
"""

from __future__ import annotations

import json
import re
import shutil
import subprocess
from fractions import Fraction
from pathlib import Path

import pytest

from fep_lean.verification.gnn_artifact_proof import (
    DISCRETE_BOOL_SHAPES,
    ArtifactProofError,
    PymdpArtifactTables,
    extract_pymdp_tables,
    manifest_mismatches,
    render_lean_probe,
    sha256_file,
)
from tests._support.lean_runner import run_lean_probe

PROJECT_ROOT = Path(__file__).resolve().parents[1]
SLICE = PROJECT_ROOT / "specs" / "gnn-bridge-q5-artifact-proof"
FIXTURES = SLICE / "fixtures"
GENERATED = SLICE / "generated"
SYMMETRIC_FIXTURE = FIXTURES / "pymdp_symmetric_runner.py"
ASYMMETRIC_FIXTURE = FIXTURES / "pymdp_asymmetric_runner.py"
EXTRACTOR = PROJECT_ROOT / "src" / "fep_lean" / "verification" / "gnn_artifact_proof.py"
GENERATOR = SLICE / "generate_probe.py"
MANIFEST = GENERATED / "artifact_proof_manifest.json"
IMPORT_ROOT = PROJECT_ROOT / "src" / "fep_lean" / "formal"
LEAN_ROOT = PROJECT_ROOT / "lean"

ALLOWED_AXIOMS = frozenset({"propext", "Classical.choice", "Quot.sound"})

SYMMETRIC_NAMESPACE = "FEPProbe.Q5ArtifactProof"
ASYMMETRIC_NAMESPACE = "FEPProbe.Q5ArtifactProofAsym"
SYMMETRIC_THEOREMS = (
    "symArtifactTables_faithful",
    "symArtifact_statement5Pymdp",
    "symArtifact_carrierMasses",
    "symArtifact_aMass_eq_original",
)
ASYMMETRIC_THEOREMS = (
    "asymArtifactTables_faithful",
    "asymExpected_ne_symBoolPayload",
)

A_LINE = "    A_data = [[0.25, 0.5], [0.75, 0.5]]\n"


def _lake_executable() -> str | None:
    lake = shutil.which("lake")
    if lake is None:
        return None
    if (
        not (LEAN_ROOT / "lakefile.lean").exists()
        and not (LEAN_ROOT / "lakefile.toml").exists()
    ):
        return None
    return lake


def _compile_probe(path: Path) -> subprocess.CompletedProcess[str]:
    return run_lean_probe(path, import_root=IMPORT_ROOT, cwd=LEAN_ROOT, timeout_s=900)


def _runner_body(*lines: str) -> str:
    body = "".join(line + "\n" for line in lines)
    return (
        "from __future__ import annotations\n\n\n"
        "def main() -> int:\n"
        f"{body}"
        "    return 0\n"
    )


def _base_body() -> list[str]:
    return [
        "    A_data = [[0.5, 0.5], [0.5, 0.5]]",
        "    B_data = [[[0.5, 0.5], [0.5, 0.5]], [[0.5, 0.5], [0.5, 0.5]]]",
        "    C_data = [0.5, 0.5]",
        "    D_data = [0.5, 0.5]",
        "    E_data = [0.25, 0.75]",
    ]


def _tables(source: str) -> PymdpArtifactTables:
    return extract_pymdp_tables(source, source_name="<test runner>")


def _expect_rejection(source: str, reason: str) -> None:
    with pytest.raises(ArtifactProofError) as excinfo:
        _tables(source)
    assert excinfo.value.reason == reason, excinfo.value.detail


# ---------------------------------------------------------------------------
# Positive extractions (retained fixtures, exact dyadic rationals)
# ---------------------------------------------------------------------------


def test_symmetric_fixture_extracts_exact_tables() -> None:
    tables = extract_pymdp_tables(SYMMETRIC_FIXTURE.read_text(encoding="utf-8"))
    assert tables.source_sha256 == sha256_file(SYMMETRIC_FIXTURE)
    for name, shape in DISCRETE_BOOL_SHAPES.items():
        assert tables.table(name).shape == shape, name
    a = tables.table("A_data")
    for outcome in range(2):
        for state in range(2):
            assert a.get((outcome, state)) == Fraction(1, 2)
    e = tables.table("E_data")
    assert e.get((0,)) == Fraction(1, 4)
    assert e.get((1,)) == Fraction(3, 4)


def test_asymmetric_fixture_extracts_exact_tables() -> None:
    tables = extract_pymdp_tables(ASYMMETRIC_FIXTURE.read_text(encoding="utf-8"))
    a = tables.table("A_data")
    assert a.get((0, 0)) == Fraction(1, 4)
    assert a.get((0, 1)) == Fraction(1, 2)
    assert a.get((1, 0)) == Fraction(3, 4)
    assert a.get((1, 1)) == Fraction(1, 2)
    b = tables.table("B_data")
    assert b.get((0, 0, 0)) == Fraction(1, 4)
    assert b.get((1, 0, 0)) == Fraction(3, 4)
    assert b.get((0, 1, 0)) == Fraction(3, 4)
    assert b.get((1, 1, 0)) == Fraction(1, 4)
    assert b.get((0, 0, 1)) == Fraction(1, 2)
    assert b.get((0, 1, 1)) == Fraction(1, 8)
    assert b.get((1, 0, 1)) == Fraction(1, 2)
    assert b.get((1, 1, 1)) == Fraction(7, 8)
    assert tables.table("C_data").get((0,)) == Fraction(1, 4)
    assert tables.table("C_data").get((1,)) == Fraction(3, 4)
    assert tables.table("E_data").get((0,)) == Fraction(3, 8)
    assert tables.table("E_data").get((1,)) == Fraction(5, 8)


# ---------------------------------------------------------------------------
# Fail-closed negative matrix
# ---------------------------------------------------------------------------


def test_duplicate_assignment_rejected() -> None:
    lines = _base_body()
    lines.append("    A_data = [[0.5, 0.5], [0.5, 0.5]]")
    _expect_rejection(_runner_body(*lines), "duplicate_assignment")


def test_augmented_reassignment_rejected() -> None:
    lines = _base_body()
    lines.append("    C_data += [0.0]")
    _expect_rejection(_runner_body(*lines), "reassignment")


def test_subscript_mutation_rejected() -> None:
    lines = _base_body()
    lines.append("    A_data[0] = [0.5, 0.5]")
    _expect_rejection(_runner_body(*lines), "reassignment")


def test_walrus_binding_rejected() -> None:
    lines = _base_body()
    lines.append("    if (A_data := [0.5, 0.5]):")
    lines.append("        pass")
    _expect_rejection(_runner_body(*lines), "ambiguous_dataflow")


def test_loop_binding_rejected() -> None:
    lines = _base_body()
    lines.append("    for A_data in [[0.5, 0.5], [0.5, 0.5]]:")
    lines.append("        pass")
    _expect_rejection(_runner_body(*lines), "ambiguous_dataflow")


def test_conditional_assignment_rejected() -> None:
    lines = [
        _base_body()[0],
        _base_body()[1],
        _base_body()[2],
        _base_body()[4],
        "    if True:",
        "        D_data = [0.5, 0.5]",
    ]
    _expect_rejection(_runner_body(*lines), "ambiguous_dataflow")


def test_call_rhs_rejected() -> None:
    lines = _base_body()
    lines[0] = "    A_data = np.array([[0.5, 0.5], [0.5, 0.5]])"
    _expect_rejection(_runner_body(*lines), "unsupported_expression")


def test_name_rhs_rejected() -> None:
    lines = _base_body()
    lines[0] = "    A_data = other_matrix"
    _expect_rejection(_runner_body(*lines), "unsupported_expression")


def test_method_call_on_table_rejected() -> None:
    lines = _base_body()
    lines.append("    A_data.append([0.5, 0.5])")
    _expect_rejection(_runner_body(*lines), "unsupported_expression")


def test_non_dyadic_literal_rejected() -> None:
    lines = _base_body()
    lines[2] = "    C_data = [0.1, 0.9]"
    _expect_rejection(_runner_body(*lines), "non_dyadic_value")


def test_non_finite_literal_rejected() -> None:
    lines = _base_body()
    lines[2] = "    C_data = [1e999, 0.0]"
    _expect_rejection(_runner_body(*lines), "non_finite_value")


def test_ragged_table_rejected() -> None:
    lines = _base_body()
    lines[0] = "    A_data = [[0.5, 0.5], [0.5, 0.5, 0.0]]"
    _expect_rejection(_runner_body(*lines), "ragged_table")


def test_shape_mismatch_rejected() -> None:
    lines = _base_body()
    lines[2] = "    C_data = [0.5, 0.25, 0.25]"
    _expect_rejection(_runner_body(*lines), "shape_mismatch")


def test_assignment_outside_main_rejected() -> None:
    source = (
        "from __future__ import annotations\n"
        "\n"
        "A_data = [[0.5, 0.5], [0.5, 0.5]]\n"
        "B_data = [[[0.5, 0.5], [0.5, 0.5]], [[0.5, 0.5], [0.5, 0.5]]]\n"
        "C_data = [0.5, 0.5]\n"
        "D_data = [0.5, 0.5]\n"
        "E_data = [0.25, 0.75]\n"
    )
    _expect_rejection(source, "ambiguous_dataflow")


def test_axis_swap_breaks_normalization() -> None:
    fixture_text = ASYMMETRIC_FIXTURE.read_text(encoding="utf-8")
    swapped = fixture_text.replace(A_LINE, "    A_data = [[0.25, 0.75], [0.5, 0.5]]\n")
    assert swapped != fixture_text
    _expect_rejection(swapped, "normalization_violation")


def test_value_mutation_with_normalization_is_detected() -> None:
    fixture_text = ASYMMETRIC_FIXTURE.read_text(encoding="utf-8")
    mutated = fixture_text.replace(A_LINE, "    A_data = [[0.75, 0.5], [0.25, 0.5]]\n")
    assert mutated != fixture_text
    tables = _tables(mutated)
    expected = json.loads(MANIFEST.read_text(encoding="utf-8"))["expected_payload"]
    assert [str(value) for _, value in tables.table("A_data").entries()] != expected[
        "asymmetric"
    ]["A_data"]["values"]


def test_unmodified_fixture_matches_manifest_expected_payload() -> None:
    tables = extract_pymdp_tables(ASYMMETRIC_FIXTURE.read_text(encoding="utf-8"))
    expected = json.loads(MANIFEST.read_text(encoding="utf-8"))["expected_payload"]
    for name in ("A_data", "B_data", "C_data", "D_data", "E_data"):
        assert [str(value) for _, value in tables.table(name).entries()] == expected[
            "asymmetric"
        ][name]["values"]


# ---------------------------------------------------------------------------
# Generation determinism, freshness gate, and hash integrity
# ---------------------------------------------------------------------------


def test_probe_render_is_deterministic_and_matches_committed_bytes() -> None:
    def render() -> str:
        return render_lean_probe(
            extract_pymdp_tables(SYMMETRIC_FIXTURE.read_text(encoding="utf-8")),
            variant="symmetric",
            fixture_name=SYMMETRIC_FIXTURE.name,
            fixture_sha256=sha256_file(SYMMETRIC_FIXTURE),
        )

    assert render() == render()
    assert (GENERATED / "probe_symmetric.lean").read_text(encoding="utf-8") == render()


def test_generate_check_gate_is_fresh() -> None:
    result = subprocess.run(
        [str(PROJECT_ROOT / ".venv" / "bin" / "python"), str(GENERATOR), "--check"],
        capture_output=True,
        text=True,
        cwd=PROJECT_ROOT,
        timeout=120,
        check=False,
    )
    assert result.returncode == 0, result.stdout + result.stderr


def test_manifest_detects_tampered_fixture_digest() -> None:
    manifest = json.loads(MANIFEST.read_text(encoding="utf-8"))
    fixture_name = SYMMETRIC_FIXTURE.name
    tampered_fixtures = {
        name: ("0" * 64 if name == fixture_name else digest)
        for name, digest in manifest["fixtures"].items()
    }
    tampered_text = (
        json.dumps(
            {**manifest, "fixtures": tampered_fixtures}, sort_keys=True, indent=2
        )
        + "\n"
    )
    problems = manifest_mismatches(
        tampered_text, repo_root=PROJECT_ROOT, slice_root=SLICE
    )
    assert any(problem.startswith(f"{fixture_name}: ") for problem in problems)


def test_digests_unchanged_by_extraction_and_render() -> None:
    watched = [
        SYMMETRIC_FIXTURE,
        ASYMMETRIC_FIXTURE,
        EXTRACTOR,
        GENERATED / "probe_symmetric.lean",
        GENERATED / "probe_asymmetric.lean",
        MANIFEST,
    ]
    before = {path: sha256_file(path) for path in watched}
    extract_pymdp_tables(SYMMETRIC_FIXTURE.read_text(encoding="utf-8"))
    render_lean_probe(
        extract_pymdp_tables(ASYMMETRIC_FIXTURE.read_text(encoding="utf-8")),
        variant="asymmetric",
        fixture_name=ASYMMETRIC_FIXTURE.name,
        fixture_sha256=sha256_file(ASYMMETRIC_FIXTURE),
    )
    after = {path: sha256_file(path) for path in watched}
    assert before == after


# ---------------------------------------------------------------------------
# Serial Lean probes (committed generated bytes)
# ---------------------------------------------------------------------------


def _parse_axioms(block: str) -> frozenset[str]:
    return frozenset(
        token.strip().strip("'")
        for token in block.replace("\n", " ").split(",")
        if token.strip().strip("'")
    )


def _assert_standard_axioms(
    output: str, namespace: str, theorems: tuple[str, ...]
) -> None:
    assert "sorryAx" not in output
    for name in theorems:
        qualified = f"{namespace}.{name}"
        report = re.search(
            rf"'{re.escape(qualified)}' "
            r"(?:depends on axioms: \[(?P<axioms>.*?)\]"
            r"|does not depend on any axioms)",
            output,
            re.DOTALL,
        )
        assert report is not None, f"missing axiom report for {qualified}\n{output}"
        if report.group("axioms") is not None:
            parsed = _parse_axioms(report.group("axioms"))
            assert parsed, f"empty axiom report for {qualified}"
            assert parsed <= ALLOWED_AXIOMS, parsed


@pytest.mark.serial_lean
@pytest.mark.skipif(_lake_executable() is None, reason="lake toolchain unavailable")
def test_symmetric_probe_compiles_warning_free_with_standard_axioms(
    tmp_path: Path,
) -> None:
    probe = GENERATED / "probe_symmetric.lean"
    result = _compile_probe(probe)
    output = result.stdout + result.stderr
    assert result.returncode == 0, output
    assert "warning:" not in output.lower()
    audit = (
        probe.read_text(encoding="utf-8")
        + "\n"
        + "\n".join(
            f"#print axioms {SYMMETRIC_NAMESPACE}.{name}" for name in SYMMETRIC_THEOREMS
        )
        + "\n"
    )
    audit_path = tmp_path / "Q5SymAxiomAudit.lean"
    audit_path.write_text(audit, encoding="utf-8")
    audit_result = _compile_probe(audit_path)
    audit_output = audit_result.stdout + audit_result.stderr
    assert audit_result.returncode == 0, audit_output
    _assert_standard_axioms(audit_output, SYMMETRIC_NAMESPACE, SYMMETRIC_THEOREMS)


@pytest.mark.serial_lean
@pytest.mark.skipif(_lake_executable() is None, reason="lake toolchain unavailable")
def test_asymmetric_probe_compiles_warning_free_with_standard_axioms(
    tmp_path: Path,
) -> None:
    probe = GENERATED / "probe_asymmetric.lean"
    result = _compile_probe(probe)
    output = result.stdout + result.stderr
    assert result.returncode == 0, output
    assert "warning:" not in output.lower()
    audit = (
        probe.read_text(encoding="utf-8")
        + "\n"
        + "\n".join(
            f"#print axioms {ASYMMETRIC_NAMESPACE}.{name}"
            for name in ASYMMETRIC_THEOREMS
        )
        + "\n"
    )
    audit_path = tmp_path / "Q5AsymAxiomAudit.lean"
    audit_path.write_text(audit, encoding="utf-8")
    audit_result = _compile_probe(audit_path)
    audit_output = audit_result.stdout + audit_result.stderr
    assert audit_result.returncode == 0, audit_output
    _assert_standard_axioms(audit_output, ASYMMETRIC_NAMESPACE, ASYMMETRIC_THEOREMS)


def test_split_main_rejected() -> None:
    source = (
        "from __future__ import annotations\n"
        "\n"
        "\n"
        "def main() -> int:\n"
        "    A_data = [[0.5, 0.5], [0.5, 0.5]]\n"
        "    B_data = [[[0.5, 0.5], [0.5, 0.5]], [[0.5, 0.5], [0.5, 0.5]]]\n"
        "    C_data = [0.5, 0.5]\n"
        "    return 0\n"
        "\n"
        "\n"
        "def main() -> int:\n"
        "    D_data = [0.5, 0.5]\n"
        "    E_data = [0.25, 0.75]\n"
        "    return 0\n"
    )
    _expect_rejection(source, "ambiguous_dataflow")


def test_async_main_rejected() -> None:
    source = (
        "from __future__ import annotations\n"
        "\n"
        "\n"
        "async def main() -> int:\n"
        "    A_data = [[0.5, 0.5], [0.5, 0.5]]\n"
        "    B_data = [[[0.5, 0.5], [0.5, 0.5]], [[0.5, 0.5], [0.5, 0.5]]]\n"
        "    C_data = [0.5, 0.5]\n"
        "    D_data = [0.5, 0.5]\n"
        "    E_data = [0.25, 0.75]\n"
        "    return 0\n"
    )
    _expect_rejection(source, "ambiguous_dataflow")


def test_function_shadow_rejected() -> None:
    lines = _base_body()
    lines.append("    def A_data() -> int:")
    lines.append("        return 0")
    _expect_rejection(_runner_body(*lines), "shadowed_name")


def test_class_shadow_rejected() -> None:
    lines = _base_body()
    lines.append("    class E_data:")
    lines.append("        pass")
    _expect_rejection(_runner_body(*lines), "shadowed_name")


def test_import_shadow_rejected() -> None:
    lines = _base_body()
    lines.append("    from math import floor as C_data")
    _expect_rejection(_runner_body(*lines), "shadowed_name")


def test_except_binding_shadow_rejected() -> None:
    lines = _base_body()
    lines.append("    try:")
    lines.append("        pass")
    lines.append("    except ValueError as C_data:")
    lines.append("        pass")
    _expect_rejection(_runner_body(*lines), "shadowed_name")


def test_match_capture_shadow_rejected() -> None:
    lines = _base_body()
    lines.append("    match [0.5]:")
    lines.append("        case D_data:")
    lines.append("            pass")
    _expect_rejection(_runner_body(*lines), "shadowed_name")


def test_try_star_conditional_assignment_rejected() -> None:
    lines = [
        _base_body()[0],
        _base_body()[1],
        _base_body()[2],
        _base_body()[3],
        "    try:",
        "        E_data = [0.25, 0.75]",
        "    except* ValueError:",
        "        pass",
    ]
    _expect_rejection(_runner_body(*lines), "ambiguous_dataflow")


def test_manifest_rejects_missing_fixture_key() -> None:
    manifest = json.loads(MANIFEST.read_text(encoding="utf-8"))
    fixtures = {
        name: digest
        for name, digest in manifest["fixtures"].items()
        if name != SYMMETRIC_FIXTURE.name
    }
    trimmed = json.dumps({**manifest, "fixtures": fixtures}, sort_keys=True, indent=2)
    problems = manifest_mismatches(
        trimmed + "\n", repo_root=PROJECT_ROOT, slice_root=SLICE
    )
    assert f"fixtures: missing key {SYMMETRIC_FIXTURE.name}" in problems


def test_manifest_rejects_extra_and_traversal_keys() -> None:
    manifest = json.loads(MANIFEST.read_text(encoding="utf-8"))
    generated = {
        **manifest["generated"],
        "generated/../../escaped.lean": "0" * 64,
    }
    extended = json.dumps(
        {**manifest, "generated": generated}, sort_keys=True, indent=2
    )
    problems = manifest_mismatches(
        extended + "\n", repo_root=PROJECT_ROOT, slice_root=SLICE
    )
    assert "generated: unexpected key generated/../../escaped.lean" in problems


def test_manifest_rejects_malformed_json() -> None:
    problems = manifest_mismatches(
        "{not json", repo_root=PROJECT_ROOT, slice_root=SLICE
    )
    assert problems and problems[0].startswith("manifest: malformed JSON")


def test_regeneration_does_not_bypass_stored_digest() -> None:
    manifest = json.loads(MANIFEST.read_text(encoding="utf-8"))
    key = "generated/probe_symmetric.lean"
    stored = manifest["generated"][key]
    tampered_stored = "1" * 64
    assert tampered_stored != stored
    regenerated = {key: stored}  # regeneration agrees with on-disk bytes
    tampered_text = (
        json.dumps(
            {**manifest, "generated": {**manifest["generated"], key: tampered_stored}},
            sort_keys=True,
            indent=2,
        )
        + "\n"
    )
    problems = manifest_mismatches(
        tampered_text,
        repo_root=PROJECT_ROOT,
        slice_root=SLICE,
        regenerate=regenerated,
    )
    assert any(
        problem.startswith(f"{key}: on-disk ") and "manifest 1111" in problem
        for problem in problems
    )


@pytest.mark.parametrize(
    "field", ["fixture_digest", "probe_digest", "extractor_digest", "payload", "slice"]
)
def test_manifest_rejects_malformed_values(field: str) -> None:
    payload = json.loads(MANIFEST.read_text())
    if field == "fixture_digest":
        payload["fixtures"]["pymdp_symmetric_runner.py"] = None
    elif field == "probe_digest":
        payload["generated"]["generated/probe_symmetric.lean"] = False
    elif field == "extractor_digest":
        payload["extractor_sha256"] = None
    elif field == "payload":
        payload["expected_payload"] = {}
    else:
        payload["slice"] = "different-slice"
    assert manifest_mismatches(
        json.dumps(payload), repo_root=PROJECT_ROOT, slice_root=SLICE
    )


def test_manifest_rejects_duplicate_json_fields() -> None:
    text = MANIFEST.read_text()
    duplicated = text.replace("{", '{"slice":"wrong",', 1)
    assert manifest_mismatches(duplicated, repo_root=PROJECT_ROOT, slice_root=SLICE)


def test_asymmetric_transition_distinguishes_every_axis_permutation() -> None:
    from itertools import permutations, product

    table = _tables(ASYMMETRIC_FIXTURE.read_text()).table("B_data")
    for order in permutations(range(3)):
        if order != (0, 1, 2):
            assert any(
                table.get(index) != table.get(tuple(index[axis] for axis in order))
                for index in product(range(2), repeat=3)
            ), f"asymmetric fixture hides axis permutation {order}"


@pytest.mark.serial_lean
def test_lean_rejects_normalized_previous_policy_axis_swap(tmp_path: Path) -> None:
    original = ASYMMETRIC_FIXTURE.read_text()
    mutated = original.replace(
        "[[0.25, 0.5], [0.75, 0.125]]", "[[0.25, 0.75], [0.5, 0.125]]"
    ).replace("[[0.75, 0.5], [0.25, 0.875]]", "[[0.75, 0.25], [0.5, 0.875]]")
    assert mutated != original
    tables = _tables(mutated)  # This permutation preserves normalization.
    source = render_lean_probe(
        tables,
        variant="asymmetric",
        fixture_name="axis-mutated.py",
        fixture_sha256=tables.source_sha256,
    )
    probe = tmp_path / "WrongAxes.lean"
    probe.write_text(source)
    result = _compile_probe(probe)
    assert result.returncode != 0
    assert "unsolved goals" in result.stdout + result.stderr
