"""manuscript_vars structure from catalogue. All real methods, no direct execution."""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path

import yaml

from catalogue.topics import FEPTopicCatalogue
from output.manuscript import (
    UNIFIED_FORMALISM_CATALOGUE_FILENAME,
    _count_test_cases,
    _get_latest_verification_manifest,
    _hermes_block_from_summary,
    _read_toolchain_vars,
    _verify_block_from_manifest,
    build_lean_catalogue_markdown,
    build_manuscript_vars,
    build_typeset_equations_markdown,
    build_unified_formalism_appendix_markdown,
    write_manuscript_vars,
    write_unified_formalism_appendix_markdown,
)

PROJ = Path(__file__).resolve().parent.parent


def test_build_manuscript_vars_shape() -> None:
    c = FEPTopicCatalogue.from_yaml(PROJ / "config" / "topics.yaml")
    v = build_manuscript_vars(c, PROJ)
    assert v["total_topics"] == 50
    assert v["total_areas"] == 5
    assert len(v["topic_ids"]) == 50
    t035 = next(t for t in c.topics if t.id == "fep-035")
    row035 = v["topics"]["fep-035"]
    assert row035["area"] == "FEP"
    assert row035["maturity"] == "real"
    assert row035["maturity_icon"] == "✅"
    assert row035["mathlib_status"] == "real"
    assert int(row035["lean_chars"]) == t035.lean_chars
    assert row035["nl_statement"] == t035.nl
    assert row035["lean_sketch"] == t035.lean_sketch
    assert "maturity_icon" in v["topics"]["fep-035"]
    assert "lean_chars" in v["topics"]["fep-035"]
    assert "verify" in v
    assert v["lean_toolchain"] == (PROJ / "lean" / "lean-toolchain").read_text(
        encoding="utf-8"
    ).strip().splitlines()[0]
    assert v["lean_version"] == "4.29.0"
    assert v["mathlib_tag"] == "v4.29.0"


def test_read_toolchain_vars_matches_disk(tmp_path: Path) -> None:
    lean = tmp_path / "lean"
    lean.mkdir(parents=True)
    (lean / "lean-toolchain").write_text("leanprover/lean4:v4.29.0\n", encoding="utf-8")
    (lean / "lakefile.lean").write_text(
        'require mathlib from git\n  "https://github.com/leanprover-community/mathlib4.git" @ "v4.29.0"\n',
        encoding="utf-8",
    )
    t = _read_toolchain_vars(tmp_path)
    assert t["lean_toolchain"] == "leanprover/lean4:v4.29.0"
    assert t["lean_version"] == "4.29.0"
    assert t["mathlib_tag"] == "v4.29.0"


def test_read_toolchain_vars_fallback_lake_manifest(tmp_path: Path) -> None:
    lean = tmp_path / "lean"
    lean.mkdir(parents=True)
    (lean / "lean-toolchain").write_text("leanprover/lean4:v4.29.0\n", encoding="utf-8")
    (lean / "lakefile.lean").write_text("package foo\n", encoding="utf-8")
    (lean / "lake-manifest.json").write_text(
        '{"packages": [{"name": "mathlib", "inputRev": "v4.29.0"}]}',
        encoding="utf-8",
    )
    t = _read_toolchain_vars(tmp_path)
    assert t["mathlib_tag"] == "v4.29.0"


def test_build_lean_catalogue_markdown_matches_topics() -> None:
    c = FEPTopicCatalogue.from_yaml(PROJ / "config" / "topics.yaml")
    md = build_lean_catalogue_markdown(c)
    assert md.count("\n```lean\n") == 50
    assert "**Version**:" not in md
    assert "**Status**: Generated" not in md
    assert "**Source**: `src/output/manuscript.py`" not in md
    for t in c.topics:
        assert t.id in md
        assert t.lean_sketch.strip() in md


def test_write_unified_formalism_appendix_markdown_roundtrip(tmp_path: Path) -> None:
    import shutil

    shutil.copytree(PROJ / "config", tmp_path / "config")
    (tmp_path / "manuscript").mkdir(parents=True, exist_ok=True)
    c = FEPTopicCatalogue.from_yaml(tmp_path / "config" / "topics.yaml")
    out = write_unified_formalism_appendix_markdown(tmp_path, c)
    assert out.is_file()
    assert out.name == UNIFIED_FORMALISM_CATALOGUE_FILENAME
    out2 = write_unified_formalism_appendix_markdown(tmp_path, c)
    assert out2.resolve() == out.resolve()
    text = out.read_text(encoding="utf-8")
    assert text.count("```lean") == 50
    assert "## fep-001 —" in text
    assert "## fep-050 —" in text
    assert "### Lean sketch" in text
    assert "### Typeset statement signatures" in text
    assert "**Version**:" not in text
    assert "**Status**: Generated" not in text
    assert "**Source**: `src/output/manuscript.py`" not in text
    assert text.startswith("<!-- AUTO-GENERATED by src/output/manuscript.py")


def test_build_typeset_equations_markdown_structure() -> None:
    c = FEPTopicCatalogue.from_yaml(PROJ / "config" / "topics.yaml")
    md = build_typeset_equations_markdown(c, PROJ)
    assert "# Appendix C:" in md
    assert "sec:appendix_c_latex_equations" in md
    for t in c.topics:
        assert f"## {t.id} —" in md
        assert f"sec:eqs-{t.id}" in md
        n_eq = len(re.findall(rf"\\label\{{eq:{re.escape(t.id)}-\d+\}}", md))
        n_th = len(re.findall(r"^\s*theorem\s+", t.lean_sketch, re.MULTILINE))
        assert n_eq > 0
        assert n_eq == n_th


def test_build_unified_formalism_appendix_markdown_structure() -> None:
    c = FEPTopicCatalogue.from_yaml(PROJ / "config" / "topics.yaml")
    md = build_unified_formalism_appendix_markdown(c, PROJ)
    assert "sec:appendix_b_full_topic_lean_catalogue" in md
    assert r"\label{sec:appendix_c_latex_equations}" in md
    assert md.count("### Lean sketch") == 50
    assert md.count("### Typeset statement signatures") == 50
    for t in c.topics:
        assert f"{{#sec:catalogue-{t.id}}}" in md
        assert f"{{#sec:eqs-{t.id}}}" in md


def test_fep_001_latex_equations_from_yaml_matches_data_module() -> None:
    if str(PROJ / "scripts") not in sys.path:
        sys.path.insert(0, str(PROJ / "scripts"))
    from catalogue_sketches import LATEX_EQUATIONS, THEOREM_LATEX

    c = FEPTopicCatalogue.from_yaml(PROJ / "config" / "topics.yaml")
    t1 = next(t for t in c.topics if t.id == "fep-001")
    assert t1.latex_equations == tuple(LATEX_EQUATIONS["fep-001"])
    assert t1.latex_equations[0] == THEOREM_LATEX["fep001_measure_union_le"]


def test_theorem_latex_is_probability_measure_not_double_wrapped() -> None:
    if str(PROJ / "scripts") not in sys.path:
        sys.path.insert(0, str(PROJ / "scripts"))
    from catalogue_sketches import THEOREM_LATEX

    s = THEOREM_LATEX["fep002_prob_measure_univ"]
    assert r"\mathsf{IsProbability\mathsf{Measure}" not in s
    assert r"\mathsf{IsProbabili\mathsf{Measure}" not in s
    assert r"\mathsf{IsProbabilityMeasure}" in s
    s2 = THEOREM_LATEX["fep002_prob_compl"]
    assert r"\mathsf{IsProbability\mathsf{Measure}" not in s2
    assert r"\mathsf{IsProbabilityMeasure}" in s2


def test_verify_block_from_manifest_missing() -> None:
    b = _verify_block_from_manifest(None)
    assert b["manifest_present"] is False


def test_verify_block_from_manifest_invalid_json(tmp_path: Path) -> None:
    p = tmp_path / "verification_manifest.json"
    p.write_text("{not json", encoding="utf-8")
    b = _verify_block_from_manifest(p)
    assert b["manifest_present"] is True
    assert b["verify_lean_ran"] is False


def test_verify_block_from_manifest_topics_fallback(tmp_path: Path) -> None:
    p = tmp_path / "verification_manifest.json"
    p.write_text('{"results": [{"x": 1}, {"x": 2}]}', encoding="utf-8")
    b = _verify_block_from_manifest(p)
    assert b["topics_with_result"] == 2


def test_latest_verification_manifest_newest(tmp_path: Path) -> None:
    base = tmp_path / "output" / "reports"
    old = base / "run_old"
    new = base / "run_new"
    old.mkdir(parents=True)
    new.mkdir(parents=True)
    (old / "verification_manifest.json").write_text("{}", encoding="utf-8")
    (new / "verification_manifest.json").write_text("{}", encoding="utf-8")
    import os
    import time

    os.utime(new / "verification_manifest.json", (time.time() + 10, time.time() + 10))
    picked = _get_latest_verification_manifest(tmp_path)
    assert picked is not None
    assert "run_new" in str(picked)


def test_manuscript_vars_honor_explicit_output_root(tmp_path: Path) -> None:
    custom = tmp_path / "custom-output" / "reports" / "run_custom"
    custom.mkdir(parents=True)
    (custom / "verification_manifest.json").write_text(
        json.dumps(
            {
                "verify_lean_ran": True,
                "topics_with_result": 1,
                "compiles_true": 1,
                "compiles_false": 0,
                "results": [{"topic_id": "fep-001", "compiles": True}],
            }
        ),
        encoding="utf-8",
    )
    c = FEPTopicCatalogue.from_yaml(PROJ / "config" / "topics.yaml")
    values = build_manuscript_vars(c, PROJ, output_root=tmp_path / "custom-output")
    assert values["verify"]["topics_with_result"] == 1


def test_verify_block_from_manifest_json(tmp_path: Path) -> None:
    p = tmp_path / "verification_manifest.json"
    p.write_text(
        json.dumps(
            {
                "verify_lean_ran": True,
                "topics_with_result": 3,
                "compiles_true": 1,
                "compiles_false": 2,
            }
        ),
        encoding="utf-8",
    )
    b = _verify_block_from_manifest(p)
    assert b["manifest_present"] is True
    assert b["verify_lean_ran"] is True
    assert b["topics_with_result"] == 3


def test_hermes_block_missing_summary_returns_zeros() -> None:
    block = _hermes_block_from_summary(None)
    assert block["summary_present"] is False
    assert block["processed"] == 0
    assert block["success_count"] == 0
    assert block["tokens_total"] == 0
    assert block["primary_model"] == ""
    assert block["models_used"] == ""


def test_hermes_block_aggregates_from_summary(tmp_path: Path) -> None:
    summary_path = tmp_path / "summary.json"
    summary_path.write_text(
        json.dumps(
            {
                "run_id": "20260420_111111",
                "topics": [
                    {
                        "topic_id": "fep-001",
                        "hermes_success": True,
                        "lean_compiles": True,
                        "hermes_lean_compiles": True,
                        "cache_hit": True,
                        "tokens_used": 1000,
                        "hermes_model": "z-ai/glm-5.1",
                    },
                    {
                        "topic_id": "fep-002",
                        "hermes_success": True,
                        "lean_compiles": True,
                        "hermes_lean_compiles": False,
                        "cache_hit": False,
                        "tokens_used": 2000,
                        "hermes_model": "z-ai/glm-5.1",
                    },
                    {
                        "topic_id": "fep-003",
                        "hermes_success": False,
                        "lean_compiles": False,
                        "cache_hit": False,
                        "tokens_used": 0,
                        "hermes_model": "",
                    },
                ],
            }
        ),
        encoding="utf-8",
    )
    block = _hermes_block_from_summary(summary_path)
    assert block["summary_present"] is True
    assert block["run_id"] == "run_20260420_111111"
    assert block["processed"] == 3
    assert block["success_count"] == 2
    assert block["cache_hits"] == 1
    assert block["tokens_total"] == 3000
    assert block["tokens_mean"] == 1500
    assert block["hermes_lean_compiles_count"] == 1
    assert block["hermes_lean_compiles_count"] == 1
    assert block["primary_model"] == "z-ai/glm-5.1"
    assert "z-ai/glm-5.1" in block["models_used"]
    # All three topics used the same model, so the OpenRouter chain never
    # had to advance past the primary; ``model_fallback_count`` reports 0.
    assert block["model_fallback_count"] == 0
    # No per-topic ``network_retries`` or ``chain_advance_reason`` fields in
    # this fixture ⇒ aggregates default to zero / empty.
    assert block["network_retry_count"] == 0
    assert block["chain_advance_reasons"] == {}
    assert block["chain_advance_reasons_summary"] == "none"


def test_hermes_block_counts_model_chain_advances(tmp_path: Path) -> None:
    """When a topic's final model differs from the primary (most-used) model,
    ``model_fallback_count`` reports it.  Distinct from ``fallback_count``,
    which reports a model-chain advance rather than a source substitution.

    Also asserts that per-topic ``network_retries`` sum into
    ``network_retry_count`` and ``chain_advance_reason`` strings are tallied
    into ``chain_advance_reasons``.
    """
    summary_path = tmp_path / "summary.json"
    summary_path.write_text(
        json.dumps(
            {
                "run_id": "20260420_222222",
                "topics": [
                    {
                        "hermes_model": "moonshotai/kimi-k2.6",
                        "hermes_success": True,
                        "network_retries": 1,
                    },
                    {
                        "hermes_model": "moonshotai/kimi-k2.6",
                        "hermes_success": True,
                        "network_retries": 0,
                    },
                    {
                        "hermes_model": "moonshotai/kimi-k2-thinking",
                        "hermes_success": True,
                        "network_retries": 2,
                        "chain_advance_reason": "empty_content",
                    },
                ],
            }
        ),
        encoding="utf-8",
    )
    block = _hermes_block_from_summary(summary_path)
    assert block["primary_model"] == "moonshotai/kimi-k2.6"
    assert block["model_fallback_count"] == 1
    assert block["network_retry_count"] == 3
    assert block["chain_advance_reasons"] == {"empty_content": 1}
    assert block["chain_advance_reasons_summary"] == "1× empty_content"


def test_hermes_block_aggregates_chain_reasons(tmp_path: Path) -> None:
    """Distinct chain-advance reasons aggregate into a sorted summary string."""
    summary_path = tmp_path / "summary.json"
    summary_path.write_text(
        json.dumps(
            {
                "run_id": "20260420_222333",
                "topics": [
                    {
                        "hermes_model": "openai/gpt-oss-120b:free",
                        "hermes_success": True,
                        "chain_advance_reason": "wall_clock_timeout",
                    },
                    {
                        "hermes_model": "openai/gpt-oss-120b:free",
                        "hermes_success": True,
                        "chain_advance_reason": "wall_clock_timeout",
                    },
                    {
                        "hermes_model": "deepseek/deepseek-chat-v3.1:free",
                        "hermes_success": True,
                        "chain_advance_reason": "transport_error",
                    },
                ],
            }
        ),
        encoding="utf-8",
    )
    block = _hermes_block_from_summary(summary_path)
    assert block["chain_advance_reasons"] == {
        "wall_clock_timeout": 2,
        "transport_error": 1,
    }
    # Summary is sorted by descending count, so wall_clock_timeout comes first.
    assert block["chain_advance_reasons_summary"] == (
        "2× wall_clock_timeout, 1× transport_error"
    )


def test_build_manuscript_vars_exposes_hermes_block(tmp_path: Path) -> None:
    """``build_manuscript_vars`` must expose a top-level ``hermes`` block when a
    sibling ``summary.json`` is present alongside the verification manifest."""
    import shutil

    shutil.copytree(PROJ / "config", tmp_path / "config")
    (tmp_path / "manuscript").mkdir()
    # _read_toolchain_vars only reads ``lean-toolchain``, ``lakefile.lean``,
    # ``lake-manifest.json``; skip the multi-GB ``.lake`` build cache and the
    # transient FepSketches verification scratch dir.
    shutil.copytree(
        PROJ / "lean",
        tmp_path / "lean",
        ignore=shutil.ignore_patterns(".lake", "FepSketches"),
    )
    run_dir = tmp_path / "output" / "reports" / "run_test_hermes_block"
    run_dir.mkdir(parents=True)
    (run_dir / "verification_manifest.json").write_text(
        json.dumps(
            {
                "verify_lean_ran": True,
                "topics_with_result": 2,
                "compiles_true": 2,
                "compiles_false": 0,
                "results": [
                    {"topic_id": "fep-001", "compiles": True, "lean_has_sorry": False},
                    {"topic_id": "fep-002", "compiles": True, "lean_has_sorry": False},
                ],
            }
        ),
        encoding="utf-8",
    )
    (run_dir / "summary.json").write_text(
        json.dumps(
            {
                "run_id": "test_hermes_block",
                "topics": [
                    {
                        "topic_id": "fep-001",
                        "hermes_success": True,
                        "lean_compiles": True,
                        "hermes_lean_compiles": True,
                        "cache_hit": False,
                        "tokens_used": 500,
                        "hermes_model": "z-ai/glm-5.1",
                    },
                    {
                        "topic_id": "fep-002",
                        "hermes_success": True,
                        "lean_compiles": True,
                        "hermes_lean_compiles": True,
                        "cache_hit": True,
                        "tokens_used": 1500,
                        "hermes_model": "z-ai/glm-5.1",
                    },
                ],
            }
        ),
        encoding="utf-8",
    )
    c = FEPTopicCatalogue.from_yaml(tmp_path / "config" / "topics.yaml")
    v = build_manuscript_vars(c, tmp_path)
    assert "hermes" in v
    assert v["hermes"]["summary_present"] is True
    assert v["hermes"]["processed"] == 2
    assert v["hermes"]["success_count"] == 2
    assert v["hermes"]["cache_hits"] == 1
    assert v["hermes"]["tokens_mean"] == 1000
    assert v["hermes"]["primary_model"] == "z-ai/glm-5.1"
    assert v["hermes"]["hermes_lean_compiles_count"] == 2
    assert "fallback_count" not in v["hermes"]
    assert "tests" in v
    assert isinstance(v["tests"]["collected"], int)


def test_write_manuscript_vars_roundtrip(tmp_path: Path) -> None:
    import shutil

    shutil.copytree(PROJ / "config", tmp_path / "config")
    (tmp_path / "manuscript").mkdir()
    (tmp_path / "manuscript" / "config.yaml").write_text("paper:\n  title: t\n", encoding="utf-8")
    for d in ("scripts", "tests", "src", "output"):
        (tmp_path / d).mkdir()
    (tmp_path / "src" / "__init__.py").write_text('"""x"""\n', encoding="utf-8")
    shutil.copytree(
        PROJ / "lean",
        tmp_path / "lean",
        ignore=shutil.ignore_patterns(".lake", "FepSketches"),
    )

    c = FEPTopicCatalogue.from_yaml(tmp_path / "config" / "topics.yaml")
    out = write_manuscript_vars(tmp_path, c)
    assert out.is_file()
    data = yaml.safe_load(out.read_text(encoding="utf-8"))
    assert data["total_topics"] == len(c.topics)
    assert data["lean_version"] == "4.29.0"
    assert data["mathlib_tag"] == "v4.29.0"
    assert data["lean_toolchain"].startswith("leanprover/lean4:")


def test_count_test_cases_invalidates_on_test_change(tmp_path: Path) -> None:
    """``_count_test_cases`` reuses the cache when fresh, but a newer
    ``tests/*.py`` file (mtime > cache mtime) invalidates the cache and
    forces a fresh ``pytest --collect-only`` run on the next call.

    The actual collection is suppressed by pointing ``project_root`` at an
    isolated ``tmp_path`` with a single trivial test file, so the test
    completes in well under a second.
    """
    import os
    import time as _time

    (tmp_path / "tests").mkdir()
    test_file = tmp_path / "tests" / "test_sample.py"
    test_file.write_text(
        "def test_a(): assert 1 == 1\ndef test_b(): assert 2 == 2\n",
        encoding="utf-8",
    )
    cache_dir = tmp_path / "output" / ".cache"
    cache_dir.mkdir(parents=True)
    cache_path = cache_dir / "tests_collected.json"

    cache_path.write_text(json.dumps({"collected": 99, "ts": "fixture"}), encoding="utf-8")
    old_mtime = cache_path.stat().st_mtime - 10.0
    os.utime(cache_path, (old_mtime, old_mtime))
    test_mtime = old_mtime - 100.0
    os.utime(test_file, (test_mtime, test_mtime))
    n_fresh = _count_test_cases(tmp_path)
    assert n_fresh == 99, "fresh cache must be reused"

    new_mtime = _time.time() + 5.0
    os.utime(test_file, (new_mtime, new_mtime))
    n_stale = _count_test_cases(tmp_path)
    assert n_stale != 99, (
        "test-file mtime newer than cache mtime must invalidate cache; "
        f"got {n_stale} (expected fresh collection)"
    )
