import Mathlib.Analysis.Matrix.PosDef
import Mathlib.Analysis.Normed.Algebra.MatrixExponential
import Mathlib.Analysis.SpecialFunctions.Exponential
import Mathlib.Tactic.NoncommRing
import Mathlib.Topology.Instances.NNReal.Lemmas

/-!
# H2.5b-R0 transition covariance proof spike

This bounded spike tests the generic finite-axis matrix theorem needed before a
maintained transition-covariance foundation is authorized.
-/

open Matrix
open scoped ComplexOrder NNReal

namespace FEP.TransitionCovarianceR0

variable {Axis : Type*} [Fintype Axis] [DecidableEq Axis]

/-- The stationary covariance derived from a raw precision matrix. -/
noncomputable def covariance (precision : Matrix Axis Axis ℝ) : Matrix Axis Axis ℝ :=
  precision⁻¹

/-- The matrix-exponential evolution generated by a precision matrix. -/
noncomputable def evolution (precision : Matrix Axis Axis ℝ) (time : ℝ≥0) :
    Matrix Axis Axis ℝ :=
  NormedSpace.exp ((-(time : ℝ)) • precision)

/-- The finite-time transition covariance of the reversible linear Gaussian flow. -/
noncomputable def transitionCovariance (precision : Matrix Axis Axis ℝ) (time : ℝ≥0) :
    Matrix Axis Axis ℝ :=
  covariance precision -
    evolution precision time * covariance precision * (evolution precision time)ᵀ

private lemma unitary_inverse_eq_transpose (U : unitary (Matrix Axis Axis ℝ)) :
    ((U : Matrix Axis Axis ℝ)⁻¹) = (U : Matrix Axis Axis ℝ)ᵀ := by
  apply Matrix.inv_eq_left_inv
  simpa only [Matrix.star_eq_conjTranspose, Matrix.conjTranspose_eq_transpose_of_trivial] using
    Unitary.coe_star_mul_self U

private lemma precision_spectral_form (precision : Matrix Axis Axis ℝ)
    (hPrecision : precision.PosDef) :
    precision =
      (hPrecision.isHermitian.eigenvectorUnitary : Matrix Axis Axis ℝ) *
        Matrix.diagonal hPrecision.isHermitian.eigenvalues *
          (hPrecision.isHermitian.eigenvectorUnitary : Matrix Axis Axis ℝ)ᵀ := by
  simpa only [Unitary.conjStarAlgAut_apply, RCLike.ofReal_real_eq_id, Function.id_comp,
    Matrix.star_eq_conjTranspose, Matrix.conjTranspose_eq_transpose_of_trivial] using
      hPrecision.isHermitian.spectral_theorem

private lemma covariance_spectral_form (precision : Matrix Axis Axis ℝ)
    (hPrecision : precision.PosDef) :
    covariance precision =
      (hPrecision.isHermitian.eigenvectorUnitary : Matrix Axis Axis ℝ) *
        Matrix.diagonal (fun i => (hPrecision.isHermitian.eigenvalues i)⁻¹) *
          (hPrecision.isHermitian.eigenvectorUnitary : Matrix Axis Axis ℝ)ᵀ := by
  rw [covariance]
  apply Matrix.inv_eq_right_inv
  calc
    precision *
          ((hPrecision.isHermitian.eigenvectorUnitary : Matrix Axis Axis ℝ) *
            Matrix.diagonal (fun i => (hPrecision.isHermitian.eigenvalues i)⁻¹) *
              (hPrecision.isHermitian.eigenvectorUnitary : Matrix Axis Axis ℝ)ᵀ) =
        ((hPrecision.isHermitian.eigenvectorUnitary : Matrix Axis Axis ℝ) *
            Matrix.diagonal hPrecision.isHermitian.eigenvalues *
              (hPrecision.isHermitian.eigenvectorUnitary : Matrix Axis Axis ℝ)ᵀ) *
          ((hPrecision.isHermitian.eigenvectorUnitary : Matrix Axis Axis ℝ) *
            Matrix.diagonal (fun i => (hPrecision.isHermitian.eigenvalues i)⁻¹) *
              (hPrecision.isHermitian.eigenvectorUnitary : Matrix Axis Axis ℝ)ᵀ) := by
        rw [← precision_spectral_form precision hPrecision]
    _ = 1 := by
      have hUnit :
        (hPrecision.isHermitian.eigenvectorUnitary : Matrix Axis Axis ℝ)ᵀ *
            (hPrecision.isHermitian.eigenvectorUnitary : Matrix Axis Axis ℝ) = 1 := by
          simpa only [Matrix.star_eq_conjTranspose,
            Matrix.conjTranspose_eq_transpose_of_trivial] using
              Unitary.coe_star_mul_self hPrecision.isHermitian.eigenvectorUnitary
      have hUnitRight :
          (hPrecision.isHermitian.eigenvectorUnitary : Matrix Axis Axis ℝ) *
              (hPrecision.isHermitian.eigenvectorUnitary : Matrix Axis Axis ℝ)ᵀ = 1 := by
        simpa only [Matrix.star_eq_conjTranspose,
          Matrix.conjTranspose_eq_transpose_of_trivial, Unitary.coe_star] using
            Unitary.coe_mul_star_self hPrecision.isHermitian.eigenvectorUnitary
      have hDiagonalInverse :
          Matrix.diagonal hPrecision.isHermitian.eigenvalues *
              Matrix.diagonal (fun i => (hPrecision.isHermitian.eigenvalues i)⁻¹) = 1 := by
        rw [Matrix.diagonal_mul_diagonal]
        ext i j
        by_cases hij : i = j
        · subst j
          simp [hPrecision.eigenvalues_pos i |>.ne']
        · simp [hij]
      calc
        _ =
            (hPrecision.isHermitian.eigenvectorUnitary : Matrix Axis Axis ℝ) *
              Matrix.diagonal hPrecision.isHermitian.eigenvalues *
                ((hPrecision.isHermitian.eigenvectorUnitary : Matrix Axis Axis ℝ)ᵀ *
                  (hPrecision.isHermitian.eigenvectorUnitary : Matrix Axis Axis ℝ)) *
                    Matrix.diagonal
                      (fun i => (hPrecision.isHermitian.eigenvalues i)⁻¹) *
                        (hPrecision.isHermitian.eigenvectorUnitary : Matrix Axis Axis ℝ)ᵀ := by
              noncomm_ring
        _ = 1 := by
          rw [hUnit]
          calc
            _ =
                (hPrecision.isHermitian.eigenvectorUnitary : Matrix Axis Axis ℝ) *
                  (Matrix.diagonal hPrecision.isHermitian.eigenvalues *
                    Matrix.diagonal
                      (fun i => (hPrecision.isHermitian.eigenvalues i)⁻¹)) *
                    (hPrecision.isHermitian.eigenvectorUnitary : Matrix Axis Axis ℝ)ᵀ := by
              noncomm_ring
            _ = 1 := by rw [hDiagonalInverse]; simpa using hUnitRight

private lemma evolution_spectral_form (precision : Matrix Axis Axis ℝ)
    (hPrecision : precision.PosDef) (time : ℝ≥0) :
    evolution precision time =
      (hPrecision.isHermitian.eigenvectorUnitary : Matrix Axis Axis ℝ) *
        Matrix.diagonal
          (fun i => Real.exp (-((time : ℝ) * hPrecision.isHermitian.eigenvalues i))) *
          (hPrecision.isHermitian.eigenvectorUnitary : Matrix Axis Axis ℝ)ᵀ := by
  rw [evolution]
  calc
    NormedSpace.exp ((-(time : ℝ)) • precision) =
        NormedSpace.exp
          ((-(time : ℝ)) •
            ((hPrecision.isHermitian.eigenvectorUnitary : Matrix Axis Axis ℝ) *
              Matrix.diagonal hPrecision.isHermitian.eigenvalues *
                (hPrecision.isHermitian.eigenvectorUnitary : Matrix Axis Axis ℝ)ᵀ)) := by
      exact congrArg (fun matrix : Matrix Axis Axis ℝ =>
        NormedSpace.exp ((-(time : ℝ)) • matrix))
          (precision_spectral_form precision hPrecision)
    _ = NormedSpace.exp
        ((hPrecision.isHermitian.eigenvectorUnitary : Matrix Axis Axis ℝ) *
          ((-(time : ℝ)) • Matrix.diagonal hPrecision.isHermitian.eigenvalues) *
            (hPrecision.isHermitian.eigenvectorUnitary : Matrix Axis Axis ℝ)ᵀ) := by
      congr 1
      simp
    _ =
        (hPrecision.isHermitian.eigenvectorUnitary : Matrix Axis Axis ℝ) *
          Matrix.diagonal
            (fun i => Real.exp (-((time : ℝ) * hPrecision.isHermitian.eigenvalues i))) *
            (hPrecision.isHermitian.eigenvectorUnitary : Matrix Axis Axis ℝ)ᵀ := by
      rw [← unitary_inverse_eq_transpose hPrecision.isHermitian.eigenvectorUnitary]
      rw [Matrix.exp_conj
        (hPrecision.isHermitian.eigenvectorUnitary : Matrix Axis Axis ℝ)
        ((-(time : ℝ)) • Matrix.diagonal hPrecision.isHermitian.eigenvalues)
        Unitary.isUnit_coe]
      rw [← Matrix.diagonal_smul, Matrix.exp_diagonal]
      rw [Pi.exp_def]
      congr 1
      funext i
      rw [← Real.exp_eq_exp_ℝ]
      simp
private lemma conjugate_mul (U : Matrix Axis Axis ℝ)
    (hUnit : Uᵀ * U = 1) (A B : Matrix Axis Axis ℝ) :
    (U * A * Uᵀ) * (U * B * Uᵀ) = U * (A * B) * Uᵀ := by
  calc
    _ = U * A * (Uᵀ * U) * B * Uᵀ := by noncomm_ring
    _ = U * (A * B) * Uᵀ := by rw [hUnit]; noncomm_ring

private lemma transitionCovariance_spectral_form (precision : Matrix Axis Axis ℝ)
    (hPrecision : precision.PosDef) (time : ℝ≥0) :
    transitionCovariance precision time =
      (hPrecision.isHermitian.eigenvectorUnitary : Matrix Axis Axis ℝ) *
        Matrix.diagonal (fun i =>
          (hPrecision.isHermitian.eigenvalues i)⁻¹ -
            Real.exp (-((time : ℝ) * hPrecision.isHermitian.eigenvalues i)) *
              (hPrecision.isHermitian.eigenvalues i)⁻¹ *
                Real.exp (-((time : ℝ) * hPrecision.isHermitian.eigenvalues i))) *
          (hPrecision.isHermitian.eigenvectorUnitary : Matrix Axis Axis ℝ)ᵀ := by
  rw [transitionCovariance, covariance_spectral_form precision hPrecision,
    evolution_spectral_form precision hPrecision]
  have hUnit :
    (hPrecision.isHermitian.eigenvectorUnitary : Matrix Axis Axis ℝ)ᵀ *
        (hPrecision.isHermitian.eigenvectorUnitary : Matrix Axis Axis ℝ) = 1 := by
      simpa only [Matrix.star_eq_conjTranspose,
        Matrix.conjTranspose_eq_transpose_of_trivial] using
        Unitary.coe_star_mul_self hPrecision.isHermitian.eigenvectorUnitary
  have hEvolutionTranspose :
      ((hPrecision.isHermitian.eigenvectorUnitary : Matrix Axis Axis ℝ) *
          Matrix.diagonal
            (fun i => Real.exp (-((time : ℝ) * hPrecision.isHermitian.eigenvalues i))) *
            (hPrecision.isHermitian.eigenvectorUnitary : Matrix Axis Axis ℝ)ᵀ)ᵀ =
        (hPrecision.isHermitian.eigenvectorUnitary : Matrix Axis Axis ℝ) *
          Matrix.diagonal
            (fun i => Real.exp (-((time : ℝ) * hPrecision.isHermitian.eigenvalues i))) *
            (hPrecision.isHermitian.eigenvectorUnitary : Matrix Axis Axis ℝ)ᵀ := by
    rw [Matrix.transpose_mul, Matrix.transpose_mul]
    simp [Matrix.mul_assoc]
  rw [hEvolutionTranspose]
  rw [conjugate_mul _ hUnit]
  rw [conjugate_mul _ hUnit]
  have hDiagonalProduct :
      Matrix.diagonal (fun i => (hPrecision.isHermitian.eigenvalues i)⁻¹) -
          Matrix.diagonal
              (fun i => Real.exp (-((time : ℝ) * hPrecision.isHermitian.eigenvalues i))) *
            Matrix.diagonal (fun i => (hPrecision.isHermitian.eigenvalues i)⁻¹) *
              Matrix.diagonal
                (fun i => Real.exp (-((time : ℝ) * hPrecision.isHermitian.eigenvalues i))) =
        Matrix.diagonal (fun i =>
          (hPrecision.isHermitian.eigenvalues i)⁻¹ -
            Real.exp (-((time : ℝ) * hPrecision.isHermitian.eigenvalues i)) *
              (hPrecision.isHermitian.eigenvalues i)⁻¹ *
                Real.exp (-((time : ℝ) * hPrecision.isHermitian.eigenvalues i))) := by
    ext i j
    by_cases hij : i = j
    · subst j
      simp
    · simp [hij]
  calc
    _ =
        (hPrecision.isHermitian.eigenvectorUnitary : Matrix Axis Axis ℝ) *
          (Matrix.diagonal (fun i => (hPrecision.isHermitian.eigenvalues i)⁻¹) -
            Matrix.diagonal
                (fun i => Real.exp (-((time : ℝ) * hPrecision.isHermitian.eigenvalues i))) *
              Matrix.diagonal (fun i => (hPrecision.isHermitian.eigenvalues i)⁻¹) *
                Matrix.diagonal
                  (fun i => Real.exp (-((time : ℝ) * hPrecision.isHermitian.eigenvalues i)))) *
            (hPrecision.isHermitian.eigenvectorUnitary : Matrix Axis Axis ℝ)ᵀ := by
      noncomm_ring
    _ = _ := by rw [hDiagonalProduct]

/-- The transition covariance vanishes at time zero. -/
theorem transitionCovariance_zero (precision : Matrix Axis Axis ℝ) :
    transitionCovariance precision 0 = 0 := by
  simp [transitionCovariance, evolution]

/-- A positive-definite precision induces a positive-semidefinite covariance at every time. -/
theorem transitionCovariance_posSemidef (precision : Matrix Axis Axis ℝ)
    (hPrecision : precision.PosDef) (time : ℝ≥0) :
    (transitionCovariance precision time).PosSemidef := by
  rw [transitionCovariance_spectral_form precision hPrecision time]
  suffices hDiagonal :
      (Matrix.diagonal (fun i =>
        (hPrecision.isHermitian.eigenvalues i)⁻¹ -
          Real.exp (-((time : ℝ) * hPrecision.isHermitian.eigenvalues i)) *
            (hPrecision.isHermitian.eigenvalues i)⁻¹ *
              Real.exp (-((time : ℝ) * hPrecision.isHermitian.eigenvalues i)))).PosSemidef by
    simpa only [Matrix.star_eq_conjTranspose,
      Matrix.conjTranspose_eq_transpose_of_trivial] using
        (Unitary.isUnit_coe.posSemidef_star_right_conjugate_iff.mpr hDiagonal)
  rw [Matrix.posSemidef_diagonal_iff]
  intro i
  have hEigenvalue := hPrecision.eigenvalues_pos i
  have hExponent : -((time : ℝ) * hPrecision.isHermitian.eigenvalues i) ≤ 0 := by
    exact neg_nonpos.mpr (mul_nonneg time.coe_nonneg hEigenvalue.le)
  have hExpLe : Real.exp (-((time : ℝ) * hPrecision.isHermitian.eigenvalues i)) ≤ 1 :=
    Real.exp_le_one_iff.mpr hExponent
  have hExpPos : 0 < Real.exp (-((time : ℝ) * hPrecision.isHermitian.eigenvalues i)) :=
    Real.exp_pos _
  have hInvPos : 0 < (hPrecision.isHermitian.eigenvalues i)⁻¹ := inv_pos.mpr hEigenvalue
  calc
    _ = (hPrecision.isHermitian.eigenvalues i)⁻¹ *
        ((1 - Real.exp (-((time : ℝ) * hPrecision.isHermitian.eigenvalues i))) *
          (1 + Real.exp (-((time : ℝ) * hPrecision.isHermitian.eigenvalues i)))) := by
      ring
    _ ≥ 0 := mul_nonneg hInvPos.le <| mul_nonneg (sub_nonneg.mpr hExpLe)
      (by positivity)

/-- At positive time, a positive-definite precision induces a positive-definite covariance. -/
theorem transitionCovariance_posDef (precision : Matrix Axis Axis ℝ)
    (hPrecision : precision.PosDef) (time : ℝ≥0) (hTime : 0 < time) :
    (transitionCovariance precision time).PosDef := by
  rw [transitionCovariance_spectral_form precision hPrecision time]
  suffices hDiagonal :
      (Matrix.diagonal (fun i =>
        (hPrecision.isHermitian.eigenvalues i)⁻¹ -
          Real.exp (-((time : ℝ) * hPrecision.isHermitian.eigenvalues i)) *
            (hPrecision.isHermitian.eigenvalues i)⁻¹ *
              Real.exp (-((time : ℝ) * hPrecision.isHermitian.eigenvalues i)))).PosDef by
    simpa only [Matrix.star_eq_conjTranspose,
      Matrix.conjTranspose_eq_transpose_of_trivial] using
        (Unitary.isUnit_coe.posDef_star_right_conjugate_iff.mpr hDiagonal)
  rw [Matrix.posDef_diagonal_iff]
  intro i
  have hEigenvalue := hPrecision.eigenvalues_pos i
  have hProduct : 0 < (time : ℝ) * hPrecision.isHermitian.eigenvalues i :=
    mul_pos (NNReal.coe_pos.mpr hTime) hEigenvalue
  have hExpLt : Real.exp (-((time : ℝ) * hPrecision.isHermitian.eigenvalues i)) < 1 :=
    Real.exp_lt_one_iff.mpr (neg_neg_of_pos hProduct)
  have hExpPos : 0 < Real.exp (-((time : ℝ) * hPrecision.isHermitian.eigenvalues i)) :=
    Real.exp_pos _
  have hInvPos : 0 < (hPrecision.isHermitian.eigenvalues i)⁻¹ := inv_pos.mpr hEigenvalue
  calc
    _ = (hPrecision.isHermitian.eigenvalues i)⁻¹ *
        ((1 - Real.exp (-((time : ℝ) * hPrecision.isHermitian.eigenvalues i))) *
          (1 + Real.exp (-((time : ℝ) * hPrecision.isHermitian.eigenvalues i)))) := by
      ring
    _ > 0 := mul_pos hInvPos <| mul_pos (sub_pos.mpr hExpLt) (by positivity)

private lemma evolution_add (precision : Matrix Axis Axis ℝ) (left right : ℝ≥0) :
    evolution precision (left + right) =
      evolution precision right * evolution precision left := by
  rw [evolution, evolution, evolution]
  rw [NNReal.coe_add, neg_add, add_smul]
  have hCommute :
      Commute ((-(left : ℝ)) • precision) ((-(right : ℝ)) • precision) :=
    (((Commute.refl precision).smul_left (-((left : ℝ)))).smul_right (-((right : ℝ))))
  rw [Matrix.exp_add_of_commute _ _ hCommute, hCommute.exp.eq]

/-- Transition covariances compose in chronological Chapman--Kolmogorov order. -/
theorem transitionCovariance_add (precision : Matrix Axis Axis ℝ)
    (hPrecision : precision.PosDef) (left right : ℝ≥0) :
    transitionCovariance precision (left + right) =
      evolution precision right * transitionCovariance precision left *
          (evolution precision right)ᵀ +
        transitionCovariance precision right := by
  rw [transitionCovariance, transitionCovariance, transitionCovariance, evolution_add]
  have hTranspose (time : ℝ≥0) : (evolution precision time)ᵀ = evolution precision time := by
    apply Matrix.IsSymm.exp
    have hPrecisionSymm : precision.IsSymm :=
      Matrix.isHermitian_iff_isSymm.mp hPrecision.isHermitian
    exact hPrecisionSymm.smul (-((time : ℝ)))
  rw [Matrix.transpose_mul]
  rw [hTranspose left, hTranspose right]
  noncomm_ring

end FEP.TransitionCovarianceR0
