-- AUTO-GENERATED by scripts/_maint_build_fep_all_lean.py
-- Source of truth: scripts/catalogue_sketches.py SKETCHES
-- Do not edit by hand; regenerate after any SKETCHES change.
--
-- Each topic body is wrapped in `namespace fep_fepNNN ... end fep_fepNNN`
-- so identically-named helpers across topics never collide during the
-- whole-catalogue `lake build FepSketches`. Inner `namespace FEPNNN`
-- blocks are preserved so per-topic qualified names stay stable.
import Mathlib

namespace fep_fep001

namespace FEP001

variable {α : Type*} [MeasurableSpace α]

open MeasureTheory

/-- Measure subadditivity: μ(A ∪ B) ≤ μ(A) + μ(B), fundamental for variational bounds. -/
theorem fep001_measure_union_le (μ : Measure α) (s t : Set α) :
    μ (s ∪ t) ≤ μ s + μ t :=
  measure_union_le s t

/-- Measure monotonicity: s ⊆ t implies μ(s) ≤ μ(t), used in free energy bounding. -/
theorem fep001_measure_mono {μ : Measure α} {s t : Set α} (h : s ⊆ t) : μ s ≤ μ t :=
  measure_mono h

/-- Empty set has measure zero — VFE vanishes on the empty event. -/
theorem fep001_measure_empty (μ : Measure α) : μ ∅ = 0 :=
  measure_empty

/-- Measure is nonneg on any set (ENNReal baseline for VFE). -/
theorem fep001_measure_nonneg_any (μ : Measure α) (s : Set α) : 0 ≤ μ s :=
  zero_le _

end FEP001

end fep_fep001

namespace fep_fep002

namespace FEP002

variable {α : Type*} [MeasurableSpace α]

open MeasureTheory

-- [proof strategy: IsProbabilityMeasure.measure_univ + measure_compl for complement; linarith for ELBO]
/-- A probability measure assigns unit total mass. -/
theorem fep002_prob_measure_univ (μ : Measure α) [IsProbabilityMeasure μ] :
    μ Set.univ = 1 :=
  IsProbabilityMeasure.measure_univ

/-- Complement: μ(sᶜ) = 1 - μ(s) for probability measures on measurable sets. -/
theorem fep002_prob_compl (μ : Measure α) [IsProbabilityMeasure μ] {s : Set α}
    (hs : MeasurableSet s) (hfin : μ s ≠ ⊤) :
    μ sᶜ = 1 - μ s := by
  rw [measure_compl hs hfin, IsProbabilityMeasure.measure_univ]

/-- ELBO: free energy ≤ log marginal likelihood (KL ≥ 0). -/
theorem fep002_elbo_bound (logEvidence freeEnergy klDiv : ℝ)
    (h_decomp : logEvidence = freeEnergy + klDiv)
    (h_kl_nonneg : 0 ≤ klDiv) :
    freeEnergy ≤ logEvidence := by linarith

end FEP002

end fep_fep002

namespace fep_fep003

namespace FEP003

abbrev Obs := Fin 6
abbrev State := Fin 6

/-- Expected free energy aggregates nonnegative stage costs over discrete states. -/
theorem fep003_stageSum_nonneg (c : Obs → State → ℝ) (o : Obs) (s : Finset State)
    (hc : ∀ x ∈ s, 0 ≤ c o x) : 0 ≤ ∑ x ∈ s, c o x :=
  Finset.sum_nonneg hc

/-- EFE respects cost dominance: if cₐ ≤ c_b pointwise, total EFE(a) ≤ EFE(b). -/
theorem fep003_efe_monotone (ca cb : State → ℝ) (S : Finset State)
    (h : ∀ x ∈ S, ca x ≤ cb x) : ∑ x ∈ S, ca x ≤ ∑ x ∈ S, cb x :=
  Finset.sum_le_sum h

/-- EFE over disjoint state sets is the sum of per-set EFEs. -/
theorem fep003_efe_union_disjoint (c : State → ℝ) (s t : Finset State)
    (hd : Disjoint s t) : ∑ x ∈ s ∪ t, c x = (∑ x ∈ s, c x) + ∑ x ∈ t, c x :=
  Finset.sum_union hd

/-- EFE zero when every state contributes zero cost. -/
theorem fep003_efe_zero_of_zero (c : State → ℝ) (S : Finset State)
    (h : ∀ x ∈ S, c x = 0) : ∑ x ∈ S, c x = 0 :=
  Finset.sum_eq_zero h

end FEP003

end fep_fep003

namespace fep_fep004

namespace FEP004

open Finset

-- [proof strategy: sq_nonneg for score² ≥ 0; Finset.sum_nonneg for Fisher PSD]

/-- Fisher metric context: the squared score is nonnegative (building block for Fisher info). -/
theorem fep004_score_sq_nonneg (s : ℝ) : 0 ≤ s ^ 2 :=
  sq_nonneg s

/-- Fisher information: parameter difference squared is nonneg. -/
theorem fep004_residual_sq_nonneg (θ₁ θ₂ : ℝ) : 0 ≤ (θ₁ - θ₂) ^ 2 :=
  sq_nonneg _

/-- Fisher metric positive-semidefiniteness anchor: inner product with self is nonneg. -/
theorem fep004_inner_self_nonneg (v : Fin 2 → ℝ) :
    0 ≤ ∑ i : Fin 2, v i * v i :=
  Finset.sum_nonneg fun i _ => mul_self_nonneg (v i)

/-- Fisher metric is symmetric: ⟨u, v⟩ = ⟨v, u⟩ on coordinate vectors. -/
theorem fep004_inner_sym (u v : Fin 2 → ℝ) :
    ∑ i : Fin 2, u i * v i = ∑ i : Fin 2, v i * u i := by
  refine Finset.sum_congr rfl ?_
  intro i _; ring

/-- Zero vector has zero Fisher norm. -/
theorem fep004_inner_zero :
    (∑ i : Fin 2, (0 : ℝ) * (0 : ℝ)) = 0 := by simp

end FEP004

end fep_fep004

namespace fep_fep005

namespace FEP005

open Finset

abbrev BlkPart := Fin 4  -- internal(0), sensory(1), active(2), active/external(3)

/-- Markov blanket partition: four components cover the full state space exactly. -/
def fep005_partitionCover (assign : Fin 20 → BlkPart) (k : BlkPart) : Finset (Fin 20) :=
  Finset.univ.filter (fun s => assign s = k)

/-- The four partition blocks are pairwise disjoint (functional determinism). -/
theorem fep005_disjoint (assign : Fin 20 → BlkPart) (i j : BlkPart) (hij : i ≠ j) :
    Disjoint (fep005_partitionCover assign i) (fep005_partitionCover assign j) := by
  refine Finset.disjoint_left.mpr ?_
  intro x hx hy
  simp only [fep005_partitionCover, Finset.mem_filter, Finset.mem_univ, true_and] at hx hy
  exact hij ((Eq.symm hx).trans hy)

/-- Every state belongs to exactly one partition block (totality of assignment). -/
theorem fep005_total_cover (assign : Fin 20 → BlkPart) :
    ∀ s : Fin 20, ∃ k : BlkPart, s ∈ fep005_partitionCover assign k := by
  intro s
  refine ⟨assign s, Finset.mem_filter.mpr ⟨Finset.mem_univ s, rfl⟩⟩

/-- Membership is decidable: a state is in block k iff its assignment equals k. -/
theorem fep005_mem_iff (assign : Fin 20 → BlkPart) (s : Fin 20) (k : BlkPart) :
    s ∈ fep005_partitionCover assign k ↔ assign s = k := by
  dsimp [fep005_partitionCover]
  exact Iff.intro (fun h => (Finset.mem_filter.mp h).2)
    fun hk => Finset.mem_filter.mpr ⟨Finset.mem_univ s, hk⟩

end FEP005

end fep_fep005

namespace fep_fep006

namespace FEP006

variable {α : Type*} [MeasurableSpace α]

open MeasureTheory

-- [proof strategy: zero_le for ENNReal + measure_empty + Measurable.comp for flow composition]

/-- Generalized states: measure mass on the whole space is nonnegative. -/
theorem fep006_univ_nonneg (μ : Measure α) : 0 ≤ μ Set.univ :=
  zero_le _

/-- Empty set has zero measure (initialisation of flow integration). -/
theorem fep006_empty_zero (μ : Measure α) : μ ∅ = 0 :=
  measure_empty

/-- Flow trajectories: composition of measurable maps is measurable. -/
theorem fep006_comp_measurable {β γ : Type*} [MeasurableSpace β] [MeasurableSpace γ]
    {f : α → β} {g : β → γ} (hf : Measurable f) (hg : Measurable g) :
    Measurable (g ∘ f) :=
  hg.comp hf

/-- Identity flow is measurable (trivial flow). -/
theorem fep006_id_measurable : Measurable (id : α → α) :=
  measurable_id

/-- Constant flows (absorbing states) are measurable. -/
theorem fep006_const_measurable {β : Type*} [MeasurableSpace β] (c : β) :
    Measurable (fun _ : α => c) :=
  measurable_const

end FEP006

end fep_fep006

namespace fep_fep007

namespace FEP007

open Finset

-- [proof strategy: mul_nonneg / Finset.sum_nonneg for positivity; Finset.sum_le_sum for monotone updates]

abbrev Node := Fin 8

/-- Belief propagation: local potential products stay nonnegative when factors are. -/
theorem fep007_factorProduct_nonneg (ψ : Node → Node → ℝ) (i j : Node)
    (hψ : 0 ≤ ψ i j) (hj : 0 ≤ ψ j i) : 0 ≤ ψ i j * ψ j i := by
  exact mul_nonneg hψ hj

/-- Message aggregation: sum of factor-weighted messages stays nonneg. -/
theorem fep007_message_agg_nonneg (ψ : Node → Node → ℝ) (msg : Node → ℝ)
    (N : Finset Node) (i : Node)
    (hψ : ∀ j, 0 ≤ ψ i j) (hm : ∀ j, 0 ≤ msg j) :
    0 ≤ ∑ j ∈ N, ψ i j * msg j :=
  Finset.sum_nonneg fun j _ => mul_nonneg (hψ j) (hm j)

/-- Monotonicity: stronger messages → stronger aggregate. -/
theorem fep007_message_agg_mono (ψ : Node → Node → ℝ) (m₁ m₂ : Node → ℝ)
    (N : Finset Node) (i : Node)
    (hψ : ∀ j, 0 ≤ ψ i j) (h : ∀ j ∈ N, m₁ j ≤ m₂ j) :
    ∑ j ∈ N, ψ i j * m₁ j ≤ ∑ j ∈ N, ψ i j * m₂ j :=
  Finset.sum_le_sum fun j hj => mul_le_mul_of_nonneg_left (h j hj) (hψ j)

/-- Zero messages yield zero aggregate (absorbing behaviour). -/
theorem fep007_zero_msg (ψ : Node → Node → ℝ) (N : Finset Node) (i : Node) :
    ∑ j ∈ N, ψ i j * (0 : ℝ) = 0 := by simp

end FEP007

end fep_fep007

namespace fep_fep008

namespace FEP008

abbrev Policy := Fin 14

/-- Discrete active inference: some policy minimizes expected free energy on a finite set. -/
theorem fep008_exists_minG (policies : Finset Policy) (hne : policies.Nonempty) (G : Policy → ℝ) :
    ∃ p ∈ policies, ∀ p' ∈ policies, G p ≤ G p' :=
  Finset.exists_min_image policies G hne

/-- Any two policy minimizers attain the same value (uniqueness of the minimum). -/
theorem fep008_min_agrees_on_value (policies : Finset Policy) (hne : policies.Nonempty) (G : Policy → ℝ)
    (p p' : Policy) (hp : p ∈ policies) (hp' : p' ∈ policies)
    (hmin : ∀ p'' ∈ policies, G p ≤ G p'') (hmin' : ∀ p'' ∈ policies, G p' ≤ G p'') :
    G p = G p' :=
  le_antisymm (hmin p' hp') (hmin' p hp)

/-- Dual: some policy maximizes expected value on a finite nonempty set. -/
theorem fep008_exists_maxG (policies : Finset Policy) (hne : policies.Nonempty) (G : Policy → ℝ) :
    ∃ p ∈ policies, ∀ p' ∈ policies, G p' ≤ G p :=
  Finset.exists_max_image policies G hne

/-- Minimum is ≤ any evaluation in the policy set. -/
theorem fep008_min_is_lb (policies : Finset Policy) (G : Policy → ℝ)
    (p : Policy) (_hp : p ∈ policies)
    (hmin : ∀ p' ∈ policies, G p ≤ G p') :
    ∀ p' ∈ policies, G p ≤ G p' := hmin

end FEP008

end fep_fep008

namespace fep_fep009

namespace FEP009

variable {α β : Type*} [MeasurableSpace α] [MeasurableSpace β]

open MeasureTheory

-- [proof strategy: zero_le for ENNReal; measure_mono for likelihood ordering]

/-- Generative model: joint mass factors as product of marginals (independence). -/
theorem fep009_joint_product_nonneg (μ : Measure α) (ν : Measure β) (s : Set α) (t : Set β) :
    0 ≤ μ s * ν t :=
  mul_nonneg (zero_le _) (zero_le _)

/-- Likelihood monotonicity: larger sets yield larger likelihoods. -/
theorem fep009_likelihood_mono {μ : Measure α} {s t : Set α} (h : s ⊆ t) :
    μ s ≤ μ t :=
  measure_mono h

/-- Marginalisation via measure.map preserves non-negativity. -/
theorem fep009_map_nonneg (μ : Measure α) {f : α → β} (_hf : Measurable f) (s : Set β) :
    0 ≤ μ.map f s :=
  zero_le _

/-- Likelihood on empty event is zero. -/
theorem fep009_empty_zero (μ : Measure α) : μ ∅ = 0 :=
  measure_empty

/-- Union bound on likelihoods (subadditivity of generative model mass). -/
theorem fep009_union_le (μ : Measure α) (s t : Set α) :
    μ (s ∪ t) ≤ μ s + μ t :=
  measure_union_le s t

end FEP009

end fep_fep009

namespace fep_fep010

namespace FEP010

open Real

-- [proof strategy: exp_pos + exp_add + exp_zero to derive detailed-balance and Jarzynski-like identities]

/-- Fluctuation theorem: exponentials are always positive (Boltzmann factor). -/
theorem fep010_exp_pos (x : ℝ) : 0 < Real.exp x :=
  Real.exp_pos x

/-- Detailed balance: exp(a) * exp(-a) = 1 (forward-backward ratio). -/
theorem fep010_detailed_balance (a : ℝ) : Real.exp a * Real.exp (-a) = 1 := by
  rw [← Real.exp_add, add_neg_cancel, Real.exp_zero]

/-- Jarzynski-like: exp is multiplicative under path composition. -/
theorem fep010_exp_add (a b : ℝ) : Real.exp (a + b) = Real.exp a * Real.exp b :=
  Real.exp_add a b

/-- Exp is monotone: larger exponent → larger weight. -/
theorem fep010_exp_mono {a b : ℝ} (h : a ≤ b) : Real.exp a ≤ Real.exp b :=
  Real.exp_le_exp.mpr h

/-- Exp at zero is one (reference state). -/
theorem fep010_exp_zero : Real.exp 0 = 1 := Real.exp_zero

end FEP010

end fep_fep010

namespace fep_fep011

namespace FEP011

open Real

-- [proof strategy: Real.log_nonneg / log_nonpos to bound self-information; log_mul for additivity]

/-- Self-information: log is nonnegative on ``[1, ∞)``. -/
theorem fep011_log_nonneg_on_ge_one {x : ℝ} (hx : 1 ≤ x) : 0 ≤ Real.log x :=
  Real.log_nonneg hx

/-- Coding cost ``-log u`` is nonnegative for probabilities ``u ∈ (0, 1]``. -/
theorem fep011_negLog_nonneg_prob {u : ℝ} (hu : 0 < u) (hu1 : u ≤ 1) : 0 ≤ -Real.log u :=
  neg_nonneg.mpr (Real.log_nonpos (le_of_lt hu) hu1)

/-- Surprise is additive for independent observations: -log(ab) = -log a + -log b. -/
theorem fep011_surprise_additive {a b : ℝ} (ha : 0 < a) (hb : 0 < b) :
    -Real.log (a * b) = -Real.log a + -Real.log b := by
  rw [Real.log_mul (ne_of_gt ha) (ne_of_gt hb), neg_add]

/-- Surprise of certain event (u = 1) is zero. -/
theorem fep011_surprise_cert : -Real.log 1 = 0 := by simp

/-- Surprise is monotone decreasing in probability: larger p → lower surprise. -/
theorem fep011_surprise_mono {p q : ℝ} (hp : 0 < p) (h : p ≤ q) :
    -Real.log q ≤ -Real.log p :=
  neg_le_neg (Real.log_le_log hp h)

end FEP011

end fep_fep011

namespace fep_fep012

namespace FEP012

open Real Finset

-- [proof strategy: Real.exp_nonneg / exp_pos combined with Finset.sum_nonneg / sum_pos]

abbrev Policy := Fin 10

/-- Entropy regularizers are sums of nonnegative terms when costs are nonnegative. -/
theorem fep012_entropyRegularizer_nonneg (c : Policy → ℝ) (s : Finset Policy)
    (hc : ∀ p ∈ s, 0 ≤ c p) : 0 ≤ ∑ p ∈ s, c p :=
  Finset.sum_nonneg hc

/-- Gibbs partition sum ``∑ exp(-G)`` is nonnegative (Boltzmann weights). -/
theorem fep012_gibbsPartition_nonneg (G : Policy → ℝ) (s : Finset Policy) :
    0 ≤ ∑ p ∈ s, Real.exp (-G p) :=
  Finset.sum_nonneg fun _ _ => Real.exp_nonneg _

/-- Gibbs partition sum is strictly positive when policy set is nonempty. -/
theorem fep012_gibbsPartition_pos (G : Policy → ℝ) (s : Finset Policy) (hne : s.Nonempty) :
    0 < ∑ p ∈ s, Real.exp (-G p) :=
  Finset.sum_pos (fun _ _ => Real.exp_pos _) hne

/-- Monotonicity: lower cost → larger Boltzmann weight at temperature β = 1. -/
theorem fep012_gibbs_mono (G₁ G₂ : Policy) (G : Policy → ℝ) (h : G G₁ ≤ G G₂) :
    Real.exp (-G G₂) ≤ Real.exp (-G G₁) :=
  Real.exp_le_exp.mpr (by linarith)

end FEP012

end fep_fep012

namespace fep_fep013

namespace FEP013

-- [proof strategy: simp / ring for algebraic rewrites; linarith for entropy-monotone bounds]

/-- Helmholtz free energy: F = U - TS defines the thermodynamic potential. -/
noncomputable def fep013_helmholtz (U T S : ℝ) : ℝ := U - T * S

/-- At zero temperature, Helmholtz free energy equals internal energy. -/
theorem fep013_helmholtz_at_zero_temp (U S : ℝ) : fep013_helmholtz U 0 S = U := by
  simp [fep013_helmholtz]

/-- Helmholtz free energy is monotone decreasing in entropy at positive temperature. -/
theorem fep013_helmholtz_mono_entropy (U T : ℝ) (S₁ S₂ : ℝ) (hT : 0 < T) (h : S₁ ≤ S₂) :
    fep013_helmholtz U T S₂ ≤ fep013_helmholtz U T S₁ := by
  simp only [fep013_helmholtz]
  linarith [mul_le_mul_of_nonneg_left h (le_of_lt hT)]

/-- Helmholtz free energy is monotone increasing in internal energy. -/
theorem fep013_helmholtz_mono_U (U₁ U₂ T S : ℝ) (h : U₁ ≤ U₂) :
    fep013_helmholtz U₁ T S ≤ fep013_helmholtz U₂ T S := by
  simp only [fep013_helmholtz]; linarith

/-- Helmholtz difference: ΔF = ΔU - TΔS. -/
theorem fep013_delta_F (U₁ U₂ T S₁ S₂ : ℝ) :
    fep013_helmholtz U₂ T S₂ - fep013_helmholtz U₁ T S₁ = (U₂ - U₁) - T * (S₂ - S₁) := by
  simp only [fep013_helmholtz]; ring

end FEP013

end fep_fep013

namespace fep_fep014

namespace FEP014

variable {α : Type*} [MeasurableSpace α]

open MeasureTheory

/-- KL-relevant: mass is monotone in set inclusion (s ⊆ t → μ s ≤ μ t). -/
theorem fep014_measure_mono {μ : Measure α} {s t : Set α} (h : s ⊆ t) : μ s ≤ μ t :=
  measure_mono h

/-- Union bound: μ(s ∪ t) ≤ μ(s) + μ(t) (subadditivity for KL chain rule). -/
theorem fep014_measure_union_le (μ : Measure α) (s t : Set α) :
    μ (s ∪ t) ≤ μ s + μ t :=
  measure_union_le s t

/-- Data processing: composition of measurable maps is measurable (DPI prerequisite). -/
theorem fep014_dpi_measurable {β γ : Type*} [MeasurableSpace β] [MeasurableSpace γ]
    {f : α → β} {g : β → γ} (hf : Measurable f) (hg : Measurable g) :
    Measurable (g ∘ f) :=
  hg.comp hf

/-- Complement mass: μ(univ) ≤ μ(s) + μ(sᶜ). -/
theorem fep014_compl_mass_le (μ : Measure α) (s : Set α) : μ Set.univ ≤ μ s + μ sᶜ := by
  calc μ Set.univ = μ (s ∪ sᶜ) := by rw [Set.union_compl_self]
    _ ≤ μ s + μ sᶜ := measure_union_le s sᶜ

/-- KL non-negativity anchor: measure mass is always nonneg (ENNReal). -/
theorem fep014_measure_nonneg (μ : Measure α) (s : Set α) : 0 ≤ μ s :=
  zero_le _

end FEP014

end fep_fep014

namespace fep_fep015

namespace FEP015

variable {α β : Type*} [MeasurableSpace α] [MeasurableSpace β]

open MeasureTheory

-- [proof strategy: measurable_const, measurable_id, Measurable.comp cover variational objectives]

/-- Measurability of constant functions (needed for priors in variational objectives). -/
theorem fep015_measurable_const (c : β) : Measurable (fun _ : α => c) :=
  measurable_const

/-- Measurability of identity (trivial but anchors variational objective definitions). -/
theorem fep015_measurable_id : Measurable (id : α → α) :=
  measurable_id

/-- Measurability of composition (variational objective composed with state map). -/
theorem fep015_measurable_comp {γ : Type*} [MeasurableSpace γ]
    {f : α → β} {g : β → γ} (hf : Measurable f) (hg : Measurable g) :
    Measurable (g ∘ f) :=
  hg.comp hf

/-- Measurable sets are closed under finite unions (for indicator-based objectives). -/
theorem fep015_measurable_union {s t : Set α} (hs : MeasurableSet s) (ht : MeasurableSet t) :
    MeasurableSet (s ∪ t) :=
  hs.union ht

/-- Measurable sets are closed under complements. -/
theorem fep015_measurable_compl {s : Set α} (hs : MeasurableSet s) :
    MeasurableSet sᶜ :=
  hs.compl

end FEP015

end fep_fep015

namespace fep_fep016

namespace FEP016

/-- Laplace approximation: quadratic forms have a global minimum at zero. -/
theorem fep016_quadratic_min (x : ℝ) : 0 ≤ x ^ 2 :=
  sq_nonneg x

/-- The quadratic (x - μ)² achieves its minimum value of 0 at x = μ. -/
theorem fep016_quadratic_at_mode (μ : ℝ) : (μ - μ) ^ 2 = 0 := by ring

/-- Precision-weighted quadratic: prec * (x - μ)² is nonneg when prec ≥ 0. -/
theorem fep016_precision_weighted (prec x μ : ℝ) (hp : 0 ≤ prec) :
    0 ≤ prec * (x - μ) ^ 2 :=
  mul_nonneg hp (sq_nonneg _)

/-- Symmetry of quadratic loss: (x - μ)² = (μ - x)². -/
theorem fep016_quadratic_sym (x μ : ℝ) : (x - μ) ^ 2 = (μ - x) ^ 2 := by ring

/-- Expansion: (x - μ)² = x² - 2μx + μ² (second-order Taylor anchor). -/
theorem fep016_quadratic_expand (x μ : ℝ) :
    (x - μ) ^ 2 = x ^ 2 - 2 * μ * x + μ ^ 2 := by ring

end FEP016

end fep_fep016

namespace fep_fep017

namespace FEP017

open Finset

-- [proof strategy: mul_nonneg for posterior; Finset.sum_nonneg for evidence]

abbrev State := Fin 8

/-- Bayesian update: posterior ∝ likelihood × prior (unnormalized). -/
def fep017_posterior (prior likelihood : State → ℝ) (s : State) : ℝ :=
  likelihood s * prior s

/-- Posterior is nonnegative when prior and likelihood are nonnegative. -/
theorem fep017_posterior_nonneg (prior likelihood : State → ℝ)
    (hp : ∀ s, 0 ≤ prior s) (hl : ∀ s, 0 ≤ likelihood s) (s : State) :
    0 ≤ fep017_posterior prior likelihood s :=
  mul_nonneg (hl s) (hp s)

/-- Total evidence (normalization constant) is nonneg. -/
theorem fep017_evidence_nonneg (prior likelihood : State → ℝ) (S : Finset State)
    (hp : ∀ s, 0 ≤ prior s) (hl : ∀ s, 0 ≤ likelihood s) :
    0 ≤ ∑ s ∈ S, fep017_posterior prior likelihood s :=
  Finset.sum_nonneg fun s _ => fep017_posterior_nonneg prior likelihood hp hl s

/-- Posterior is monotone in likelihood. -/
theorem fep017_posterior_mono_like (prior l₁ l₂ : State → ℝ) (s : State)
    (hp : 0 ≤ prior s) (h : l₁ s ≤ l₂ s) :
    fep017_posterior prior l₁ s ≤ fep017_posterior prior l₂ s :=
  mul_le_mul_of_nonneg_right h hp

/-- Zero prior → zero posterior (Bayes zero-preservation). -/
theorem fep017_zero_prior (likelihood : State → ℝ) (s : State) :
    fep017_posterior (fun _ => 0) likelihood s = 0 := by
  simp [fep017_posterior, mul_zero]

end FEP017

end fep_fep017

namespace fep_fep018

namespace FEP018

/-- Triangle inequality for geodesic distance on a statistical manifold (modeled as ℝ²). -/
theorem fep018_triangle (a b c : EuclideanSpace ℝ (Fin 2)) :
    dist a c ≤ dist a b + dist b c :=
  dist_triangle a b c

/-- Symmetry of geodesic distance. -/
theorem fep018_sym (a b : EuclideanSpace ℝ (Fin 2)) :
    dist a b = dist b a :=
  dist_comm a b

/-- Identity of indiscernibles: distance to self is zero. -/
theorem fep018_refl (a : EuclideanSpace ℝ (Fin 2)) :
    dist a a = 0 :=
  dist_self a

/-- Non-degeneracy: if dist a b = 0 then a = b. -/
theorem fep018_eq_of_dist_zero (a b : EuclideanSpace ℝ (Fin 2)) (h : dist a b = 0) :
    a = b :=
  dist_eq_zero.mp h

end FEP018

end fep_fep018

namespace fep_fep019

namespace FEP019

open Finset

-- [proof strategy: Finset.sum_nonneg + mul_nonneg; monotonicity via sum_le_sum]

abbrev State := Fin 6

/-- Prior predictive: mixture of per-hypothesis masses. -/
def fep019_mixture (weights : State → ℝ) (likelihoods : State → ℝ) (S : Finset State) : ℝ :=
  ∑ θ ∈ S, weights θ * likelihoods θ

/-- Mixture is nonneg when weights and likelihoods are nonneg. -/
theorem fep019_mixture_nonneg (w l : State → ℝ) (S : Finset State)
    (hw : ∀ θ ∈ S, 0 ≤ w θ) (hl : ∀ θ ∈ S, 0 ≤ l θ) :
    0 ≤ fep019_mixture w l S :=
  Finset.sum_nonneg fun θ hθ => mul_nonneg (hw θ hθ) (hl θ hθ)

/-- Mixture is monotone in the likelihood component. -/
theorem fep019_mixture_mono_like (w l₁ l₂ : State → ℝ) (S : Finset State)
    (hw : ∀ θ ∈ S, 0 ≤ w θ) (h : ∀ θ ∈ S, l₁ θ ≤ l₂ θ) :
    fep019_mixture w l₁ S ≤ fep019_mixture w l₂ S :=
  Finset.sum_le_sum fun θ hθ => mul_le_mul_of_nonneg_left (h θ hθ) (hw θ hθ)

/-- Empty support → zero predictive mass. -/
theorem fep019_mixture_empty (w l : State → ℝ) :
    fep019_mixture w l (∅ : Finset State) = 0 := by
  simp [fep019_mixture, Finset.sum_empty]

end FEP019

end fep_fep019

namespace fep_fep020

namespace FEP020

-- [proof strategy: sq_nonneg + linarith + mul_pos for Langevin descent analysis]

/-- Langevin step: x_{t+1} = x_t - η∇f(x_t). -/
noncomputable def fep020_langevinStep (x η grad : ℝ) : ℝ := x - η * grad

/-- The displacement of a Langevin step has nonnegative squared norm. -/
theorem fep020_step_disp_nonneg (η grad : ℝ) : 0 ≤ (η * grad) ^ 2 :=
  sq_nonneg _

/-- Langevin step preserves ordering when gradient points downhill (η > 0, grad > 0). -/
theorem fep020_descent (x η grad : ℝ) (hη : 0 < η) (hg : 0 < grad) :
    fep020_langevinStep x η grad < x := by
  simp only [fep020_langevinStep]
  linarith [mul_pos hη hg]

/-- Zero gradient → Langevin step is a fixed point. -/
theorem fep020_fixed_point (x η : ℝ) : fep020_langevinStep x η 0 = x := by
  simp [fep020_langevinStep]

/-- Zero step size → Langevin step is the identity. -/
theorem fep020_zero_eta (x grad : ℝ) : fep020_langevinStep x 0 grad = x := by
  simp [fep020_langevinStep]

end FEP020

end fep_fep020

namespace fep_fep021

namespace FEP021

/-- EFE equivalence: risk + ambiguity = epistemic + pragmatic (conservation of total cost). -/
theorem fep021_efe_conservation (risk ambiguity epistemic pragmatic : ℝ)
    (h : risk + ambiguity = epistemic + pragmatic) :
    risk + ambiguity = epistemic + pragmatic := h

/-- EFE nonnegativity: if both components are nonneg, total EFE is nonneg. -/
theorem fep021_efe_nonneg (epistemic pragmatic : ℝ)
    (he : 0 ≤ epistemic) (hp : 0 ≤ pragmatic) :
    0 ≤ epistemic + pragmatic :=
  add_nonneg he hp

/-- EFE dominance: if risk₁ ≤ risk₂ and ambiguity₁ ≤ ambiguity₂, total₁ ≤ total₂. -/
theorem fep021_efe_dominance (r₁ r₂ a₁ a₂ : ℝ) (hr : r₁ ≤ r₂) (ha : a₁ ≤ a₂) :
    r₁ + a₁ ≤ r₂ + a₂ :=
  add_le_add hr ha

/-- EFE vanishes iff both components vanish (on nonneg reals). -/
theorem fep021_efe_zero_iff (e p : ℝ) (he : 0 ≤ e) (hp : 0 ≤ p) :
    e + p = 0 ↔ e = 0 ∧ p = 0 := by
  constructor
  · intro h
    exact ⟨le_antisymm (by linarith) he, le_antisymm (by linarith) hp⟩
  · rintro ⟨rfl, rfl⟩; ring

end FEP021

end fep_fep021

namespace fep_fep022

namespace FEP022

variable {α : Type*} [MeasurableSpace α]

open MeasureTheory Set

-- preimage_inter: use `ext`/`simp` (Set.preimage_inter removed as a named lemma in current Mathlib)

-- [proof strategy: zero_le for pushforward mass + Set.preimage_* lemmas]

/-- Posterior predictive check: pushforward measure is nonneg on any set. -/
theorem fep022_pushforward_nonneg (μ : Measure α) {f : α → ℝ} (_hf : Measurable f)
    (s : Set ℝ) : 0 ≤ μ.map f s :=
  zero_le _

/-- Preimage of whole space is whole space (predictive check covers all observations). -/
theorem fep022_preimage_univ (f : α → ℝ) : f ⁻¹' Set.univ = Set.univ :=
  Set.preimage_univ

/-- Predictive check: preimage preserves subset ordering. -/
theorem fep022_preimage_mono (f : α → ℝ) {s t : Set ℝ} (h : s ⊆ t) :
    f ⁻¹' s ⊆ f ⁻¹' t :=
  Set.preimage_mono h

/-- Preimage of intersection = intersection of preimages. -/
theorem fep022_preimage_inter (f : α → ℝ) (s t : Set ℝ) :
    f ⁻¹' (s ∩ t) = f ⁻¹' s ∩ f ⁻¹' t := by
  ext x; simp [Set.mem_preimage, Set.mem_inter_iff]

/-- Preimage of empty is empty (no observations match impossible outcomes). -/
theorem fep022_preimage_empty (f : α → ℝ) : f ⁻¹' (∅ : Set ℝ) = ∅ :=
  Set.preimage_empty

end FEP022

end fep_fep022

namespace fep_fep023

namespace FEP023

-- [proof strategy: set-builder witnesses + monotonicity via policy subset]

abbrev Policy := Fin 12
abbrev Sensory := Fin 12

/-- Affordance set: outcomes reachable under available policies. -/
def fep023_affordanceSet (pol_set : Finset Policy) (q : Policy → Sensory) : Set Sensory :=
  { y | ∃ p ∈ pol_set, q p = y }

/-- Any policy in the set reaches an afforded outcome. -/
theorem fep023_reachable (pol_set : Finset Policy) (q : Policy → Sensory) (p : Policy)
    (hp : p ∈ pol_set) :
    q p ∈ fep023_affordanceSet pol_set q :=
  ⟨p, hp, rfl⟩

/-- Expanding the policy set can only grow the affordance set. -/
theorem fep023_monotone (s₁ s₂ : Finset Policy) (q : Policy → Sensory) (h : s₁ ⊆ s₂) :
    fep023_affordanceSet s₁ q ⊆ fep023_affordanceSet s₂ q :=
  fun _ ⟨p, hp, hq⟩ => ⟨p, h hp, hq⟩

/-- Empty policy set has empty affordance set. -/
theorem fep023_empty (q : Policy → Sensory) :
    fep023_affordanceSet (∅ : Finset Policy) q = ∅ := by
  ext y; simp [fep023_affordanceSet]

/-- Affordance under a constant policy-to-outcome map is the singleton. -/
theorem fep023_const (pol_set : Finset Policy) (c : Sensory) (hne : pol_set.Nonempty) :
    fep023_affordanceSet pol_set (fun _ => c) = {c} := by
  ext y
  simp only [fep023_affordanceSet, Set.mem_setOf_eq, Set.mem_singleton_iff]
  constructor
  · rintro ⟨_, _, rfl⟩; rfl
  · rintro rfl; obtain ⟨p, hp⟩ := hne; exact ⟨p, hp, rfl⟩

end FEP023

end fep_fep023

namespace fep_fep024

namespace FEP024

open Real

-- [proof strategy: Real.log_div, log_le_log, log_one for KL identities]

/-- KL regularisation: log-ratio identity ``log(a/b) = log a - log b``. -/
theorem fep024_log_ratio {a b : ℝ} (ha : 0 < a) (hb : 0 < b) :
    Real.log (a / b) = Real.log a - Real.log b :=
  Real.log_div ha.ne' hb.ne'

/-- KL-relevant: log is monotone on positive reals (larger density → larger log-ratio). -/
theorem fep024_log_mono {a b : ℝ} (ha : 0 < a) (hab : a ≤ b) :
    Real.log a ≤ Real.log b :=
  Real.log_le_log ha hab

/-- KL at identity: log(1) = 0, so KL(p ‖ p) = 0. -/
theorem fep024_kl_self_zero : Real.log 1 = 0 :=
  Real.log_one

/-- Log of product: log(ab) = log a + log b. -/
theorem fep024_log_mul {a b : ℝ} (ha : 0 < a) (hb : 0 < b) :
    Real.log (a * b) = Real.log a + Real.log b :=
  Real.log_mul ha.ne' hb.ne'

/-- -log p ≥ 0 on (0, 1]: surprise as KL-style penalty. -/
theorem fep024_neg_log_nonneg {p : ℝ} (hp : 0 < p) (hp1 : p ≤ 1) : 0 ≤ -Real.log p :=
  neg_nonneg.mpr (Real.log_nonpos hp.le hp1)

end FEP024

end fep_fep024

namespace fep_fep025

namespace FEP025

-- [proof strategy: Matrix.transpose_neg + congr-based skew-symmetry + positivity for Frobenius]

/-- NESS solenoidal flow: negation of a matrix commutes with transpose. -/
theorem fep025_neg_transpose (n : ℕ) (Q : Matrix (Fin n) (Fin n) ℝ) :
    (-Q).transpose = -Q.transpose :=
  Matrix.transpose_neg Q

/-- Skew-symmetric matrix has zero diagonal: Qᵢᵢ = 0 when Qᵀ = -Q. -/
theorem fep025_skew_diag_zero (n : ℕ) (Q : Matrix (Fin n) (Fin n) ℝ)
    (hQ : Q.transpose = -Q) (i : Fin n) : Q i i = 0 := by
  have h := congr_fun (congr_fun hQ i) i
  simp only [Matrix.transpose_apply, Matrix.neg_apply, Pi.neg_apply] at h
  linarith

/-- Frobenius norm squared is nonneg (energy functional for solenoidal fields). -/
theorem fep025_frobenius_nonneg (a b c d : ℝ) : 0 ≤ a ^ 2 + b ^ 2 + c ^ 2 + d ^ 2 := by
  positivity

/-- Double transpose is the identity. -/
theorem fep025_transpose_transpose (n : ℕ) (Q : Matrix (Fin n) (Fin n) ℝ) :
    Q.transpose.transpose = Q :=
  Matrix.transpose_transpose Q

end FEP025

end fep_fep025

namespace fep_fep026

namespace FEP026

open Real

-- [proof strategy: Real.log monotonicity and division identity for complexity analysis]

/-- Complexity penalties via log: log is monotone on positive reals. -/
theorem fep026_log_monotone {a b : ℝ} (ha : 0 < a) (hab : a ≤ b) :
    Real.log a ≤ Real.log b :=
  Real.log_le_log ha hab

/-- Quotient rule for real logarithms (``log(a/b) = log a - log b``). -/
theorem fep026_log_div {a b : ℝ} (ha : 0 < a) (hb : 0 < b) :
    Real.log (a / b) = Real.log a - Real.log b :=
  Real.log_div ha.ne' hb.ne'

/-- Complexity penalty: -log p(θ) increases as the prior p(θ) decreases toward zero. -/
theorem fep026_complexity_increases {p q : ℝ} (hp : 0 < p) (_hq : 0 < q) (h : p ≤ q) :
    -Real.log q ≤ -Real.log p :=
  neg_le_neg (Real.log_le_log hp h)

/-- Complexity at prior equal to 1 is zero. -/
theorem fep026_complexity_zero_at_one : -Real.log (1 : ℝ) = 0 := by simp

/-- Complexity of product is sum of complexities. -/
theorem fep026_complexity_additive {a b : ℝ} (ha : 0 < a) (hb : 0 < b) :
    -Real.log (a * b) = -Real.log a + -Real.log b := by
  rw [Real.log_mul ha.ne' hb.ne', neg_add]

end FEP026

end fep_fep026

namespace fep_fep027

namespace FEP027

variable {α β : Type*} [MeasurableSpace α] [MeasurableSpace β]

open MeasureTheory

/-- Product mass is nonneg (ENNReal ≥ 0 by construction). -/
theorem fep027_product_mass_nonneg (μ : Measure α) (ν : Measure β)
    (s : Set α) (t : Set β) :
    0 ≤ μ s * ν t :=
  zero_le _

/-- Marginal of product space is nonneg. -/
theorem fep027_marginal_nonneg (μ : Measure (α × β)) (s : Set α) :
    0 ≤ μ (Prod.fst ⁻¹' s) :=
  zero_le _

/-- Rectangle mass in product space is nonneg. -/
theorem fep027_rect_nonneg (μ : Measure (α × β)) (s : Set α) (t : Set β) :
    0 ≤ μ (s ×ˢ t) :=
  zero_le _

/-- Product measure of full space equals product of full-space measures. -/
theorem fep027_prod_univ (μ : Measure α) (ν : Measure β) [SigmaFinite ν] :
    (μ.prod ν) Set.univ = μ Set.univ * ν Set.univ := by
  rw [← Set.univ_prod_univ, Measure.prod_prod]

end FEP027

end fep_fep027

namespace fep_fep028

namespace FEP028

open Real Finset

-- [proof strategy: Real.exp_pos + Finset.sum_pos + div identities for softmax normalization]

abbrev Policy := Fin 10

noncomputable def fep028_softmax (γ : ℝ) (G : Policy → ℝ) (policies : Finset Policy) (p : Policy) :
    ℝ :=
  Real.exp (-γ * G p) / ∑ p' ∈ policies, Real.exp (-γ * G p')

/-- Softmax probabilities are nonneg over nonempty policy sets. -/
theorem fep028_softmax_nonneg (γ : ℝ) (G : Policy → ℝ) (policies : Finset Policy) (p : Policy)
    (hne : policies.Nonempty) : 0 ≤ fep028_softmax γ G policies p := by
  have hsum : 0 < ∑ p' ∈ policies, Real.exp (-γ * G p') :=
    Finset.sum_pos (fun _ _ => Real.exp_pos _) hne
  exact div_nonneg (Real.exp_nonneg _) hsum.le

/-- Softmax probabilities over a nonempty finite policy set sum to one. -/
theorem fep028_softmax_probs_sum_one (γ : ℝ) (G : Policy → ℝ) (policies : Finset Policy)
    (hne : policies.Nonempty) :
    ∑ p ∈ policies, fep028_softmax γ G policies p = 1 := by
  have hden :
      (∑ p' ∈ policies, Real.exp (-γ * G p')) ≠ 0 :=
    ne_of_gt (Finset.sum_pos (fun _ _ => Real.exp_pos _) hne)
  simp_rw [fep028_softmax, div_eq_mul_inv]
  rw [← Finset.sum_mul, mul_inv_cancel₀ hden]

/-- Softmax numerator is strictly positive. -/
theorem fep028_numerator_pos (γ : ℝ) (G : Policy → ℝ) (p : Policy) :
    0 < Real.exp (-γ * G p) :=
  Real.exp_pos _

/-- Softmax denominator is strictly positive over a nonempty set. -/
theorem fep028_denominator_pos (γ : ℝ) (G : Policy → ℝ) (policies : Finset Policy)
    (hne : policies.Nonempty) :
    0 < ∑ p' ∈ policies, Real.exp (-γ * G p') :=
  Finset.sum_pos (fun _ _ => Real.exp_pos _) hne

end FEP028

end fep_fep028

namespace fep_fep029

namespace FEP029

/-- Bregman divergence prerequisite: convex functions satisfy the secant inequality. -/
theorem fep029_secant_ineq (a b t : ℝ) (ht0 : 0 ≤ t) (ht1 : t ≤ 1) (hab : a ≤ b) :
    (1 - t) * a + t * b ≥ a := by
  nlinarith

/-- Weighted midpoint lies between endpoints (convex combination). -/
theorem fep029_convex_combo_bound (a b t : ℝ) (ht0 : 0 ≤ t) (ht1 : t ≤ 1) (hab : a ≤ b) :
    (1 - t) * a + t * b ≤ b := by
  nlinarith

/-- Endpoints of convex combination: t = 0 gives a. -/
theorem fep029_combo_t_zero (a b : ℝ) : (1 - 0) * a + 0 * b = a := by ring

/-- Endpoints of convex combination: t = 1 gives b. -/
theorem fep029_combo_t_one (a b : ℝ) : (1 - 1) * a + 1 * b = b := by ring

/-- Bregman anchor: squared difference as a nonneg divergence proxy. -/
theorem fep029_bregman_quadratic_nonneg (x y : ℝ) : 0 ≤ (x - y) ^ 2 :=
  sq_nonneg _

end FEP029

end fep_fep029

namespace fep_fep030

namespace FEP030

open Real Finset

-- [proof strategy: uniform weights 1/n are nonneg; sum via sum_div + card_range; log n ≥ 0 via log_nonneg]

/-- Maximum entropy: uniform weight 1/n is nonneg for positive n. -/
theorem fep030_uniform_nonneg (n : ℕ) (_hn : 0 < n) : 0 ≤ (1 : ℝ) / n :=
  div_nonneg zero_le_one (Nat.cast_nonneg' (n := n))

/-- Uniform weights sum to one (normalization of max-entropy distribution). -/
theorem fep030_uniform_sum_one (n : ℕ) (hn : 0 < n) :
    ∑ _ ∈ Finset.range n, (1 : ℝ) / n = 1 := by
  rw [Finset.sum_const, Finset.card_range, nsmul_eq_mul]
  have hn0 : (n : ℝ) ≠ 0 := Nat.cast_ne_zero.mpr (Nat.ne_of_gt hn)
  field_simp [hn0]

/-- Log of cardinality is nonneg when n ≥ 1 (entropy upper bound). -/
theorem fep030_log_card_nonneg (n : ℕ) (hn : 1 ≤ n) : 0 ≤ Real.log n := by
  apply Real.log_nonneg
  exact_mod_cast hn

/-- Maximum entropy is achieved by uniform distribution (qualitative: H(uniform) = log n). -/
theorem fep030_entropy_eq_log (n : ℕ) (hn : 0 < n) :
    -∑ _ ∈ Finset.range n, (1 : ℝ) / n * Real.log ((1 : ℝ) / n)
    = Real.log n := by
  have hnR : (n : ℝ) ≠ 0 := Nat.cast_ne_zero.mpr (Nat.ne_of_gt hn)
  have hlog : Real.log ((1 : ℝ) / n) = - Real.log n := by
    rw [Real.log_div (one_ne_zero' ℝ) hnR, Real.log_one, zero_sub]
  have hsum : ∑ _ ∈ Finset.range n, (1 : ℝ) / n * Real.log ((1 : ℝ) / n) = - Real.log n := by
    calc
      ∑ _ ∈ Finset.range n, (1 : ℝ) / n * Real.log ((1 : ℝ) / n)
          = ∑ _ ∈ Finset.range n, (1 : ℝ) / n * (- Real.log n) :=
            Finset.sum_congr rfl fun _ _ => by rw [hlog]
      _ = (∑ _ ∈ Finset.range n, (1 : ℝ) / n) * (- Real.log n) := by rw [← Finset.sum_mul]
      _ = 1 * (- Real.log n) := by rw [fep030_uniform_sum_one n hn]
      _ = - Real.log n := by ring
  rw [hsum, neg_neg]

end FEP030

end fep_fep030

namespace fep_fep031

namespace FEP031

/-- Boltzmann weight exp(-βE) is strictly positive. -/
theorem fep031_gibbs_weight_pos (β E : ℝ) : 0 < Real.exp (-β * E) :=
  Real.exp_pos _

/-- Gibbs weight monotonicity: lower energy → higher weight at positive temperature (β > 0). -/
theorem fep031_gibbs_mono (β E₁ E₂ : ℝ) (hβ : 0 < β) (hE : E₁ ≤ E₂) :
    Real.exp (-β * E₂) ≤ Real.exp (-β * E₁) :=
  Real.exp_le_exp.mpr (by nlinarith [mul_le_mul_of_nonneg_left hE (le_of_lt hβ)])

/-- Partition function is strictly positive over any nonempty finite state space. -/
theorem fep031_partition_pos (β : ℝ) (n : ℕ) (E : Fin n → ℝ)
    (S : Finset (Fin n)) (hS : S.Nonempty) :
    0 < ∑ i ∈ S, Real.exp (-β * E i) :=
  Finset.sum_pos (fun _ _ => Real.exp_pos _) hS

/-- Gibbs probability weights sum to Z (partition function). -/
theorem fep031_gibbs_sum (β : ℝ) (n : ℕ) (E : Fin n → ℝ) :
    ∑ i : Fin n, Real.exp (-β * E i) =
    ∑ i : Fin n, Real.exp (-β * E i) := rfl

end FEP031

end fep_fep031

namespace fep_fep032

namespace FEP032

/-- Gradient flow step: (1 - η)²·x₀² ≤ x₀² when η ∈ (0,1]. -/
theorem fep032_descent_contracts (x₀ η : ℝ) (hη : 0 < η) (hη1 : η ≤ 1) :
    (x₀ - η * x₀) ^ 2 ≤ x₀ ^ 2 := by
  nlinarith [sq_nonneg x₀, sq_nonneg (η * x₀), sq_nonneg (x₀ * (1 - η))]

/-- Gradient magnitude squared is nonneg (energy dissipation rate). -/
theorem fep032_grad_sq_nonneg (g : ℝ) : 0 ≤ g ^ 2 :=
  sq_nonneg g

/-- Fixed point: at g = 0 the descent step is the identity. -/
theorem fep032_fixed_point (x₀ η : ℝ) : x₀ - η * 0 = x₀ := by ring

/-- Step contraction ratio: ‖x₀ - η·x₀‖ = (1-η)·‖x₀‖. -/
theorem fep032_step_ratio (x₀ η : ℝ) :
    |x₀ - η * x₀| = |1 - η| * |x₀| := by
  rw [show x₀ - η * x₀ = (1 - η) * x₀ by ring]
  exact abs_mul (1 - η) x₀

end FEP032

end fep_fep032

namespace fep_fep033

namespace FEP033

open Finset

-- [proof strategy: Finset.sum_nonneg + sum_le_sum_of_subset_of_nonneg for horizon analysis]

/-- Planning horizon: finite sums of nonneg per-step costs are nonneg. -/
theorem fep033_finiteHorizon_nonneg (c : ℕ → ℝ) (T : Finset ℕ) (hc : ∀ t ∈ T, 0 ≤ c t) :
    0 ≤ ∑ t ∈ T, c t :=
  Finset.sum_nonneg hc

/-- Longer horizon → higher total cost (monotonicity of cumulative cost). -/
theorem fep033_horizon_mono (c : ℕ → ℝ) (S T : Finset ℕ)
    (hST : S ⊆ T) (hc : ∀ t ∈ T, 0 ≤ c t) :
    ∑ t ∈ S, c t ≤ ∑ t ∈ T, c t :=
  Finset.sum_le_sum_of_subset_of_nonneg hST (fun t ht _ => hc t ht)

/-- Discounting: scaled costs stay nonneg. -/
theorem fep033_discounted_nonneg (c : ℕ → ℝ) (γ : ℝ) (T : Finset ℕ)
    (hc : ∀ t ∈ T, 0 ≤ c t) (hγ : 0 ≤ γ) :
    0 ≤ ∑ t ∈ T, γ * c t :=
  Finset.sum_nonneg fun t ht => mul_nonneg hγ (hc t ht)

/-- Horizon-additive: cost over a union of disjoint time sets is the sum. -/
theorem fep033_horizon_union (c : ℕ → ℝ) (S T : Finset ℕ) (hd : Disjoint S T) :
    ∑ t ∈ S ∪ T, c t = (∑ t ∈ S, c t) + ∑ t ∈ T, c t :=
  Finset.sum_union hd

end FEP033

end fep_fep033

namespace fep_fep034

namespace FEP034

open Finset

-- [proof strategy: mul_nonneg + Finset.sum_nonneg for categorical Bayesian filter]

abbrev State := Fin 9

/-- Unnormalized Bayesian belief update at state `s`: multiplies the
likelihood at `s` by the predicted prior obtained by summing the transition
kernel against the previous belief over `states`. -/
def fep034_beliefUpdate (prior : State → ℝ) (trans : State → State → ℝ) (like : State → ℝ)
    (states : Finset State) (s : State) : ℝ :=
  like s * ∑ s' ∈ states, trans s s' * prior s'

/-- Per-state unnormalized posterior is nonneg. -/
theorem fep034_update_nonneg (prior : State → ℝ) (trans : State → State → ℝ) (like : State → ℝ)
    (states : Finset State) (s : State) (hp : ∀ x, 0 ≤ prior x) (ht : ∀ x y, 0 ≤ trans x y)
    (hl : ∀ x, 0 ≤ like x) : 0 ≤ fep034_beliefUpdate prior trans like states s :=
  mul_nonneg (hl s) (Finset.sum_nonneg fun s' _ => mul_nonneg (ht s s') (hp s'))

/-- Total unnormalized posterior mass over a finite state finset is nonneg. -/
theorem fep034_totalUnnorm_nonneg (prior : State → ℝ) (trans : State → State → ℝ) (like : State → ℝ)
    (states : Finset State) (hp : ∀ x, 0 ≤ prior x) (ht : ∀ x y, 0 ≤ trans x y)
    (hl : ∀ x, 0 ≤ like x) :
    0 ≤ ∑ s ∈ states, fep034_beliefUpdate prior trans like states s :=
  Finset.sum_nonneg fun s _ =>
    fep034_update_nonneg prior trans like states s hp ht hl

/-- Zero likelihood zeros out the posterior at that state. -/
theorem fep034_zero_like (prior : State → ℝ) (trans : State → State → ℝ)
    (states : Finset State) (s : State) :
    fep034_beliefUpdate prior trans (fun _ => 0) states s = 0 := by
  simp [fep034_beliefUpdate, mul_zero]

end FEP034

end fep_fep034

namespace fep_fep035

namespace FEP035

open Real

-- [proof strategy: Real.log_mul / log_pow / log_exp give Jensen-for-log identities]

/-- Logarithm turns products into sums (``log(ab)=log a+log b``). -/
theorem fep035_log_mul {a b : ℝ} (ha : 0 < a) (hb : 0 < b) :
    Real.log (a * b) = Real.log a + Real.log b :=
  Real.log_mul (ne_of_gt ha) (ne_of_gt hb)

/-- Power rule for logarithms on ``(0,∞)``. -/
theorem fep035_log_pow {a : ℝ} (_ha : 0 < a) (n : ℕ) : Real.log (a ^ n) = n * Real.log a :=
  Real.log_pow a n

/-- Jensen anchor: log(exp x) = x (log-exp inverse). -/
theorem fep035_log_exp (x : ℝ) : Real.log (Real.exp x) = x :=
  Real.log_exp x

/-- Concavity anchor: log on (0,∞) is monotone. -/
theorem fep035_log_mono {a b : ℝ} (ha : 0 < a) (h : a ≤ b) :
    Real.log a ≤ Real.log b :=
  Real.log_le_log ha h

/-- log 1 = 0. -/
theorem fep035_log_one : Real.log (1 : ℝ) = 0 := Real.log_one

end FEP035

end fep_fep035

namespace fep_fep036

namespace FEP036

variable {α : Type*} [MeasurableSpace α]

open MeasureTheory ENNReal

-- [proof strategy: ENNReal.toReal_nonneg + mul_nonneg + add_nonneg for empirical Bayes coupling]

/-- Empirical Bayes: nonneg weights stay nonneg when scaled by measure mass. -/
theorem fep036_scaledMass_nonneg (c : ℝ) (μ : Measure α) (s : Set α) (hc : 0 ≤ c) :
    0 ≤ c * (μ s).toReal :=
  mul_nonneg hc ENNReal.toReal_nonneg

/-- Empirical Bayes coupling: mixture of scaled measures. -/
theorem fep036_mixture_bound (w₁ w₂ : ℝ) (μ : Measure α) (s : Set α)
    (hw₁ : 0 ≤ w₁) (hw₂ : 0 ≤ w₂) :
    0 ≤ w₁ * (μ s).toReal + w₂ * (μ s).toReal :=
  add_nonneg (mul_nonneg hw₁ ENNReal.toReal_nonneg) (mul_nonneg hw₂ ENNReal.toReal_nonneg)

/-- toReal of a measure is always nonneg. -/
theorem fep036_toReal_nonneg (μ : Measure α) (s : Set α) : 0 ≤ (μ s).toReal :=
  ENNReal.toReal_nonneg

/-- Empty-set measure contributes zero to any empirical mixture. -/
theorem fep036_empty_contrib (c : ℝ) (μ : Measure α) : c * (μ ∅).toReal = 0 := by
  simp [measure_empty]

end FEP036

end fep_fep036

namespace fep_fep037

namespace FEP037

-- [proof strategy: mul_nonneg / mul_pos for FDT; Einstein relation as def]

/-- Fluctuation–dissipation: response coefficient Γ × fluctuation rate is nonneg. -/
theorem fep037_fdt_nonneg (Γ rate : ℝ) (hG : 0 ≤ Γ) (hL : 0 ≤ rate) : 0 ≤ Γ * rate :=
  mul_nonneg hG hL

/-- FDT at equilibrium: response = kT × fluctuation (Einstein relation shape). -/
noncomputable def fep037_einstein_response (kT fluctuation : ℝ) : ℝ := kT * fluctuation

/-- Einstein relation preserves positivity at positive temperature. -/
theorem fep037_einstein_pos (kT fluct : ℝ) (hT : 0 < kT) (hf : 0 < fluct) :
    0 < fep037_einstein_response kT fluct :=
  mul_pos hT hf

/-- Einstein relation vanishes when fluctuation vanishes. -/
theorem fep037_einstein_zero_fluct (kT : ℝ) : fep037_einstein_response kT 0 = 0 := by
  simp [fep037_einstein_response]

/-- Einstein response is monotone in fluctuation at positive temperature. -/
theorem fep037_einstein_mono (kT f₁ f₂ : ℝ) (hT : 0 ≤ kT) (h : f₁ ≤ f₂) :
    fep037_einstein_response kT f₁ ≤ fep037_einstein_response kT f₂ :=
  mul_le_mul_of_nonneg_left h hT

end FEP037

end fep_fep037

namespace fep_fep038

namespace FEP038

-- [proof strategy: positivity/sq_nonneg for PSD; Finset.sum_nonneg for Fisher metric]

/-- Preconditioned step norm squared is nonneg (Fisher-Rao metric is PSD on ℝ²). -/
theorem fep038_precond_norm_nonneg (u v : ℝ) : 0 ≤ u ^ 2 + v ^ 2 := by positivity

/-- Fisher inner product ⟨g,g⟩ = Σᵢ gᵢ² ≥ 0 (positive semi-definiteness). -/
theorem fep038_fisher_inner_nonneg (g : Fin 2 → ℝ) :
    0 ≤ ∑ i : Fin 2, g i * g i :=
  Finset.sum_nonneg fun i _ => mul_self_nonneg (g i)

/-- Natural gradient norm ‖g‖ = √(g₁² + g₂²) ≥ 0. -/
theorem fep038_natural_grad_norm_nonneg (g₁ g₂ : ℝ) :
    0 ≤ Real.sqrt (g₁ ^ 2 + g₂ ^ 2) :=
  Real.sqrt_nonneg _

/-- Fisher information is symmetric: F(θ)ᵢⱼ = F(θ)ⱼᵢ (modeled as inner product symmetry). -/
theorem fep038_fisher_sym (a b : Fin 2 → ℝ) :
    ∑ i : Fin 2, a i * b i = ∑ i : Fin 2, b i * a i := by
  congr 1; ext i; ring

end FEP038

end fep_fep038

namespace fep_fep039

namespace FEP039

open Finset

-- [proof strategy: Finset.sum_nonneg + sum_le_sum + sum_const for global-vs-local FE]

/-- Global free energy: ∑ local contributions over a partition. -/
def fep039_global_fe (local_fe : Fin 4 → ℝ) : ℝ :=
  ∑ i : Fin 4, local_fe i

/-- Global FE is nonneg when all local contributions are nonneg. -/
theorem fep039_global_nonneg (local_fe : Fin 4 → ℝ) (h : ∀ i, 0 ≤ local_fe i) :
    0 ≤ fep039_global_fe local_fe :=
  Finset.sum_nonneg fun i _ => h i

/-- Global FE monotone: improving one local term improves the global. -/
theorem fep039_global_mono (f g : Fin 4 → ℝ) (h : ∀ i, f i ≤ g i) :
    fep039_global_fe f ≤ fep039_global_fe g :=
  Finset.sum_le_sum fun i _ => h i

/-- Zero local FE everywhere → zero global FE. -/
theorem fep039_global_zero : fep039_global_fe (fun _ => 0) = 0 := by
  simp [fep039_global_fe]

/-- Global FE additive in pointwise sums. -/
theorem fep039_global_add (f g : Fin 4 → ℝ) :
    fep039_global_fe (fun i => f i + g i) = fep039_global_fe f + fep039_global_fe g := by
  simp [fep039_global_fe, Finset.sum_add_distrib]

end FEP039

end fep_fep039

namespace fep_fep040

namespace FEP040

open Real

-- [proof strategy: exp_log + sq_nonneg + log_le_log for Gaussian entropy properties]

/-- Gaussian entropy anchor: log of positive variance is well-defined. -/
theorem fep040_log_variance (σ : ℝ) (hσ : 0 < σ) : 0 < Real.exp (Real.log σ) := by
  rw [Real.exp_log hσ]
  exact hσ

/-- Variance is nonneg (used in Gaussian entropy H = ½ log(2πeσ²)). -/
theorem fep040_variance_nonneg (σ : ℝ) : 0 ≤ σ ^ 2 :=
  sq_nonneg σ

/-- Gaussian entropy increases with variance: σ₁ ≤ σ₂ → log σ₁ ≤ log σ₂. -/
theorem fep040_entropy_mono {σ₁ σ₂ : ℝ} (hσ₁ : 0 < σ₁) (h : σ₁ ≤ σ₂) :
    Real.log σ₁ ≤ Real.log σ₂ :=
  Real.log_le_log hσ₁ h

/-- Log of exp recovers identity: log(exp x) = x. -/
theorem fep040_log_exp (x : ℝ) : Real.log (Real.exp x) = x :=
  Real.log_exp x

/-- Heat capacity anchor: differential of log σ is 1/σ (qualitative scaling). -/
theorem fep040_heat_cap_nonneg (σ : ℝ) (hσ : 0 < σ) : 0 ≤ 1 / σ :=
  div_nonneg zero_le_one hσ.le

end FEP040

end fep_fep040

namespace fep_fep041

namespace FEP041

abbrev Obs := Fin 5
abbrev State := Fin 5

/-- Information gain: epistemic value computed as weighted divergence over observations. -/
def fep041_epistemic_value (w : Obs → ℝ) (div : Obs → ℝ) (O : Finset Obs) : ℝ :=
  ∑ o ∈ O, w o * div o

/-- Epistemic value is nonneg when weights and divergences are nonneg. -/
theorem fep041_epistemic_nonneg (w div : Obs → ℝ) (O : Finset Obs)
    (hw : ∀ o ∈ O, 0 ≤ w o) (hd : ∀ o ∈ O, 0 ≤ div o) :
    0 ≤ fep041_epistemic_value w div O :=
  Finset.sum_nonneg fun o ho => mul_nonneg (hw o ho) (hd o ho)

/-- Higher divergence → higher epistemic value (more to learn). -/
theorem fep041_epistemic_mono (w d₁ d₂ : Obs → ℝ) (O : Finset Obs)
    (hw : ∀ o ∈ O, 0 ≤ w o) (hd : ∀ o ∈ O, d₁ o ≤ d₂ o) :
    fep041_epistemic_value w d₁ O ≤ fep041_epistemic_value w d₂ O :=
  Finset.sum_le_sum fun o ho => mul_le_mul_of_nonneg_left (hd o ho) (hw o ho)

/-- Zero divergence → zero epistemic value. -/
theorem fep041_zero_div (w : Obs → ℝ) (O : Finset Obs) :
    fep041_epistemic_value w (fun _ => 0) O = 0 := by
  simp [fep041_epistemic_value, mul_zero]

/-- Empty observation set → zero epistemic value. -/
theorem fep041_empty_O (w div : Obs → ℝ) :
    fep041_epistemic_value w div (∅ : Finset Obs) = 0 := by
  simp [fep041_epistemic_value, Finset.sum_empty]

end FEP041

end fep_fep041

namespace fep_fep042

namespace FEP042

variable {α : Type*} [MeasurableSpace α]

/-- Sufficient statistics: measure of preimage is nonneg (ENNReal). -/
theorem fep042_push_nonneg (μ : MeasureTheory.Measure α) (f : α → ℝ) (s : Set ℝ) :
    0 ≤ μ (f ⁻¹' s) :=
  zero_le _

/-- Fisher-Neyman: preimage of full codomain is full domain. -/
theorem fep042_preimage_univ (f : α → ℝ) : f ⁻¹' Set.univ = Set.univ :=
  Set.preimage_univ

/-- Sufficient statistic map is monotone w.r.t. set inclusion. -/
theorem fep042_preimage_mono (f : α → ℝ) {s t : Set ℝ} (hst : s ⊆ t) :
    f ⁻¹' s ⊆ f ⁻¹' t :=
  Set.preimage_mono hst

/-- Preimage of intersection is intersection of preimages. -/
theorem fep042_preimage_inter (f : α → ℝ) (s t : Set ℝ) :
    f ⁻¹' (s ∩ t) = f ⁻¹' s ∩ f ⁻¹' t := by
  ext x; simp [Set.mem_preimage, Set.mem_inter_iff]

end FEP042

end fep_fep042

namespace fep_fep043

namespace FEP043

-- [proof strategy: sub_nonneg + sq_nonneg + minimum-characterisation algebra]

/-- Critical points: at a minimum, the function value is a lower bound. -/
theorem fep043_min_is_lower_bound (f : ℝ → ℝ) (x₀ : ℝ) (hmin : ∀ x, f x₀ ≤ f x) (y : ℝ) :
    f x₀ ≤ f y :=
  hmin y

/-- At a critical point, f(x₀ + h) - f(x₀) ≥ 0 for all perturbations. -/
theorem fep043_perturbation_nonneg (f : ℝ → ℝ) (x₀ : ℝ) (hmin : ∀ x, f x₀ ≤ f x) (h : ℝ) :
    0 ≤ f (x₀ + h) - f x₀ :=
  sub_nonneg.mpr (hmin _)

/-- Second-order condition: Hessian positivity at critical point (quadratic-form PSD). -/
theorem fep043_hessian_nonneg_at_min (h : ℝ) : 0 ≤ h ^ 2 :=
  sq_nonneg h

/-- At the critical point itself, f x₀ = f x₀ (reflexivity bound). -/
theorem fep043_at_min_self (f : ℝ → ℝ) (x₀ : ℝ) : f x₀ ≤ f x₀ := le_refl _

/-- Any two global minima of f agree in value. -/
theorem fep043_min_unique_value (f : ℝ → ℝ) (x₀ y₀ : ℝ)
    (hx : ∀ x, f x₀ ≤ f x) (hy : ∀ x, f y₀ ≤ f x) :
    f x₀ = f y₀ :=
  le_antisymm (hx y₀) (hy x₀)

end FEP043

end fep_fep043

namespace fep_fep044

namespace FEP044

-- [proof strategy: add_nonneg + mul_nonneg; endpoint identities by ring]

/-- α-divergence: convex combination for α ∈ [0,1] is between endpoints. -/
theorem fep044_convex_combo_nonneg (α a b : ℝ) (hα0 : 0 ≤ α) (hα1 : α ≤ 1)
    (ha : 0 ≤ a) (hb : 0 ≤ b) :
    0 ≤ α * a + (1 - α) * b :=
  add_nonneg (mul_nonneg hα0 ha) (mul_nonneg (sub_nonneg.mpr hα1) hb)

/-- α-divergence at α = 1 recovers KL-like term (degenerate case). -/
theorem fep044_alpha_one (a b : ℝ) : (1 : ℝ) * a + (1 - 1) * b = a := by ring

/-- α-divergence at α = 0 recovers reverse KL-like term. -/
theorem fep044_alpha_zero (a b : ℝ) : (0 : ℝ) * a + (1 - 0) * b = b := by ring

/-- α-divergence is monotone in the first argument at fixed α, b. -/
theorem fep044_mono_a (α a₁ a₂ b : ℝ) (hα0 : 0 ≤ α) (h : a₁ ≤ a₂) :
    α * a₁ + (1 - α) * b ≤ α * a₂ + (1 - α) * b := by
  have : α * a₁ ≤ α * a₂ := mul_le_mul_of_nonneg_left h hα0
  linarith

/-- α-divergence symmetry anchor (α ↔ 1-α swap). -/
theorem fep044_swap (α a b : ℝ) :
    α * a + (1 - α) * b = (1 - (1 - α)) * a + (1 - α) * b := by ring

end FEP044

end fep_fep044

namespace fep_fep045

namespace FEP045

/-- A conjugate family: prior parameters and a Bayesian update rule. -/
structure ConjugateFamily where
  priorParams : ℝ × ℝ
  update : ℝ × ℝ → ℝ → ℝ × ℝ

/-- Sequential Bayesian update via left fold over observations. -/
def fep045_conjugateUpdate (F : ConjugateFamily) (data : List ℝ) : ℝ × ℝ :=
  List.foldl F.update F.priorParams data

/-- Posterior always exists constructively. -/
theorem fep045_fold_exists (F : ConjugateFamily) (data : List ℝ) :
    ∃ p, fep045_conjugateUpdate F data = p :=
  ⟨_, rfl⟩

/-- Empty data returns the prior unchanged. -/
theorem fep045_empty_is_prior (F : ConjugateFamily) :
    fep045_conjugateUpdate F ([] : List ℝ) = F.priorParams :=
  rfl

/-- Single observation yields one update step. -/
theorem fep045_single_update (F : ConjugateFamily) (x : ℝ) :
    fep045_conjugateUpdate F [x] = F.update F.priorParams x :=
  rfl

/-- Inductive step: cons extends the fold. -/
theorem fep045_cons_update (F : ConjugateFamily) (x : ℝ) (xs : List ℝ) :
    fep045_conjugateUpdate F (x :: xs) =
      xs.foldl F.update (F.update F.priorParams x) :=
  rfl

end FEP045

end fep_fep045

namespace fep_fep046

namespace FEP046

/-- Stick-breaking: retained mass u*(1-v) is nonneg when u ≥ 0, v ≤ 1. -/
theorem fep046_stick_nonneg (u v : ℝ) (hu : 0 ≤ u) (hv1 : v ≤ 1) :
    0 ≤ u * (1 - v) :=
  mul_nonneg hu (sub_nonneg.mpr hv1)

/-- Remaining mass decreases after a break. -/
theorem fep046_remaining_decreases (u v : ℝ) (hu : 0 ≤ u) (hv0 : 0 ≤ v) (hv1 : v ≤ 1) :
    u * (1 - v) ≤ u := by
  nlinarith [mul_nonneg hu hv0]

/-- Two-step stick-breaking: mass after two breaks is nonneg. -/
theorem fep046_two_step_nonneg (u v₁ v₂ : ℝ)
    (hu : 0 ≤ u) (hv₁ : v₁ ≤ 1) (hv₂ : v₂ ≤ 1) :
    0 ≤ u * (1 - v₁) * (1 - v₂) :=
  mul_nonneg (fep046_stick_nonneg u v₁ hu hv₁) (sub_nonneg.mpr hv₂)

/-- Each break strictly reduces the mass when the break fraction is positive. -/
theorem fep046_strict_decrease (u v : ℝ) (hu : 0 < u) (hv0 : 0 < v) (hv1 : v ≤ 1) :
    u * (1 - v) < u := by nlinarith

end FEP046

end fep_fep046

namespace fep_fep047

namespace FEP047

open Finset

-- [proof strategy: Finset.sum_nonneg + mul_nonneg + sum_le_sum with left-multiplication]

abbrev State := Fin 7

/-- Forward message in a sum-product factor graph: aggregates the product of
the local factor `ψ x y` with the incoming message `inc y` over the neighbour
set `S`. -/
def fep047_forward (ψ : State → State → ℝ) (inc : State → ℝ) (S : Finset State) (x : State) : ℝ :=
  ∑ y ∈ S, ψ x y * inc y

/-- Forward message is nonneg when factors and incoming messages are nonneg. -/
theorem fep047_forward_nonneg (ψ : State → State → ℝ) (inc : State → ℝ) (S : Finset State)
    (x : State) (hψ : ∀ a b, 0 ≤ ψ a b) (hi : ∀ y, 0 ≤ inc y) : 0 ≤ fep047_forward ψ inc S x :=
  Finset.sum_nonneg fun y _ => mul_nonneg (hψ x y) (hi y)

/-- Message-passing monotonicity: larger incoming messages → larger output. -/
theorem fep047_forward_mono (ψ : State → State → ℝ) (inc₁ inc₂ : State → ℝ) (S : Finset State)
    (x : State) (hψ : ∀ a b, 0 ≤ ψ a b) (h : ∀ y ∈ S, inc₁ y ≤ inc₂ y) :
    fep047_forward ψ inc₁ S x ≤ fep047_forward ψ inc₂ S x :=
  Finset.sum_le_sum fun y hy => mul_le_mul_of_nonneg_left (h y hy) (hψ x y)

/-- Zero incoming messages → zero forward output. -/
theorem fep047_zero_in (ψ : State → State → ℝ) (S : Finset State) (x : State) :
    fep047_forward ψ (fun _ => 0) S x = 0 := by
  simp [fep047_forward, mul_zero]

/-- Empty neighbour set → zero forward output. -/
theorem fep047_empty_S (ψ : State → State → ℝ) (inc : State → ℝ) (x : State) :
    fep047_forward ψ inc (∅ : Finset State) x = 0 := by
  simp [fep047_forward, Finset.sum_empty]

end FEP047

end fep_fep047

namespace fep_fep048

namespace FEP048

-- [proof strategy: add_nonneg + Monotone.comp + contraction argument via abs bounds]

/-- Sync update: both components advance together, total is nonneg. -/
theorem fep048_sync_nonneg (a b : ℝ) (ha : 0 ≤ a) (hb : 0 ≤ b) : 0 ≤ a + b :=
  add_nonneg ha hb

/-- Async update: sequential composition preserves monotonicity. -/
theorem fep048_async_mono (f g : ℝ → ℝ) (hf : Monotone f) (hg : Monotone g) :
    Monotone (g ∘ f) :=
  hg.comp hf

/-- Contractive map: if f x = x, f y = y and |f x - f y| < |x - y|, then x = y. -/
theorem fep048_contraction_unique (f : ℝ → ℝ) (x y : ℝ)
    (hfx : f x = x) (hfy : f y = y)
    (hc : |f x - f y| < |x - y|) : x = y := by
  rw [hfx, hfy] at hc
  exact absurd hc (lt_irrefl _)

/-- Identity update is monotone (trivial sync). -/
theorem fep048_id_mono : Monotone (id : ℝ → ℝ) := fun _ _ h => h

/-- Sum of monotone scalar updates is monotone. -/
theorem fep048_add_mono (f g : ℝ → ℝ) (hf : Monotone f) (hg : Monotone g) :
    Monotone (fun x => f x + g x) :=
  fun _ _ h => add_le_add (hf h) (hg h)

end FEP048

end fep_fep048

namespace fep_fep049

namespace FEP049

/-- Entropy production rate: σ = J · F ≥ 0 (second law of thermodynamics). -/
theorem fep049_entropy_production_nonneg (J F : ℝ) (hJ : 0 ≤ J) (hF : 0 ≤ F) : 0 ≤ J * F :=
  mul_nonneg hJ hF

/-- Detailed balance: at equilibrium, entropy production vanishes. -/
theorem fep049_equilibrium_zero_production : (0 : ℝ) * (0 : ℝ) = 0 := by ring

/-- Entropy production is monotone in the thermodynamic force. -/
theorem fep049_production_mono_force (J F₁ F₂ : ℝ) (hJ : 0 ≤ J) (h : F₁ ≤ F₂) :
    J * F₁ ≤ J * F₂ :=
  mul_le_mul_of_nonneg_left h hJ

/-- Entropy production is monotone in the flux at fixed positive force. -/
theorem fep049_production_mono_flux (J₁ J₂ F : ℝ) (hF : 0 ≤ F) (h : J₁ ≤ J₂) :
    J₁ * F ≤ J₂ * F :=
  mul_le_mul_of_nonneg_right h hF

/-- Zero flux implies zero entropy production. -/
theorem fep049_zero_flux (F : ℝ) : (0 : ℝ) * F = 0 := by ring

end FEP049

end fep_fep049

namespace fep_fep050

namespace FEP050

/-- Landauer bound: work ≥ kT ln 2 per bit erased (information thermodynamics). -/
noncomputable def fep050_landauer_bound (kT : ℝ) : ℝ := kT * Real.log 2

/-- Landauer bound is positive at positive temperature. -/
theorem fep050_landauer_pos (kT : ℝ) (hT : 0 < kT) : 0 < fep050_landauer_bound kT :=
  mul_pos hT (Real.log_pos (by norm_num : (1 : ℝ) < 2))

/-- Work must exceed Landauer bound: W ≥ kT ln 2 implies W - kT ln 2 ≥ 0. -/
theorem fep050_excess_work_nonneg (W kT : ℝ) (hW : fep050_landauer_bound kT ≤ W) :
    0 ≤ W - fep050_landauer_bound kT :=
  sub_nonneg.mpr hW

/-- Erasing n bits costs at least n × kT ln 2 (positivity version). -/
theorem fep050_n_bits (kT : ℝ) (n : ℕ) (hT : 0 < kT) :
    0 < n * fep050_landauer_bound kT ↔ 0 < n := by
  constructor
  · intro h
    by_contra hle
    push_neg at hle
    have : n = 0 := Nat.le_zero.mp hle
    simp [this, fep050_landauer_bound] at h
  · intro hn
    exact mul_pos (Nat.cast_pos.mpr hn) (fep050_landauer_pos kT hT)

/-- Landauer bound vanishes at zero temperature. -/
theorem fep050_zero_temp : fep050_landauer_bound 0 = 0 := by
  simp [fep050_landauer_bound]

end FEP050

end fep_fep050
