#!/usr/bin/env python3
"""Deterministic Q5 probe generator and freshness gate.

Regenerates, from the retained runner fixtures:

- ``generated/probe_symmetric.lean`` — the concrete PyMDP artifact proof for
  the accepted P1 runner (byte-copy under ``fixtures/``);
- ``generated/probe_asymmetric.lean`` — the axis-sensitive normalized dyadic
  control probe;
- ``generated/artifact_proof_manifest.json`` — SHA-256 digests of the
  fixtures, the extractor module, the generated probes, and the expected
  exact-rational payload record.

``--check`` regenerates in memory only and verifies the committed artifacts
are byte-identical and every digest matches (exit 0 fresh, exit 1 stale),
following the P2 emitter pattern. No Lean process is launched here; probe
compilation is owned by the focused pytest layer.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

from fep_lean.verification.gnn_artifact_proof import (
    PymdpArtifactTables,
    extract_pymdp_tables,
    manifest_mismatches,
    render_lean_probe,
    render_manifest,
    sha256_file,
)

REPO_ROOT = Path(__file__).resolve().parents[2]
SLICE = REPO_ROOT / "specs" / "gnn-bridge-q5-artifact-proof"
FIXTURES = {
    "symmetric": SLICE / "fixtures" / "pymdp_symmetric_runner.py",
    "asymmetric": SLICE / "fixtures" / "pymdp_asymmetric_runner.py",
}
GENERATED = SLICE / "generated"
MANIFEST = GENERATED / "artifact_proof_manifest.json"
EXTRACTOR = REPO_ROOT / "src" / "fep_lean" / "verification" / "gnn_artifact_proof.py"


def _expected_payload(tables: PymdpArtifactTables) -> dict[str, object]:
    record: dict[str, object] = {}
    for name in ("A_data", "B_data", "C_data", "D_data", "E_data"):
        value = tables.table(name)
        record[name] = {
            "shape": list(value.shape),
            "values": [str(entry) for _, entry in value.entries()],
        }
    return record


def regenerate() -> tuple[dict[str, str], dict[str, object]]:
    """Recompute every generated artifact in memory; return texts and payload."""
    import hashlib

    texts: dict[str, str] = {}
    payload: dict[str, object] = {}
    fixture_digests = {path.name: sha256_file(path) for path in FIXTURES.values()}
    for variant, fixture_path in FIXTURES.items():
        source = fixture_path.read_text(encoding="utf-8")
        tables = extract_pymdp_tables(
            source, source_name=str(fixture_path.relative_to(REPO_ROOT))
        )
        texts[f"generated/probe_{variant}.lean"] = render_lean_probe(
            tables,
            variant=variant,
            fixture_name=fixture_path.name,
            fixture_sha256=fixture_digests[fixture_path.name],
        )
        payload[variant] = _expected_payload(tables)
    manifest = render_manifest(
        fixture_digests=fixture_digests,
        extractor_sha256=sha256_file(EXTRACTOR),
        generated={
            name: hashlib.sha256(text.encode("utf-8")).hexdigest()
            for name, text in texts.items()
        },
        expected_payload=payload,
    )
    texts["generated/artifact_proof_manifest.json"] = manifest
    return texts, payload


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify committed artifacts are fresh instead of writing them",
    )
    args = parser.parse_args()

    texts, _payload = regenerate()
    if not args.check:
        GENERATED.mkdir(parents=True, exist_ok=True)
        for name, text in texts.items():
            (SLICE / name).write_text(text, encoding="utf-8")
            print(f"wrote {name} ({len(text.encode('utf-8'))} bytes)")
        return 0

    problems = manifest_mismatches(
        MANIFEST.read_text(encoding="utf-8"),
        repo_root=REPO_ROOT,
        slice_root=SLICE,
        regenerate={
            name: __import__("hashlib").sha256(text.encode("utf-8")).hexdigest()
            for name, text in texts.items()
        },
    )
    for name, text in texts.items():
        on_disk = (SLICE / name).read_text(encoding="utf-8")
        if on_disk != text:
            problems.append(f"{name}: regenerated bytes differ from committed artifact")
    if problems:
        for problem in problems:
            print(f"STALE: {problem}", file=sys.stderr)
        return 1
    print("OK: Q5 generated artifacts are fresh (probes, manifest, digests)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
