"""Deterministic catalogue projections from the maintained authoring sources."""

from __future__ import annotations

import re
from collections.abc import Mapping
from pathlib import Path
from typing import Any

import yaml

from fep_lean.lean_source import lean_code_without_comments

from .novelty import load_formalism_novelty
from .registry import (
    BODIES,
    LATEX_EQUATIONS,
    assert_roster,
    validate_body_family_ownership,
)
from .schema import load_catalogue_metadata
from .semantics import load_theorem_maturity, render_proxy_statement


def topics_header(topic_count: int) -> str:
    """Return the generated projection header without a fixed roster constant."""
    return (
        f"# FEP / Active Inference / Bayesian Mechanics — {topic_count}-topic Lean4 catalogue\n"
        "# Each topic maps to one OpenGauss session when workflows are enabled.\n"
        "# Regenerate: uv run python scripts/_maint_build_topics_catalogue.py\n"
        "# Fields include compile maturity and a separately reviewed semantic disposition.\n"
        "# `latex_equations` is generated from fep_lean.catalogue.registry; do not edit it here.\n"
        "# Manuscript rendering consumes those same generated equation signatures.\n\n"
    )


_IMPORT_RE = re.compile(r"^import\s+\S+.*$", re.MULTILINE)


def strip_sketch_imports(body: str) -> str:
    """Remove imports that the aggregate projection hoists to its header."""
    code = lean_code_without_comments(body)
    return "".join(
        raw_line
        for raw_line, code_line in zip(
            body.splitlines(keepends=True), code.splitlines(keepends=True), strict=True
        )
        if _IMPORT_RE.match(code_line) is None
    ).lstrip("\n")


def hoisted_sketch_imports(sketches: Mapping[str, str]) -> tuple[str, ...]:
    """Return the exact distinct sketch imports in deterministic order."""
    return tuple(
        sorted(
            {
                import_line.strip()
                for body in sketches.values()
                for import_line in _IMPORT_RE.findall(lean_code_without_comments(body))
            }
        )
    )


def topic_id_to_namespace(topic_id: str) -> str:
    """Convert ``fep-NNN`` to the aggregate's ``fep_fepNNN`` namespace."""
    if not topic_id.startswith("fep-"):
        raise ValueError(f"unexpected topic id format: {topic_id!r}")
    suffix = topic_id.removeprefix("fep-")
    if not suffix.isdigit():
        raise ValueError(f"non-numeric topic suffix: {topic_id!r}")
    return f"fep_fep{suffix}"


def render_fep_all_lean(sketches: Mapping[str, str] | None = None) -> str:
    """Render the canonical whole-catalogue Lean projection."""
    source = dict(BODIES) if sketches is None else dict(sketches)
    if not source:
        raise ValueError(
            "body registry is empty — refusing to write a degenerate aggregate"
        )

    parts = [
        "-- AUTO-GENERATED by scripts/_maint_build_fep_all_lean.py",
        "-- Source of truth: src/fep_lean/catalogue/bodies/*.py via catalogue.registry",
        "-- Do not edit by hand; regenerate after any canonical body change.",
        "--",
        "-- Each topic body is wrapped in `namespace fep_fepNNN ... end fep_fepNNN`",
        "-- so identically-named helpers across topics never collide during the",
        "-- whole-catalogue `lake build FepSketches`. Inner `namespace FEPNNN`",
        "-- blocks are preserved so per-topic qualified names stay stable.",
        *hoisted_sketch_imports(source),
        "",
    ]
    for topic_id in sorted(source):
        namespace = topic_id_to_namespace(topic_id)
        body = strip_sketch_imports(source[topic_id]).rstrip()
        parts.extend((f"namespace {namespace}", "", body, "", f"end {namespace}", ""))
    return "\n".join(parts).rstrip() + "\n"


def fep_all_projection_path(project_root: Path) -> Path:
    """Return the tracked whole-catalogue Lean projection path."""
    return Path(project_root) / "lean" / "FepSketches" / "fep_all.lean"


def fep_all_projection_drift(project_root: Path) -> tuple[Path, ...]:
    """Return the aggregate path when its bytes differ from canonical sketches."""
    path = fep_all_projection_path(project_root)
    expected = render_fep_all_lean()
    try:
        current = path.read_text(encoding="utf-8")
    except OSError:
        return (path,)
    return () if current == expected else (path,)


def build_topics_data(project_root: Path) -> dict[str, Any]:
    """Join metadata, semantic review, Lean bodies, and equation signatures."""
    root = Path(project_root)
    metadata = load_catalogue_metadata(root / "config" / "catalogue_metadata.yaml")
    assert_roster(metadata.topic_ids)
    validate_body_family_ownership(
        {record.id: record.family for record in metadata.records}
    )
    audit = load_theorem_maturity(
        root / "config" / "theorem_maturity.yaml",
        roster_ids=metadata.topic_ids,
    )
    reviews = audit.by_topic_id
    if [row.id for row in metadata.records] != [record.id for record in audit.records]:
        raise ValueError("catalogue metadata and theorem maturity rosters differ")
    from fep_lean.formal.declarations import composed_theorem_sources

    load_formalism_novelty(
        root / "config" / "formalism_novelty.yaml",
        metadata.topic_ids,
        composed_sources=composed_theorem_sources(root),
    )

    rows: list[dict[str, Any]] = []
    for meta in metadata.records:
        review = reviews[meta.id]
        rows.append(
            {
                "id": meta.id,
                "title": meta.title,
                "area": meta.area,
                "family": meta.family,
                "mathlib_modules": list(meta.mathlib_modules),
                "mathlib_status": meta.mathlib_status,
                "primary_theorem": review.primary_theorem,
                "supporting_theorems": list(review.supporting_theorems),
                "boundary_theorems": list(review.boundary_theorems),
                "semantic_disposition": review.disposition.value,
                "nl": render_proxy_statement(review),
                "assumption_review": review.assumption_review,
                "non_vacuity": review.non_vacuity,
                "acceptance_probe": review.acceptance_probe,
                "lean_sketch": BODIES[meta.id],
                "latex_equations": list(LATEX_EQUATIONS[meta.id]),
            }
        )
    return {
        "schema_version": 2,
        "roster": {
            "first_id": metadata.roster.first_id,
            "last_id": metadata.roster.last_id,
        },
        "families": list(metadata.families),
        "topics": rows,
    }


def render_topics_yaml(project_root: Path) -> str:
    """Render the checkout and wheel catalogue bytes."""
    data = build_topics_data(project_root)
    rows = data["topics"]
    return topics_header(len(rows)) + yaml.safe_dump(
        data,
        sort_keys=False,
        allow_unicode=True,
        width=120,
    )


def catalogue_projection_paths(project_root: Path) -> tuple[Path, Path]:
    """Return checkout and package-data destinations in stable order."""
    root = Path(project_root)
    return (
        root / "config" / "topics.yaml",
        root / "src" / "fep_lean" / "data" / "topics.yaml",
    )


def write_topics_catalogues(project_root: Path) -> tuple[Path, Path]:
    """Write both generated projections from one rendered byte sequence."""
    rendered = render_topics_yaml(project_root)
    paths = catalogue_projection_paths(project_root)
    for path in paths:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(rendered, encoding="utf-8")
    return paths


def catalogue_projection_drift(project_root: Path) -> list[Path]:
    """Return generated paths whose current bytes differ from canonical output."""
    expected = render_topics_yaml(project_root)
    return [
        path
        for path in catalogue_projection_paths(project_root)
        if not path.is_file() or path.read_text(encoding="utf-8") != expected
    ]
