#!/usr/bin/env python3
"""Deterministic fep_lean -> GNN document projector (bridge P1/P2 spike).

Projects the compiled Lean instance

    FEP.ActiveInference.symmetricBoolModel trueBiasedPolicyPrior
      : GenerativeModel Bool Bool Bool

from `lean/FepSketches/active_inference.lean` (fep_lean pinned workspace)
to a GNN v1 document (`FepLeanSymmetricBool.md`) that the
GeneralizedNotationNotation pipeline parses (step 3), type checks
(step 5), renders (step 11), and executes (step 12).

Every emitted numeric literal is the exact Lean source value with a
file:line provenance comment; nothing is rounded (spec README,
"Rounding policy"). Regeneration is byte-deterministic given unchanged
repository state: the only varying inputs are the two commit digests,
which are part of the document's provenance by design (bridge contract
section 4 and section 9 artifact-custody policy).

Modes:
  default    regenerate `gnn-input/FepLeanSymmetricBool.md` in place.
  --check    freshness gate (style of `fep-lean atlas --check`): exit 0
             only when the on-disk document equals the regenerated bytes
             and its recorded digests equal the live repository heads;
             exit 1 with a reason otherwise.

This script never invokes Lean tooling (task constraint) and never
writes outside this spec slice.
"""

from __future__ import annotations

import argparse
import subprocess
import sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
FEP_LEAN_ROOT = SCRIPT_DIR.parents[1]
GNN_ROOT = FEP_LEAN_ROOT.parent / "GeneralizedNotationNotation"
ARTIFACT_PATH = SCRIPT_DIR / "gnn-input" / "FepLeanSymmetricBool.md"

FEP_LEAN_LEAN_MODULE = "lean/FepSketches/active_inference.lean"
GENERATOR_IDENTITY = (
    "fep_lean specs/gnn-bridge-p1-finite-spike/projection.py"
    " (bridge P1/P2 deterministic emitter)"
)
SYNTAX_TARGET = "GNN v1 (doc/gnn/gnn_syntax.md v1.1 surface)"
ROUNDING_POLICY = (
    "exact Lean rationals emitted as shortest exact terminating decimal"
    " strings; non-terminating expansions are a no-go, never rounded"
)

# --- Lean-extracted values (exact; see spec README extraction record) ---

# lean/FepSketches/active_inference.lean:743-744 — carrier types
# Policy = Bool, State = Bool, Outcome = Bool.
NUM_POLICIES = 2
NUM_STATES = 2
NUM_OBS = 2

# lean/FepSketches/active_inference.lean:719-722 (mass _ := 1 / 2, line
# 720), used at lines 745 (initialState) and 748 (preferences).
# Bool index order is (false, true).
D_VALUES = ("0.5", "0.5")
C_VALUES = ("0.5", "0.5")

# lean/FepSketches/active_inference.lean:725-728 (mass _ _ := 1 / 2,
# line 726). Likelihood := fairBoolKernel (line 747): A[obs, state],
# all entries 1/2.
A_VALUES: tuple[tuple[str, str], tuple[str, str]] = (
    ("0.5", "0.5"),
    ("0.5", "0.5"),
)

# Same definition, used policy-indexed at line 746 (`transition _ :=
# fairBoolKernel`): B[next_state, previous_state, policy], both policy
# slices identical, every entry 1/2.
B_SLICES: tuple[
    tuple[tuple[str, str], tuple[str, str]],
    tuple[tuple[str, str], tuple[str, str]],
] = (
    (("0.5", "0.5"), ("0.5", "0.5")),
    (("0.5", "0.5"), ("0.5", "0.5")),
)

# lean/FepSketches/active_inference.lean:731-734 (mass policy :=
# if policy then 3 / 4 else 1 / 4, line 732) applied at lines 743/749:
# E(false) = 1/4, E(true) = 3/4.
E_VALUES = ("0.25", "0.75")


def repo_head(repo: Path) -> str:
    """Return `git rev-parse HEAD` for *repo* (read-only query)."""
    result = subprocess.run(
        ["git", "rev-parse", "HEAD"],
        cwd=repo,
        capture_output=True,
        text=True,
        check=True,
    )
    return result.stdout.strip()


def _row(values: tuple[str, str]) -> str:
    return "(" + ", ".join(values) + ")"


def _slice(values: tuple[tuple[str, str], tuple[str, str]]) -> str:
    return "( " + ", ".join(_row(r) for r in values) + " )"


def build_document(fep_lean_head: str, gnn_head: str) -> str:
    """Render the GNN document for the pinned Lean instance."""
    lines = [
        "# GNN Bridge: FepLean Symmetric Boolean Generative Model",
        "# GNN Version: 1.0",
        "# Deterministic projection of the compiled Lean instance",
        "#   FEP.ActiveInference.symmetricBoolModel trueBiasedPolicyPrior",
        "#   (fep_lean, lean/FepSketches/active_inference.lean:743-749).",
        "# Every numeric literal below is the exact Lean source value;",
        "# provenance file:line comments name each definition site.",
        "",
        "## GNNSection",
        "FepLeanSymmetricBool",
        "",
        "## GNNVersionAndFlags",
        "GNN v1",
        "",
        "## ModelName",
        "FepLean Symmetric Boolean Generative Model",
        "",
        "## ModelAnnotation",
        "Bridge P1 spike: the fep_lean active_inference.lean",
        "GenerativeModel instance `symmetricBoolModel trueBiasedPolicyPrior`",
        "(two policies, two hidden states, two observations, one step)",
        "projected deterministically to GNN v1 syntax.",
        "Extraction record (file:line in the fep_lean checkout at the",
        "commit recorded under Signature):",
        "- D initialState = fairBoolLaw (1/2, 1/2)",
        "  [def active_inference.lean:719-722; use :745]",
        "- B transition = fairBoolKernel, policy-indexed, all entries 1/2",
        "  [def active_inference.lean:725-728; use :746]",
        "- A likelihood = fairBoolKernel, all entries 1/2",
        "  [def active_inference.lean:725-728; use :747]",
        "- C preferences = fairBoolLaw (1/2, 1/2)",
        "  [def active_inference.lean:719-722; use :748]",
        "- E policyPrior = trueBiasedPolicyPrior: E(false)=1/4, E(true)=3/4",
        "  [def active_inference.lean:731-734; parameter :743,:749]",
        "- Timescale: one transition application [active_inference.lean:30-32]",
        "- The Lean GenerativeModel carries no Action type, so no `u`",
        "  variable or action edges are emitted.",
        "",
        "## StateSpaceBlock",
        "# Likelihood matrix: A[observation_outcomes, hidden_states]",
        "A[2,2,type=float]      # likelihood : FiniteKernel State Outcome",
        "# Transition matrix: B[next_state, previous_state, policy]",
        "B[2,2,2,type=float]    # transition : Policy -> FiniteKernel State State",
        "# Preference vector: C[observation_outcomes] (probability law)",
        "C[2,type=float]        # preferences : FiniteLaw Outcome",
        "# Prior vector: D[states]",
        "D[2,type=float]        # initialState : FiniteLaw State",
        "# Policy prior vector: E[policies]",
        "E[2,type=float]        # policyPrior : FiniteLaw Policy",
        "# Hidden state",
        "s[2,1,type=float]      # initialState distribution",
        "s_prime[2,1,type=float]  # predictedState (one-step)",
        "# Observation",
        "o[2,1,type=float]      # predictedOutcome distribution",
        "# Policy",
        "π[2,type=float]        # policy prior / posterior over policies",
        "F[π,type=float]        # variationalFreeEnergy readout",
        "G[π,type=float]        # expectedFreeEnergy readout",
        "# Time",
        "t[1,type=int]          # discrete time step (one-step model)",
        "",
        "## Connections",
        "# Plain edges only: the pipeline markdown parser (step 3) does not",
        "# strip v1.1 ':annotation' suffixes and then warns on the targets;",
        "# recorded as a GNN-side parser finding in the slice report.",
        "D>s",
        "s-B",
        "B>s_prime",
        "s_prime-A",
        "A-o",
        "E>π",
        "π-B",
        "C>G",
        "G>π",
        "",
        "## InitialParameterization",
        "# Rounding policy: exact Lean rationals -> exact terminating",
        "# decimal strings; no value is rounded.",
        "# A: active_inference.lean:725-728 (mass _ _ := 1 / 2), used :747.",
        "# Rows are observations, columns are hidden states (Bool: false, true).",
        "A={",
        "  " + _row(A_VALUES[0]) + ",",
        "  " + _row(A_VALUES[1]),
        "}",
        "",
        "# B: active_inference.lean:725-728, policy-indexed at :746.",
        "# B[next_state, previous_state, policy]; per-policy slices are",
        "# column-stochastic 2x2 matrices (rows next, columns previous).",
        "B={",
        "  " + _slice(B_SLICES[0]) + ",",
        "  " + _slice(B_SLICES[1]),
        "}",
        "",
        "# C: active_inference.lean:719-722, used :748. Probability law",
        "# over outcomes (Bool: false, true); emitted untransformed.",
        "C={" + _row(C_VALUES) + "}",
        "",
        "# D: active_inference.lean:719-722, used :745.",
        "D={" + _row(D_VALUES) + "}",
        "",
        "# E: active_inference.lean:731-734 (mass policy := if policy then",
        "# 3 / 4 else 1 / 4), applied at :743,:749.",
        "E={" + _row(E_VALUES) + "}",
        "",
        "## Equations",
        "# Lean-defined quantities over the projected instance",
        "# (file:line in lean/FepSketches/active_inference.lean):",
        "# predictedState  :30-32   q_π(s') = Σ_s B[s',s,π] D[s]",
        "# predictedOutcome:40-42   p_π(o)  = Σ_s' A[o,s'] q_π(s')",
        "# risk            :128-131 KL(p_π || C)",
        "# ambiguity       :133-135 Σ_s' q_π(s') H(A[·,s'])",
        "# expectedFreeEnergy :148-150 G(π) = risk(π) + ambiguity(π)",
        "# variationalFreeEnergy :209-214 F = KL(q||posterior) + surprisal",
        "# policyPosterior :475-485 Q(π) ∝ E(π) exp(-γ G(π))",
        "",
        "## Time",
        "Time=t",
        "Dynamic",
        "Discrete",
        "ModelTimeHorizon=1",
        "",
        "## ActInfOntologyAnnotation",
        "A=LikelihoodMatrix",
        "B=TransitionMatrix",
        "C=Preferences",
        "D=PriorOverHiddenStates",
        "E=Habit",
        "F=VariationalFreeEnergy",
        "G=ExpectedFreeEnergy",
        "s=HiddenState",
        "s_prime=NextHiddenState",
        "o=Observation",
        "π=PolicyVector",
        "t=Time",
        "",
        "## ModelParameters",
        "num_hidden_states: 2  # State = Bool",
        "num_obs: 2            # Outcome = Bool",
        "num_actions: 2        # B policy dimension = Policy = Bool",
        "num_timesteps: 1      # one-step model",
        "",
        "## Footer",
        "FepLean bridge P1 spike: symmetric Boolean generative model",
        "projected from fep_lean active_inference.lean",
        "symmetricBoolModel trueBiasedPolicyPrior. One-step horizon,",
        "no planning depth, no precision modulation.",
        "",
        "## Signature",
        "source_repository: fep_lean",
        f"source_commit: {fep_lean_head}",
        "pipeline_repository: GeneralizedNotationNotation",
        f"pipeline_commit: {gnn_head}",
        f"lean_module: {FEP_LEAN_LEAN_MODULE}",
        "lean_structure: FEP.ActiveInference.GenerativeModel",
        "lean_instance: FEP.ActiveInference.symmetricBoolModel trueBiasedPolicyPrior",
        "projection_tool: " + GENERATOR_IDENTITY,
        f"target_syntax: {SYNTAX_TARGET}",
        f"rounding_policy: {ROUNDING_POLICY}",
    ]
    return "\n".join(lines) + "\n"


def write_document() -> int:
    """Regenerate the artifact in place (default mode)."""
    document = build_document(repo_head(FEP_LEAN_ROOT), repo_head(GNN_ROOT))
    ARTIFACT_PATH.parent.mkdir(parents=True, exist_ok=True)
    ARTIFACT_PATH.write_text(document, encoding="utf-8")
    print(f"wrote {ARTIFACT_PATH} ({len(document)} bytes)")
    return 0


def check_document() -> int:
    """Freshness gate: regenerated bytes and live digests must match."""
    fep_lean_head = repo_head(FEP_LEAN_ROOT)
    gnn_head = repo_head(GNN_ROOT)
    regenerated = build_document(fep_lean_head, gnn_head)
    if not ARTIFACT_PATH.is_file():
        print(f"DRIFT: missing artifact {ARTIFACT_PATH}")
        return 1
    on_disk = ARTIFACT_PATH.read_text(encoding="utf-8")
    if on_disk != regenerated:
        print(
            "DRIFT: on-disk document differs from regeneration at"
            f" fep_lean {fep_lean_head} / GNN {gnn_head}"
        )
        return 1
    print(
        "FRESH:"
        f" fep_lean {fep_lean_head} / GNN {gnn_head}"
        " — regenerated bytes match on-disk artifact"
    )
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description=(
            "Deterministic fep_lean -> GNN projector for the bridge P1"
            " finite spike; --check gates freshness."
        )
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit non-zero when the artifact is missing or stale",
    )
    args = parser.parse_args(argv)
    if args.check:
        return check_document()
    return write_document()


if __name__ == "__main__":
    sys.exit(main())
