"""Canonical Lean bodies for one original catalogue family."""

from __future__ import annotations

BODIES: dict[str, str] = {
    "fep-001": """import Mathlib.InformationTheory.KullbackLeibler.Basic

namespace FEP001

variable {α : Type*} [MeasurableSpace α]

open MeasureTheory
open scoped ENNReal

/-- Native variational gap between an approximate and exact posterior law. -/
noncomputable def fep001_variationalGap
    (approximation posterior : Measure α) : ENNReal :=
  InformationTheory.klDiv approximation posterior

/-- Surprisal plus the native KL variational gap. -/
noncomputable def fep001_variationalUpperBound
    (approximation posterior : Measure α) (surprisal : ENNReal) : ENNReal :=
  surprisal + fep001_variationalGap approximation posterior

/-- The KL remainder makes the variational quantity an upper bound. -/
theorem fep001_variationalUpperBound_ge
    (approximation posterior : Measure α) (surprisal : ENNReal) :
    surprisal ≤
      fep001_variationalUpperBound approximation posterior surprisal := by
  exact le_add_right (le_refl _)

/-- For finite measures, the variational gap vanishes exactly at the posterior. -/
theorem fep001_variationalGap_eq_zero_iff
    (approximation posterior : Measure α)
    [IsFiniteMeasure approximation] [IsFiniteMeasure posterior] :
    fep001_variationalGap approximation posterior = 0 ↔
      approximation = posterior := by
  exact InformationTheory.klDiv_eq_zero_iff

/-- At finite surprisal, the variational bound is exact exactly when the
approximation equals the posterior. -/
theorem fep001_variationalUpperBound_eq_iff
    (approximation posterior : Measure α)
    [IsFiniteMeasure approximation] [IsFiniteMeasure posterior]
    {surprisal : ENNReal} (hsurprisal : surprisal ≠ ∞) :
    fep001_variationalUpperBound approximation posterior surprisal = surprisal ↔
      approximation = posterior := by
  constructor
  · intro hbound
    have hadd : surprisal + fep001_variationalGap approximation posterior =
        surprisal + 0 := by
      simpa [fep001_variationalUpperBound] using hbound
    have hgap : fep001_variationalGap approximation posterior = 0 :=
      (ENNReal.add_right_inj hsurprisal).mp hadd
    exact (fep001_variationalGap_eq_zero_iff approximation posterior).mp hgap
  · intro hequal
    subst posterior
    simp [fep001_variationalUpperBound, fep001_variationalGap,
      InformationTheory.klDiv_self]

end FEP001
""",
    "fep-002": """import Mathlib.InformationTheory.KullbackLeibler.Basic
import Mathlib.MeasureTheory.Measure.Typeclasses.Probability

namespace FEP002

variable {α : Type*} [MeasurableSpace α]

open MeasureTheory
open scoped ENNReal

-- [proof strategy: IsProbabilityMeasure.measure_univ + measure_compl for complement; linarith for ELBO]
/-- A probability measure assigns unit total mass. -/
theorem fep002_prob_measure_univ (μ : Measure α) [IsProbabilityMeasure μ] :
    μ Set.univ = 1 :=
  IsProbabilityMeasure.measure_univ

/-- Complement: μ(sᶜ) = 1 - μ(s) for probability measures on measurable sets. -/
theorem fep002_prob_compl (μ : Measure α) [IsProbabilityMeasure μ] {s : Set α}
    (hs : MeasurableSet s) (hfin : μ s ≠ ⊤) :
    μ sᶜ = 1 - μ s := by
  rw [measure_compl hs hfin, IsProbabilityMeasure.measure_univ]

/-- A scalar ELBO decomposition: free energy ≤ log marginal likelihood when the
KL remainder is nonnegative. -/
theorem fep002_elbo_bound (logEvidence freeEnergy klDiv : ℝ)
    (h_decomp : logEvidence = freeEnergy + klDiv)
    (h_kl_nonneg : 0 ≤ klDiv) :
    freeEnergy ≤ logEvidence := by linarith

/-- Variational free energy in Mathlib's native nonnegative extended-real KL
codomain: surprisal plus the divergence from an approximate posterior to the
exact posterior. -/
noncomputable def fep002_variationalFreeEnergy
    (q posterior : Measure α) (surprisal : ENNReal) : ENNReal :=
  surprisal + InformationTheory.klDiv q posterior

/-- The KL remainder makes variational free energy an upper bound on
surprisal. -/
theorem fep002_vfe_ge_surprisal (q posterior : Measure α) (surprisal : ENNReal) :
    surprisal ≤ fep002_variationalFreeEnergy q posterior surprisal := by
  simp only [fep002_variationalFreeEnergy]
  exact le_add_right (le_refl surprisal)

/-- The variational bound is exact when the approximation is the posterior
itself. -/
theorem fep002_vfe_exact_at_posterior (posterior : Measure α)
    [SigmaFinite posterior] (surprisal : ENNReal) :
    fep002_variationalFreeEnergy posterior posterior surprisal = surprisal := by
  simp [fep002_variationalFreeEnergy, InformationTheory.klDiv_self]

end FEP002
""",
    "fep-006": """import Mathlib.Dynamics.FixedPoints.Basic
import Mathlib.MeasureTheory.MeasurableSpace.Basic

namespace FEP006

variable {α : Type*}

/-- The discrete-time flow generated by repeatedly applying one state update. -/
def fep006_iterateFlow (step : α → α) (time : ℕ) : α → α :=
  step^[time]

/-- Every time slice of a measurable discrete flow is measurable. -/
theorem fep006_iterateFlow_measurable
    [MeasurableSpace α] {step : α → α} (hstep : Measurable step) (time : ℕ) :
    Measurable (fep006_iterateFlow step time) := by
  exact hstep.iterate time

/-- The time-zero flow is the identity. -/
theorem fep006_iterateFlow_zero (step : α → α) :
    fep006_iterateFlow step 0 = id := by
  rfl

/-- Discrete flow obeys the exact additive semigroup law. -/
theorem fep006_iterateFlow_add (step : α → α) (m n : ℕ) (state : α) :
    fep006_iterateFlow step (m + n) state =
      fep006_iterateFlow step m (fep006_iterateFlow step n state) := by
  exact Function.iterate_add_apply step m n state

/-- A fixed point remains fixed at every discrete time. -/
theorem fep006_iterateFlow_fixed
    (step : α → α) {state : α} (hfixed : Function.IsFixedPt step state)
    (time : ℕ) :
    fep006_iterateFlow step time state = state := by
  exact hfixed.iterate time

end FEP006
""",
    "fep-011": """import Mathlib.Analysis.SpecialFunctions.Log.Basic

namespace FEP011

open Real

/-- Shannon self-information (surprise) of a positive scalar probability. -/
noncomputable def fep011_surprise (probability : ℝ) : ℝ :=
  -Real.log probability

/-- Self-information: log is nonnegative on ``[1, ∞)``. -/
theorem fep011_log_nonneg_on_ge_one {x : ℝ} (hx : 1 ≤ x) : 0 ≤ Real.log x :=
  Real.log_nonneg hx

/-- Coding cost ``-log u`` is nonnegative for probabilities ``u ∈ (0, 1]``. -/
theorem fep011_surprise_nonneg {u : ℝ} (hu : 0 < u) (hu1 : u ≤ 1) :
    0 ≤ fep011_surprise u :=
  neg_nonneg.mpr (Real.log_nonpos (le_of_lt hu) hu1)

/-- Surprise is additive for independent observations: -log(ab) = -log a + -log b. -/
theorem fep011_surprise_additive {a b : ℝ} (ha : 0 < a) (hb : 0 < b) :
    fep011_surprise (a * b) = fep011_surprise a + fep011_surprise b := by
  simp only [fep011_surprise]
  rw [Real.log_mul (ne_of_gt ha) (ne_of_gt hb), neg_add]

/-- Surprise of certain event (u = 1) is zero. -/
theorem fep011_surprise_cert : fep011_surprise 1 = 0 := by
  simp [fep011_surprise]

/-- Surprise is monotone decreasing in probability: larger p → lower surprise. -/
theorem fep011_surprise_mono {p q : ℝ} (hp : 0 < p) (h : p ≤ q) :
    fep011_surprise q ≤ fep011_surprise p :=
  neg_le_neg (Real.log_le_log hp h)

/-- On positive probabilities, only a certain event has zero surprise. -/
theorem fep011_surprise_eq_zero_iff {p : ℝ} (hp : 0 < p) :
    fep011_surprise p = 0 ↔ p = 1 := by
  constructor
  · intro hzero
    exact Real.eq_one_of_pos_of_log_eq_zero hp (neg_eq_zero.mp hzero)
  · rintro rfl
    exact fep011_surprise_cert

/-- Surprise is strictly antitone on positive probabilities. -/
theorem fep011_surprise_strictAnti {p q : ℝ} (hp : 0 < p) (hpq : p < q) :
    fep011_surprise q < fep011_surprise p := by
  exact neg_lt_neg (Real.log_lt_log hp hpq)

end FEP011
""",
    "fep-012": """import Mathlib.Analysis.SpecialFunctions.Exp
import Mathlib.Analysis.SpecialFunctions.Log.Basic
import Mathlib.Algebra.BigOperators.Group.Finset.Basic
import Mathlib.Algebra.Order.BigOperators.Group.Finset

namespace FEP012

open Real Finset

-- [proof strategy: Real.exp_nonneg / exp_pos combined with Finset.sum_nonneg / sum_pos]

abbrev Policy := Fin 10

/-- Shannon entropy of a finite policy-weight vector.  The probability-simplex
assumptions are stated by the theorems that use it. -/
noncomputable def fep012_policyEntropy (q : Policy → ℝ) : ℝ :=
  ∑ p, q p * (-Real.log (q p))

/-- Expected policy cost under finite weights. -/
def fep012_expectedCost (q cost : Policy → ℝ) : ℝ :=
  ∑ p, q p * cost p

/-- Entropy-regularized policy objective, with temperature `τ`. -/
noncomputable def fep012_entropyRegularizedCost
    (q cost : Policy → ℝ) (τ : ℝ) : ℝ :=
  fep012_expectedCost q cost - τ * fep012_policyEntropy q

/-- Policy entropy is nonnegative for weights in the unit interval. -/
theorem fep012_policyEntropy_nonneg (q : Policy → ℝ)
    (hq : ∀ p, q p ∈ Set.Icc (0 : ℝ) 1) :
    0 ≤ fep012_policyEntropy q := by
  exact Finset.sum_nonneg fun p _ =>
    mul_nonneg (hq p).1
      (neg_nonneg.mpr (Real.log_nonpos (hq p).1 (hq p).2))

/-- A deterministic point policy has zero Shannon entropy. -/
theorem fep012_policyEntropy_pointMass (chosen : Policy) :
    fep012_policyEntropy (fun p => if p = chosen then 1 else 0) = 0 := by
  classical
  simp [fep012_policyEntropy]

/-- Nonnegative entropy temperature can only lower the regularized objective
relative to the unregularized expected cost. -/
theorem fep012_entropyRegularizedCost_le_expectedCost
    (q cost : Policy → ℝ) (τ : ℝ)
    (hτ : 0 ≤ τ) (hq : ∀ p, q p ∈ Set.Icc (0 : ℝ) 1) :
    fep012_entropyRegularizedCost q cost τ ≤ fep012_expectedCost q cost := by
  exact sub_le_self _ (mul_nonneg hτ (fep012_policyEntropy_nonneg q hq))

/-- At zero temperature entropy regularization vanishes exactly. -/
theorem fep012_entropyRegularizedCost_zeroTemperature
    (q cost : Policy → ℝ) :
    fep012_entropyRegularizedCost q cost 0 = fep012_expectedCost q cost := by
  simp [fep012_entropyRegularizedCost]

/-- Gibbs partition sum ``∑ exp(-G)`` is nonnegative (Boltzmann weights). -/
theorem fep012_gibbsPartition_nonneg (G : Policy → ℝ) (s : Finset Policy) :
    0 ≤ ∑ p ∈ s, Real.exp (-G p) :=
  Finset.sum_nonneg fun _ _ => Real.exp_nonneg _

/-- Gibbs partition sum is strictly positive when policy set is nonempty. -/
theorem fep012_gibbsPartition_pos (G : Policy → ℝ) (s : Finset Policy) (hne : s.Nonempty) :
    0 < ∑ p ∈ s, Real.exp (-G p) :=
  Finset.sum_pos (fun _ _ => Real.exp_pos _) hne

/-- Monotonicity: lower cost → larger Boltzmann weight at temperature β = 1. -/
theorem fep012_gibbs_mono (G₁ G₂ : Policy) (G : Policy → ℝ) (h : G G₁ ≤ G G₂) :
    Real.exp (-G G₂) ≤ Real.exp (-G G₁) :=
  Real.exp_le_exp.mpr (by linarith)

end FEP012
""",
    "fep-015": """import Mathlib.MeasureTheory.Constructions.BorelSpace.Basic

namespace FEP015

variable {α : Type*} [MeasurableSpace α]

/-- Pointwise variational-free-energy integrand: energy plus approximate
log-density minus generative log-density. -/
def fep015_variationalIntegrand
    (energy logApproximation logGenerative : α → ℝ) (state : α) : ℝ :=
  energy state + logApproximation state - logGenerative state

/-- Measurability of all three scientific ingredients is sufficient for
measurability of the complete variational integrand. -/
theorem fep015_variationalIntegrand_measurable
    {energy logApproximation logGenerative : α → ℝ}
    (henergy : Measurable energy)
    (happroximation : Measurable logApproximation)
    (hgenerative : Measurable logGenerative) :
    Measurable
      (fep015_variationalIntegrand energy logApproximation logGenerative) := by
  exact (henergy.add happroximation).sub hgenerative

/-- Reparameterizing a measurable variational integrand by a measurable state
map preserves measurability. -/
theorem fep015_variationalIntegrand_comp_measurable
    {β : Type*} [MeasurableSpace β]
    {energy logApproximation logGenerative : α → ℝ}
    {reparameterize : β → α}
    (henergy : Measurable energy)
    (happroximation : Measurable logApproximation)
    (hgenerative : Measurable logGenerative)
    (hreparameterize : Measurable reparameterize) :
    Measurable
      (fep015_variationalIntegrand energy logApproximation logGenerative ∘
        reparameterize) :=
  (fep015_variationalIntegrand_measurable
    henergy happroximation hgenerative).comp hreparameterize

/-- Adding a measurable scalar baseline preserves variational-integrand
measurability. -/
theorem fep015_variationalIntegrand_add_const_measurable
    {energy logApproximation logGenerative : α → ℝ}
    (henergy : Measurable energy)
    (happroximation : Measurable logApproximation)
    (hgenerative : Measurable logGenerative) (baseline : ℝ) :
    Measurable (fun state =>
      fep015_variationalIntegrand energy logApproximation logGenerative state +
        baseline) :=
  (fep015_variationalIntegrand_measurable
    henergy happroximation hgenerative).add measurable_const

end FEP015
""",
    "fep-016": """import Mathlib.Analysis.SpecialFunctions.Gaussian.GaussianIntegral

namespace FEP016

/-- Laplace approximation: quadratic forms have a global minimum at zero. -/
theorem fep016_quadratic_min (x : ℝ) : 0 ≤ x ^ 2 :=
  sq_nonneg x

/-- The quadratic (x - μ)² achieves its minimum value of 0 at x = μ. -/
theorem fep016_quadratic_at_mode (μ : ℝ) : (μ - μ) ^ 2 = 0 := by ring

/-- Precision-weighted quadratic: prec * (x - μ)² is nonneg when prec ≥ 0. -/
theorem fep016_precision_weighted (prec x μ : ℝ) (hp : 0 ≤ prec) :
    0 ≤ prec * (x - μ) ^ 2 :=
  mul_nonneg hp (sq_nonneg _)

/-- Symmetry of quadratic loss: (x - μ)² = (μ - x)². -/
theorem fep016_quadratic_sym (x μ : ℝ) : (x - μ) ^ 2 = (μ - x) ^ 2 := by ring

/-- Expansion: (x - μ)² = x² - 2μx + μ² (second-order Taylor anchor). -/
theorem fep016_quadratic_expand (x μ : ℝ) :
    (x - μ) ^ 2 = x ^ 2 - 2 * μ * x + μ ^ 2 := by ring

/-- The centered exponential kernel produced by a scalar quadratic Laplace
model with precision `precision`. -/
noncomputable def fep016_laplaceKernel (precision x : ℝ) : ℝ :=
  Real.exp (-(precision / 2) * x ^ 2)

/-- Positive precision makes the quadratic Laplace kernel integrable. -/
theorem fep016_laplaceKernel_integrable
    {precision : ℝ} (hprecision : 0 < precision) :
    MeasureTheory.Integrable (fep016_laplaceKernel precision) := by
  exact integrable_exp_neg_mul_sq (by positivity : 0 < precision / 2)

/-- Mathlib's Gaussian integral gives the exact scalar Laplace normalizer. -/
theorem fep016_laplaceKernel_integral
    {precision : ℝ} (hprecision : 0 < precision) :
    (∫ x : ℝ, fep016_laplaceKernel precision x) =
      Real.sqrt (Real.pi / (precision / 2)) := by
  have _hintegrable :
      MeasureTheory.Integrable (fep016_laplaceKernel precision) :=
    fep016_laplaceKernel_integrable hprecision
  simpa [fep016_laplaceKernel] using
    integral_gaussian (precision / 2)

end FEP016
""",
    "fep-026": """import Mathlib.Analysis.SpecialFunctions.Log.Basic

namespace FEP026

open Real

/-- Negative-log prior complexity of a positive prior density value. -/
noncomputable def fep026_priorComplexity (priorDensity : ℝ) : ℝ :=
  -Real.log priorDensity

/-- Complexity penalties via log: log is monotone on positive reals. -/
theorem fep026_log_monotone {a b : ℝ} (ha : 0 < a) (hab : a ≤ b) :
    Real.log a ≤ Real.log b :=
  Real.log_le_log ha hab

/-- Quotient rule for real logarithms (``log(a/b) = log a - log b``). -/
theorem fep026_log_div {a b : ℝ} (ha : 0 < a) (hb : 0 < b) :
    Real.log (a / b) = Real.log a - Real.log b :=
  Real.log_div ha.ne' hb.ne'

/-- Complexity penalty: -log p(θ) increases as the prior p(θ) decreases toward zero. -/
theorem fep026_complexity_increases {p q : ℝ} (hp : 0 < p) (_hq : 0 < q) (h : p ≤ q) :
    fep026_priorComplexity q ≤ fep026_priorComplexity p :=
  neg_le_neg (Real.log_le_log hp h)

/-- Complexity at prior equal to 1 is zero. -/
theorem fep026_complexity_zero_at_one : fep026_priorComplexity 1 = 0 := by
  simp [fep026_priorComplexity]

/-- Complexity of product is sum of complexities. -/
theorem fep026_complexity_additive {a b : ℝ} (ha : 0 < a) (hb : 0 < b) :
    fep026_priorComplexity (a * b) =
      fep026_priorComplexity a + fep026_priorComplexity b := by
  simp only [fep026_priorComplexity]
  rw [Real.log_mul ha.ne' hb.ne', neg_add]

/-- For positive prior density, zero complexity occurs exactly at unit
density. -/
theorem fep026_priorComplexity_eq_zero_iff {p : ℝ} (hp : 0 < p) :
    fep026_priorComplexity p = 0 ↔ p = 1 := by
  constructor
  · intro hzero
    apply Real.eq_one_of_pos_of_log_eq_zero hp
    exact neg_eq_zero.mp (by simpa [fep026_priorComplexity] using hzero)
  · rintro rfl
    exact fep026_complexity_zero_at_one

/-- Negative-log complexity strictly decreases as positive prior density
increases. -/
theorem fep026_priorComplexity_strictAnti
    {p q : ℝ} (hp : 0 < p) (hpq : p < q) :
    fep026_priorComplexity q < fep026_priorComplexity p := by
  exact neg_lt_neg (Real.log_lt_log hp hpq)

end FEP026
""",
    "fep-032": """import Mathlib.Analysis.SpecificLimits.Normed
import Mathlib.Tactic

namespace FEP032

/-- Gradient-descent update for the centered quadratic energy
`(x - center)² / 2`. -/
def fep032_quadraticUpdate (step center x : ℝ) : ℝ :=
  x - step * (x - center)

/-- One descent step scales displacement from the minimizer exactly. -/
theorem fep032_quadraticUpdate_deviation (step center x : ℝ) :
    fep032_quadraticUpdate step center x - center =
      (1 - step) * (x - center) := by
  simp only [fep032_quadraticUpdate]
  ring

/-- The minimizer is a fixed point for every step size. -/
theorem fep032_quadraticUpdate_fixed (step center : ℝ) :
    fep032_quadraticUpdate step center center = center := by
  simp [fep032_quadraticUpdate]

/-- Closed form for every finite gradient-descent iterate. -/
theorem fep032_quadraticUpdate_iterate (step center x : ℝ) (n : ℕ) :
    ((fep032_quadraticUpdate step center)^[n]) x - center =
      (1 - step) ^ n * (x - center) := by
  induction n with
  | zero => simp
  | succ n ih =>
      rw [Function.iterate_succ_apply']
      rw [fep032_quadraticUpdate_deviation, ih, pow_succ]
      ring

/-- Step sizes in `[0,2]` cannot increase the centered quadratic energy. -/
theorem fep032_quadraticEnergy_descent
    {step center x : ℝ} (hstep0 : 0 ≤ step) (hstep2 : step ≤ 2) :
    (fep032_quadraticUpdate step center x - center) ^ 2 ≤
      (x - center) ^ 2 := by
  rw [fep032_quadraticUpdate_deviation]
  have hfactor : (1 - step) ^ 2 ≤ 1 := by nlinarith
  have hscaled :=
    mul_le_mul_of_nonneg_right hfactor (sq_nonneg (x - center))
  nlinarith

/-- Every strictly stable step size converges to the unique quadratic
minimizer from every initial state. -/
theorem fep032_quadraticUpdate_tendsto
    {step : ℝ} (hstep0 : 0 < step) (hstep2 : step < 2)
    (center x : ℝ) :
    Filter.Tendsto
      (fun n => ((fep032_quadraticUpdate step center)^[n]) x)
      Filter.atTop (nhds center) := by
  have habs : |1 - step| < 1 := by
    rw [abs_lt]
    constructor <;> linarith
  have hpow : Filter.Tendsto (fun n : ℕ => (1 - step) ^ n)
      Filter.atTop (nhds 0) :=
    tendsto_pow_atTop_nhds_zero_of_abs_lt_one habs
  have hdeviation : Filter.Tendsto
      (fun n : ℕ =>
        ((fep032_quadraticUpdate step center)^[n]) x - center)
      Filter.atTop (nhds 0) := by
    simpa only [fep032_quadraticUpdate_iterate, zero_mul] using
      hpow.mul_const (x - center)
  simpa only [sub_add_cancel, zero_add] using hdeviation.add_const center

end FEP032
""",
    "fep-035": """import Mathlib.Analysis.Convex.SpecificFunctions.Basic

namespace FEP035

open Real

-- [proof strategy: Mathlib strict concavity plus logarithm identities]

/-- The real logarithm is strictly concave on the positive half-line. -/
theorem fep035_log_strictConcave :
    StrictConcaveOn ℝ (Set.Ioi 0) Real.log :=
  strictConcaveOn_log_Ioi

/-- Strict two-point Jensen inequality for distinct positive inputs and
strictly positive weights summing to one. -/
theorem fep035_log_jensen_two_strict
    {x y a b : ℝ} (hx : 0 < x) (hy : 0 < y) (hxy : x ≠ y)
    (ha : 0 < a) (hb : 0 < b) (hab : a + b = 1) :
    a * Real.log x + b * Real.log y < Real.log (a * x + b * y) := by
  simpa only [smul_eq_mul] using
    strictConcaveOn_log_Ioi.2 hx hy hxy ha hb hab

/-- Logarithm turns products into sums (``log(ab)=log a+log b``). -/
theorem fep035_log_mul {a b : ℝ} (ha : 0 < a) (hb : 0 < b) :
    Real.log (a * b) = Real.log a + Real.log b :=
  Real.log_mul (ne_of_gt ha) (ne_of_gt hb)

/-- Power rule for logarithms on ``(0,∞)``. -/
theorem fep035_log_pow {a : ℝ} (_ha : 0 < a) (n : ℕ) : Real.log (a ^ n) = n * Real.log a :=
  Real.log_pow a n

/-- Jensen anchor: log(exp x) = x (log-exp inverse). -/
theorem fep035_log_exp (x : ℝ) : Real.log (Real.exp x) = x :=
  Real.log_exp x

/-- Concavity anchor: log on (0,∞) is monotone. -/
theorem fep035_log_mono {a b : ℝ} (ha : 0 < a) (h : a ≤ b) :
    Real.log a ≤ Real.log b :=
  Real.log_le_log ha h

/-- log 1 = 0. -/
theorem fep035_log_one : Real.log (1 : ℝ) = 0 := Real.log_one

end FEP035
""",
    "fep-039": """import Mathlib.Algebra.BigOperators.Group.Finset.Basic
import Mathlib.Algebra.Order.BigOperators.Group.Finset
import Mathlib.Data.Real.Basic

namespace FEP039

open Finset

-- [proof strategy: Finset.sum_nonneg + sum_le_sum + sum_const for global-vs-local FE]

/-- Global free energy: ∑ local contributions over a partition. -/
def fep039_global_fe (local_fe : Fin 4 → ℝ) : ℝ :=
  ∑ i : Fin 4, local_fe i

/-- Global FE is nonneg when all local contributions are nonneg. -/
theorem fep039_global_nonneg (local_fe : Fin 4 → ℝ) (h : ∀ i, 0 ≤ local_fe i) :
    0 ≤ fep039_global_fe local_fe :=
  Finset.sum_nonneg fun i _ => h i

/-- Global FE monotone: improving one local term improves the global. -/
theorem fep039_global_mono (f g : Fin 4 → ℝ) (h : ∀ i, f i ≤ g i) :
    fep039_global_fe f ≤ fep039_global_fe g :=
  Finset.sum_le_sum fun i _ => h i

/-- Zero local FE everywhere → zero global FE. -/
theorem fep039_global_zero : fep039_global_fe (fun _ => 0) = 0 := by
  simp [fep039_global_fe]

/-- Global FE additive in pointwise sums. -/
theorem fep039_global_add (f g : Fin 4 → ℝ) :
    fep039_global_fe (fun i => f i + g i) = fep039_global_fe f + fep039_global_fe g := by
  simp [fep039_global_fe, Finset.sum_add_distrib]

/-- For nonnegative local energies, global free energy vanishes exactly when
every local contribution vanishes. -/
theorem fep039_global_eq_zero_iff (local_fe : Fin 4 → ℝ)
    (hnonneg : ∀ i, 0 ≤ local_fe i) :
    fep039_global_fe local_fe = 0 ↔ ∀ i, local_fe i = 0 := by
  constructor
  · intro hzero i
    exact (Finset.sum_eq_zero_iff_of_nonneg
      (fun j _ => hnonneg j)).mp hzero i (Finset.mem_univ i)
  · intro hlocal
    simp [fep039_global_fe, hlocal]

end FEP039
""",
    "fep-043": """import Mathlib.Analysis.Calculus.Deriv.Mul
import Mathlib.Analysis.Calculus.Deriv.Pow
import Mathlib.Analysis.Calculus.LocalExtr.Basic
import Mathlib.Tactic

namespace FEP043

/-- Fermat's theorem: the derivative vanishes at every local minimum. -/
theorem fep043_localMin_deriv_zero
    {f : ℝ → ℝ} {x₀ : ℝ} (hmin : IsLocalMin f x₀) :
    deriv f x₀ = 0 :=
  hmin.deriv_eq_zero

/-- Exact scalar quadratic free-energy landscape. -/
def fep043_quadraticFreeEnergy (a x₀ c x : ℝ) : ℝ :=
  a * (x - x₀) ^ 2 + c

/-- Its gradient field. -/
def fep043_quadraticGradient (a x₀ x : ℝ) : ℝ :=
  2 * a * (x - x₀)

/-- Exact first derivative of the quadratic free energy. -/
theorem fep043_quadratic_hasDerivAt (a x₀ c x : ℝ) :
    HasDerivAt (fep043_quadraticFreeEnergy a x₀ c)
      (fep043_quadraticGradient a x₀ x) x := by
  convert (((hasDerivAt_id x).sub_const x₀).pow 2).const_mul a |>.add_const c using 1
  all_goals
    first
    | exact AddCommGroup.ext rfl
    | exact Module.ext rfl
    | rfl
    | (simp [fep043_quadraticGradient] ; ring)

/-- Positive curvature makes the center the unique global minimizer. -/
theorem fep043_quadratic_unique_min
    {a x₀ c x : ℝ} (ha : 0 < a) :
    fep043_quadraticFreeEnergy a x₀ c x =
        fep043_quadraticFreeEnergy a x₀ c x₀ ↔
      x = x₀ := by
  constructor
  · intro h
    have hcenter : fep043_quadraticFreeEnergy a x₀ c x₀ = c := by
      simp [fep043_quadraticFreeEnergy]
    rw [hcenter] at h
    rw [fep043_quadraticFreeEnergy] at h
    have hsquare : (x - x₀) ^ 2 = 0 := by nlinarith
    nlinarith
  · rintro rfl
    rfl

/-- For positive curvature, the unique critical point is the unique minimum. -/
theorem fep043_quadratic_critical_iff
    {a x₀ c x : ℝ} (ha : 0 < a) :
    deriv (fep043_quadraticFreeEnergy a x₀ c) x = 0 ↔ x = x₀ := by
  rw [(fep043_quadratic_hasDerivAt a x₀ c x).deriv]
  simp only [fep043_quadraticGradient]
  constructor <;> intro h
  · nlinarith
  · rw [h, sub_self, mul_zero]

/-- The gradient derivative is the constant scalar Hessian `2a`. -/
theorem fep043_quadraticGradient_hasDerivAt (a x₀ x : ℝ) :
    HasDerivAt (fep043_quadraticGradient a x₀) (2 * a) x := by
  convert ((hasDerivAt_id x).sub_const x₀).const_mul (2 * a) using 1
  all_goals
    first
    | exact AddCommGroup.ext rfl
    | exact Module.ext rfl
    | rfl
    | simp

/-- Positive quadratic curvature gives a strictly positive Hessian. -/
theorem fep043_quadratic_hessian_pos {a : ℝ} (ha : 0 < a) :
    0 < 2 * a := by positivity

end FEP043
""",
    "fep-048": """import Mathlib.Order.Monotone.Basic
import Mathlib.Topology.MetricSpace.Contracting
import Mathlib.Tactic

namespace FEP048

open Topology

-- [proof strategy: native Mathlib ContractingWith and fixed-point API]

/-- Sync update: both components advance together, total is nonneg. -/
theorem fep048_sync_nonneg (a b : ℝ) (ha : 0 ≤ a) (hb : 0 ≤ b) : 0 ≤ a + b :=
  add_nonneg ha hb

/-- Async update: sequential composition preserves monotonicity. -/
theorem fep048_async_mono (f g : ℝ → ℝ) (hf : Monotone f) (hg : Monotone g) :
    Monotone (g ∘ f) :=
  hg.comp hf

/-- Mathlib's global contraction contract gives fixed-point uniqueness. -/
theorem fep048_contraction_unique (f : ℝ → ℝ) (c : NNReal)
    (hcontract : ContractingWith c f) (x y : ℝ)
    (hfx : Function.IsFixedPt f x) (hfy : Function.IsFixedPt f y) : x = y :=
  hcontract.fixedPoint_unique' hfx hfy

/-- A concrete nontrivial contraction used as an executable witness. -/
noncomputable def fep048_halfUpdate (x : ℝ) : ℝ := x / 2

/-- Halving contracts distances by exactly one half. -/
theorem fep048_halfUpdate_contracts :
    ContractingWith (1 / 2 : NNReal) fep048_halfUpdate := by
  refine ⟨by norm_num, LipschitzWith.of_dist_le_mul ?_⟩
  intro a b
  simp only [fep048_halfUpdate, Real.dist_eq]
  rw [← sub_div, abs_div]
  norm_num [div_eq_mul_inv]
  rw [mul_comm]

/-- The concrete halving contraction has zero as its unique fixed point. -/
theorem fep048_halfUpdate_unique_fixed_point (x : ℝ)
    (hx : Function.IsFixedPt fep048_halfUpdate x) : x = 0 := by
  exact fep048_halfUpdate_contracts.fixedPoint_unique' hx (by
    change fep048_halfUpdate 0 = 0
    norm_num [fep048_halfUpdate])

/-- Iterating the halving update from any real initial state converges to zero. -/
theorem fep048_halfUpdate_iterates_converge (x : ℝ) :
    Filter.Tendsto (fun n ↦ fep048_halfUpdate^[n] x) Filter.atTop (𝓝 0) := by
  have hzero : Function.IsFixedPt fep048_halfUpdate 0 := by
    change fep048_halfUpdate 0 = 0
    norm_num [fep048_halfUpdate]
  have hfixed : ContractingWith.fixedPoint fep048_halfUpdate
      fep048_halfUpdate_contracts = 0 :=
    (fep048_halfUpdate_contracts.fixedPoint_unique hzero).symm
  rw [← hfixed]
  exact fep048_halfUpdate_contracts.tendsto_iterate_fixedPoint x

/-- Identity update is monotone (trivial sync). -/
theorem fep048_id_mono : Monotone (id : ℝ → ℝ) := fun _ _ h => h

/-- Sum of monotone scalar updates is monotone. -/
theorem fep048_add_mono (f g : ℝ → ℝ) (hf : Monotone f) (hg : Monotone g) :
    Monotone (fun x => f x + g x) :=
  fun _ _ h => add_le_add (hf h) (hg h)

end FEP048
""",
}
