"""Canonical Lean bodies for information geometry and geometric optimization."""

from __future__ import annotations

BODIES: dict[str, str] = {
    "fep-100": """import FepSketches.geometric_optimization

namespace FEP100

open FEP FEP.GeometricOptimization FEP.InformationGeometry

variable {d : ℕ}

/-- The inherited Fisher metric is strictly positive on every certified
nonzero categorical simplex tangent under full support. -/
theorem fep100_categoricalFisher_simplexTangent_positivity
    (carrier : CategoricalFisherCarrier d)
    (tangent : Fin d → ℝ) (hTangent : IsSimplexTangent tangent)
    (hNonzero : tangent ≠ 0) :
    0 < fisherMetric carrier.model tangent tangent :=
  categoricalFisher_pos carrier tangent hTangent hNonzero

/-- The genuine two-outcome categorical carrier is positive definite on its
entire nonzero simplex tangent space. -/
theorem fep100_twoCategorical_simplexMetric_fullRank
    (tangent : Fin 2 → ℝ) (hTangent : IsSimplexTangent tangent)
    (hNonzero : tangent ≠ 0) :
    0 < fisherMetric twoCategoricalFisherCarrier.model tangent tangent :=
  twoCategorical_simplexMetric_fullRank tangent hTangent hNonzero

/-- Every two-outcome simplex tangent is generated by the explicit nonzero
`(1, -1)` direction. -/
theorem fep100_twoCategorical_tangent_spanning
    (tangent : Fin 2 → ℝ) (hTangent : IsSimplexTangent tangent) :
    tangent = fun coordinate ↦
      tangent 0 * twoCategoricalTangent coordinate :=
  twoCategoricalTangent_spans tangent hTangent

/-- A concrete nonzero simplex tangent has Fisher energy exactly four. -/
theorem fep100_fullRank_categorical_example :
    IsSimplexTangent twoCategoricalTangent ∧
      twoCategoricalTangent ≠ 0 ∧
      fisherMetric twoCategoricalFisherCarrier.model
        twoCategoricalTangent twoCategoricalTangent = 4 :=
  twoCategorical_nonzeroTangent_metric

/-- Duplicated score coordinates expose a nonzero null direction. -/
theorem fep100_rankDeficient_nullDirection_example :
    duplicatedScoreNullTangent ≠ 0 ∧
      fisherMetric duplicatedFairBernoulliScoreModel
        duplicatedScoreNullTangent duplicatedScoreNullTangent = 0 :=
  duplicatedScore_nullDirection_example

end FEP100
""",
    "fep-101": """import FepSketches.geometric_optimization

namespace FEP101

open FEP FEP.GeometricOptimization FEP.InformationGeometry
open scoped Matrix

variable {Outcome : Type*} [Fintype Outcome]
variable {d k : ℕ}

/-- Fisher pullback along a composite finite Jacobian equals successive
pullback through the two coordinate maps. -/
theorem fep101_fisherPullback_reparameterization
    (model : ScoreModel Outcome d)
    (outer : Matrix (Fin d) (Fin k) ℝ)
    (inner : Matrix (Fin k) (Fin d) ℝ)
    (left right : Fin d → ℝ) :
    pullbackMetric model (outer * inner) left right =
      pullbackMetric model outer (inner.mulVec left) (inner.mulVec right) :=
  fisherPullback_comp model outer inner left right

/-- Every Fisher pullback remains positive semidefinite. -/
theorem fep101_fisherPullback_nonnegative
    (model : ScoreModel Outcome d)
    (jacobian : Matrix (Fin d) (Fin k) ℝ) (tangent : Fin k → ℝ) :
    0 ≤ pullbackMetric model jacobian tangent tangent :=
  pullbackMetric_nonneg model jacobian tangent

end FEP101
""",
    "fep-102": """import FepSketches.geometric_optimization

namespace FEP102

open FEP FEP.GeometricOptimization FEP.InformationGeometry

variable {Outcome : Type*} [Fintype Outcome]

/-- Unbiasedness, the finite score-regularity identity, and positive Fisher
information imply the scalar Cramér--Rao lower bound. -/
theorem fep102_unbiasedScalar_cramerRao
    (model : ScoreModel Outcome 1) (estimator : Outcome → ℝ)
    (target : ℝ)
    (certificate : ScalarCramerRaoCertificate model estimator target) :
    1 ≤ estimatorVariance model.law estimator target * scalarFisher model :=
  scalarCramerRao model estimator target certificate

end FEP102
""",
    "fep-103": """import FepSketches.geometric_optimization

namespace FEP103

open FEP FEP.GeometricOptimization FEP.InformationGeometry
open scoped Matrix

variable {Outcome : Type*} [Fintype Outcome]
variable {d : ℕ}

/-- An invertible full-rank Fisher metric and invertible chart transport the
natural gradient equivariantly to the pulled-back covector. -/
theorem fep103_naturalGradient_equivariance
    (model : ScoreModel Outcome d) [Invertible (fisherMatrix model)]
    (jacobian : Matrix (Fin d) (Fin d) ℝ) [Invertible jacobian]
    (covector : Fin d → ℝ) :
    chartPullbackLower model jacobian
        (chartCoordinates jacobian (naturalGradient model covector)) =
      chartCovector jacobian covector :=
  naturalGradient_equivariant model jacobian covector

/-- The slice's finite Cauchy--Schwarz proof spike remains directly available
at this gate topic, with its strict positive-energy boundary explicit. -/
theorem fep103_weightedCauchySchwarz_proofSpike
    (law : FiniteLaw Outcome) (left right : Outcome → ℝ)
    (hRight : 0 < ∑ outcome, law outcome * right outcome ^ 2) :
    (∑ outcome, law outcome * left outcome * right outcome) ^ 2 ≤
      (∑ outcome, law outcome * left outcome ^ 2) *
        ∑ outcome, law outcome * right outcome ^ 2 :=
  weightedCauchySchwarz_of_right_pos law left right hRight

end FEP103
""",
    "fep-104": """import FepSketches.geometric_optimization

namespace FEP104

open FEP.GeometricOptimization

variable {d : ℕ}

/-- The Bregman divergence generated by supplied potential and gradient data
obeys the exact mirror-descent three-point identity. -/
theorem fep104_mirrorDescent_threePoint_identity
    (potential : (Fin d → ℝ) → ℝ)
    (gradient : (Fin d → ℝ) → Fin d → ℝ)
    (left middle right : Fin d → ℝ) :
    bregmanDivergence potential gradient left right -
        bregmanDivergence potential gradient left middle -
        bregmanDivergence potential gradient middle right =
      coordinatePairing
        (fun coordinate ↦
          gradient middle coordinate - gradient right coordinate)
        (fun coordinate ↦ left coordinate - middle coordinate) :=
  mirrorDescent_threePoint_identity potential gradient left middle right

end FEP104
""",
    "fep-105": """import FepSketches.geometric_optimization

namespace FEP105

open FEP.GeometricOptimization

variable {d : ℕ}

/-- Orthogonality on the maintained affine family yields the exact Bregman
Pythagorean law. -/
theorem fep105_affineProjection_bregmanPythagorean
    (potential : (Fin d → ℝ) → ℝ)
    (gradient : (Fin d → ℝ) → Fin d → ℝ)
    (affineSet : Set (Fin d → ℝ))
    (base projection candidate : Fin d → ℝ)
    (hProjection : AffineBregmanProjection potential gradient affineSet
      base projection)
    (hCandidate : candidate ∈ affineSet) :
    bregmanDivergence potential gradient candidate base =
      bregmanDivergence potential gradient candidate projection +
        bregmanDivergence potential gradient projection base :=
  affineProjection_bregmanPythagorean potential gradient affineSet base
    projection candidate hProjection hCandidate

/-- Nonnegative residual divergence makes the affine projection a minimizer. -/
theorem fep105_affineProjection_minimizes
    (potential : (Fin d → ℝ) → ℝ)
    (gradient : (Fin d → ℝ) → Fin d → ℝ)
    (affineSet : Set (Fin d → ℝ))
    (base projection candidate : Fin d → ℝ)
    (hProjection : AffineBregmanProjection potential gradient affineSet
      base projection)
    (hCandidate : candidate ∈ affineSet)
    (hNonnegative :
      0 ≤ bregmanDivergence potential gradient candidate projection) :
    bregmanDivergence potential gradient projection base ≤
      bregmanDivergence potential gradient candidate base :=
  affineProjection_minimizes potential gradient affineSet base projection
    candidate hProjection hCandidate hNonnegative

end FEP105
""",
    "fep-106": """import FepSketches.geometric_optimization

namespace FEP106

open FEP FEP.GeometricOptimization FEP.InformationGeometry Finset
open scoped BigOperators

variable {d : ℕ}

/-- On a certified categorical Fisher carrier, the replicator field is the
natural gradient of centered fitness. -/
theorem fep106_replicator_naturalGradient_equivalence
    (carrier : CategoricalFisherCarrier d) (fitness : Fin d → ℝ) :
    IsNaturalGradient carrier.model
      (fun coordinate ↦ fitness coordinate - meanFitness carrier.law fitness)
      (replicatorVector carrier.law fitness) :=
  replicator_naturalGradient_equivalence carrier fitness

/-- Replicator dynamics preserves the affine simplex constraint. -/
theorem fep106_replicator_massConservation
    (law : FiniteLaw (Fin d)) (fitness : Fin d → ℝ) :
    ∑ coordinate, replicatorVector law fitness coordinate = 0 :=
  replicatorVector_isSimplexTangent law fitness

/-- A concrete nonconstant two-outcome fitness produces a nonzero replicator
field and realizes the categorical natural-gradient equivalence. -/
theorem fep106_twoCategorical_nonzero_replicator_witness :
    twoCategoricalFitness 0 ≠ twoCategoricalFitness 1 ∧
      replicatorVector twoCategoricalLaw twoCategoricalFitness ≠ 0 ∧
      IsNaturalGradient twoCategoricalFisherCarrier.model
        (fun coordinate ↦
          twoCategoricalFitness coordinate -
            meanFitness twoCategoricalLaw twoCategoricalFitness)
        (replicatorVector twoCategoricalLaw twoCategoricalFitness) :=
  twoCategorical_replicator_nonzero_witness

end FEP106
""",
}
