import FepSketches.compositions.native_blanket_transfer

/-! Warning-free trusted-declaration audit for native blanket transfer. -/

#print axioms FEP.NativeBlanket.staticJoint_condIndepFun
#print axioms FEP.NativeBlanket.correlatedBlanket_nonvacuous
#print axioms fep_fep139.FEP139.fep139_staticJoint_condIndepFun
#print axioms fep_fep139.FEP139.fep139_correlatedBlanket_nonvacuous
#print axioms FEPComposed.fep135_embeddedLaw_extends_fep017
#print axioms FEPComposed.fep136_embeddedExpectation_extends_fep015
#print axioms FEPComposed.fep137_embeddedPredictive_extends_fep019
#print axioms FEPComposed.fep138_rectangleFactorization_extends_fep079
#print axioms FEPComposed.fep139_nativeCondIndep_connects_fep009_fep079
#print axioms FEPComposed.fep140_measurableCoarsening_extends_fep009
#print axioms FEPComposed.fep141_blanketTransition_extends_fep080
