"""Regenerate ``lean/FepSketches/fep_all.lean`` from ``catalogue_sketches.SKETCHES``.

The aggregate Lake file is the whole-workspace compilation target used by
``lake build FepSketches`` and the CI proof-quality gate. It is tracked so a
fresh clone contains the same canonical Lean input used by the tests.

This script is the single regenerator. It reads the canonical sketch bodies
from :mod:`catalogue_sketches` (the SKETCHES dict — the same source the
catalogue YAML is built from) and emits one file:

* ``lean/FepSketches/fep_all.lean`` — every topic wrapped in
  ``namespace fep_fepNNN ... end fep_fepNNN``. Per-sketch ``import Mathlib.*``
  lines are hoisted to a single top-level ``import Mathlib`` (Mathlib's root
  module re-exports the whole library, so a single import is sufficient and
  matches the per-topic preamble used by ``LeanVerifier._wrap_lean_code``).

The aggregate's outer ``namespace fep_fepNNN`` (lowercase, ``fep_`` prefix)
differs deliberately from each sketch's inner ``namespace FEPNNN``: the outer
wrapper exists only to namespace-isolate identically-named helpers across
topics during a single batch compile, while the inner namespaces preserve the
per-topic theorem qualified names used in the manuscript and tests.

Usage
-----
::

    uv run --directory projects/fep_lean python scripts/_maint_build_fep_all_lean.py

Exit code 0 on success, non-zero if SKETCHES is empty or the lean output
directory cannot be created.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
LEAN_OUT_DIR = PROJECT_ROOT / "lean" / "FepSketches"
FEP_ALL_PATH = LEAN_OUT_DIR / "fep_all.lean"

# Match per-sketch ``import Mathlib...`` (and the rare ``import Lake``) lines so
# we can hoist them. Anything else is left in place.
_IMPORT_RE = re.compile(r"^import\s+\S+.*$", re.MULTILINE)


def _import_sketches() -> dict[str, str]:
    """Import :mod:`catalogue_sketches` from this script's directory.

    Avoids a hard package layout assumption: the script can be invoked from
    anywhere as long as it sits next to ``catalogue_sketches.py``.
    """
    scripts_dir = Path(__file__).resolve().parent
    if str(scripts_dir) not in sys.path:
        sys.path.insert(0, str(scripts_dir))
    import catalogue_sketches  # type: ignore[import-not-found]

    catalogue_sketches.assert_complete()
    return dict(catalogue_sketches.SKETCHES)


def _strip_imports(body: str) -> str:
    """Remove top-level ``import ...`` lines from a sketch body.

    The aggregate hoists a single ``import Mathlib`` to the file head, so the
    per-sketch imports become redundant and would otherwise create noisy
    duplicates in the rendered Lake file.
    """
    cleaned = _IMPORT_RE.sub("", body)
    # Collapse any leading blank lines that the import strip leaves behind so
    # ``namespace FEPNNN`` sits flush against the wrapper.
    return cleaned.lstrip("\n")


def _topic_id_to_namespace(topic_id: str) -> str:
    """``"fep-001"`` -> ``"fep_fep001"`` (the namespace expected by the SSOT test)."""
    if not topic_id.startswith("fep-"):
        raise ValueError(f"unexpected topic id format: {topic_id!r}")
    suffix = topic_id[len("fep-") :]
    if not suffix.isdigit():
        raise ValueError(f"non-numeric topic suffix: {topic_id!r}")
    return f"fep_fep{suffix}"


def _build_aggregate(sketches: dict[str, str]) -> str:
    """Render the full ``fep_all.lean`` text from the SKETCHES dict."""
    if not sketches:
        raise ValueError("SKETCHES is empty — refusing to write a degenerate aggregate")

    parts: list[str] = [
        "-- AUTO-GENERATED by scripts/_maint_build_fep_all_lean.py",
        "-- Source of truth: scripts/catalogue_sketches.py SKETCHES",
        "-- Do not edit by hand; regenerate after any SKETCHES change.",
        "--",
        "-- Each topic body is wrapped in `namespace fep_fepNNN ... end fep_fepNNN`",
        "-- so identically-named helpers across topics never collide during the",
        "-- whole-catalogue `lake build FepSketches`. Inner `namespace FEPNNN`",
        "-- blocks are preserved so per-topic qualified names stay stable.",
        "import Mathlib",
        "",
    ]

    for topic_id in sorted(sketches.keys()):
        ns = _topic_id_to_namespace(topic_id)
        body = _strip_imports(sketches[topic_id]).rstrip()
        parts.append(f"namespace {ns}")
        parts.append("")
        parts.append(body)
        parts.append("")
        parts.append(f"end {ns}")
        parts.append("")

    return "\n".join(parts).rstrip() + "\n"


def write_aggregate(out_dir: Path | None = None) -> tuple[Path, int]:
    """Write ``fep_all.lean`` under *out_dir* and return its topic count."""
    out_dir = out_dir or LEAN_OUT_DIR
    out_dir.mkdir(parents=True, exist_ok=True)

    sketches = _import_sketches()
    text = _build_aggregate(sketches)

    fep_all_path = out_dir / "fep_all.lean"
    fep_all_path.write_text(text, encoding="utf-8")
    return fep_all_path, len(sketches)


def main() -> int:
    try:
        fep_all_path, n = write_aggregate()
    except (ValueError, OSError) as exc:
        print(f"_maint_build_fep_all_lean: failed: {exc}", file=sys.stderr)
        return 1
    print(f"wrote {n} topic namespaces to {fep_all_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
