#!/usr/bin/env python3
"""Generate or drift-check the formal theorem-landscape projection.

`docs/lean-landscape.md` is generated from `src/fep_lean/formal/manifest.py`
and the actual `import FepSketches.*` statements in the workspace Lean
sources, giving an agent (or reviewer) a deterministic dependency-ordered map
of the maintained formal kernel: which modules exist, what each owns, what it
depends on, and in what order layers compile. Never edit the generated page
by hand; edit the manifest or the Lean sources and regenerate.

Usage:
    uv run python scripts/_maint_build_lean_landscape.py           # regenerate
    uv run python scripts/_maint_build_lean_landscape.py --check   # freshness gate
"""

from __future__ import annotations

import argparse
from collections import defaultdict
from pathlib import Path

from fep_lean.formal.manifest import FORMAL_MODULES

HEADER = """<!-- AUTO-GENERATED by scripts/_maint_build_lean_landscape.py; DO NOT EDIT -->

# Formal Lean Theorem Landscape

Deterministic dependency map of the maintained formal kernel, generated from
[`src/fep_lean/formal/manifest.py`](../src/fep_lean/formal/manifest.py) and the
actual `import FepSketches.*` statements in the workspace sources. The exact
roster and roles live in the manifest; this page projects them for navigation.

- **Layer N** modules import only modules in strictly lower layers, so layers
  build in order and any module in layer N can be read after its predecessors.
- Topic bodies (155 catalogue rows) live in family modules under
  [`src/fep_lean/catalogue/bodies/`](../src/fep_lean/catalogue/bodies/), not
  here; the aggregate `fep_all.lean` covers all of them.
- Regenerate with `uv run python scripts/_maint_build_lean_landscape.py`;
  `--check` is the non-mutating freshness gate.
- The interactive relation graph over these modules is
  [`formalism-atlas.html`](formalism-atlas.html); generated counts are in
  [`formalism-coverage.md`](formalism-coverage.md).
"""

FOOTER = """

## Reading order

An agent landing cold should read in this order:

1. [`../AGENTS.md`](../AGENTS.md) — purpose, terminology, execution contract.
2. [`lean4.md`](lean4.md) — pinned toolchain, build commands, aggregate rules.
3. This page — where each formal module sits in the dependency order.
4. [`formalism-coverage.md`](formalism-coverage.md) — measured declaration
   counts and semantic disposition.
5. [`../TODO.md`](../TODO.md) — open backlog with acceptance probes.
"""


def _workspace_imports(path: Path) -> list[str]:
    deps: list[str] = []
    for line in path.read_text(encoding="utf-8").splitlines():
        stripped = line.strip()
        if stripped.startswith("import "):
            target = stripped.split()[1]
            if target.startswith("FepSketches."):
                deps.append(target.removeprefix("FepSketches."))
    return deps


def _layers(project_root: Path) -> tuple[dict[str, int], dict[str, list[str]]]:
    workspace = project_root / "lean" / "FepSketches"
    deps: dict[str, list[str]] = {}
    for module in FORMAL_MODULES:
        name = module.lean_module.removeprefix("FepSketches.")
        deps[name] = [
            dep
            for dep in _workspace_imports(workspace / module.resource)
            if dep != name
        ]
    layer: dict[str, int] = {}
    manifest_names = set(deps)

    def depth(name: str, seen: tuple[str, ...]) -> int:
        # Generated aggregates (fep_all.lean) may be imported by compositions
        # without being manifested; they carry no layer of their own.
        if name not in manifest_names or name in layer:
            return layer.get(name, 0)
        if name in seen:
            # Import cycles cannot happen in compilable Lean; treat as layer 0.
            return 0
        value = max(
            (depth(dep, seen + (name,)) + 1 for dep in deps.get(name, ())),
            default=0,
        )
        layer[name] = value
        return value

    for name in sorted(manifest_names):
        depth(name, ())
    return layer, deps


def render_landscape(project_root: Path) -> str:
    layer, deps = _layers(project_root)
    by_layer: dict[int, list[str]] = defaultdict(list)
    meta = {}
    for module in FORMAL_MODULES:
        name = module.lean_module.removeprefix("FepSketches.")
        by_layer[layer[name]].append(name)
        meta[name] = (module.role.value, module.declaration_namespace, module.resource)

    lines = [HEADER.rstrip("\n"), ""]
    for depth_value in sorted(by_layer):
        names = sorted(by_layer[depth_value])
        lines.append(f"## Layer {depth_value} ({len(names)} modules)")
        lines.append("")
        lines.append("| Module | Role | Namespace | Depends on |")
        lines.append("| --- | --- | --- | --- |")
        for name in names:
            role, namespace, _resource = meta[name]
            fallback = "\u2014"
            dep_text = ", ".join(deps[name]) if deps[name] else fallback
            lines.append(
                f"| `{name}` | {role} | `{namespace or fallback}` | {dep_text} |"
            )
        lines.append("")
    lines.append(
        f"Total maintained formal modules: **{len(FORMAL_MODULES)}** across "
        f"**{max(by_layer) + 1}** dependency layers."
    )
    lines.append(FOOTER)
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    root = Path(__file__).resolve().parents[1]
    target = root / "docs" / "lean-landscape.md"
    rendered = render_landscape(root)
    if args.check:
        if target.exists() and target.read_text(encoding="utf-8") == rendered:
            print("OK: lean landscape projection is current")
            return 0
        print(f"STALE: {target.relative_to(root)}")
        return 1
    target.write_text(rendered, encoding="utf-8")
    print(f"Wrote {target.relative_to(root)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
