#!/usr/bin/env python3
"""Validate and render the maintained semantic theorem-maturity audit."""

from __future__ import annotations

import argparse
import sys
from dataclasses import asdict
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "src"
if str(SRC) not in sys.path:
    sys.path.insert(0, str(SRC))
AUDIT_PATH = ROOT / "config" / "theorem_maturity.yaml"
OUTPUT_PATH = ROOT / "docs" / "theorem-maturity-audit.md"


def validate_audit(root: Path = ROOT) -> dict[str, Any]:
    """Return package-validated rows in the Markdown renderer's input shape."""
    from fep_lean.catalogue.semantics import load_theorem_maturity
    from fep_lean.catalogue.topics import FEPTopicCatalogue

    audit = load_theorem_maturity(root / "config" / "theorem_maturity.yaml")
    catalogue = FEPTopicCatalogue.from_yaml(root / "config" / "topics.yaml")
    if [record.id for record in audit.records] != [
        topic.id for topic in catalogue.topics
    ]:
        raise ValueError("audit topic IDs do not match config/topics.yaml")
    rows = []
    for record in audit.records:
        row = asdict(record)
        row["disposition"] = record.disposition.value
        rows.append(row)
    return {
        "schema_version": audit.schema_version,
        "review_date": audit.review_date,
        "native_evidence": audit.native_evidence,
        "status_policy": audit.status_policy,
        "topics": rows,
    }


def _cell(value: object) -> str:
    return str(value).replace("|", "\\|").replace("\n", " ").strip()


def render_markdown(data: dict[str, Any]) -> str:
    """Render the checked-in Markdown projection from validated audit data."""
    lines = [
        "# Theorem maturity audit",
        "",
        "<!-- AUTO-GENERATED by scripts/theorem_maturity_audit.py; edit config/theorem_maturity.yaml. -->",
        "",
        "This audit reviews the semantic reach of each catalogue row beyond",
        "sorry-free compilation. It is deliberately separate from",
        "`mathlib_status`: `real` records that the declared Lean/Mathlib sketch",
        "is a native compilation target, not that the FEP-facing prose has been",
        "fully formalized.",
        "",
        f"**Review date:** `{data['review_date']}`<br>",
        f"**Native evidence boundary:** {data['native_evidence']}",
        "",
        "A `scope_gap` or `assumption_gap` is an honest follow-up boundary, not a",
        "compiler failure. Dispositions are maintained mathematical judgments,",
        "not values inferred from successful compilation.",
        "",
        "## Status-change policy",
        "",
        data["status_policy"],
        "A status change must update the catalogue source, regenerate YAML and the",
        "aggregate, rerun the native Lean probe, and retain the receipt in",
        "`CHANGELOG.md`.",
        "",
        "## Dispositions",
        "",
        "- `formalized`: the primary theorem directly states the maintained narrowed invariant.",
        "- `proxy`: useful foundational formal fact, with a narrower scope than the prose.",
        "- `conditional_proxy`: meaningful conditional fact whose hypotheses are explicit.",
        "- `structural_proxy`: type, set, metric, or algebra closure fact used as an anchor.",
        "- `scope_gap`: the theorem compiles but omits a named FEP or physical invariant.",
        "- `assumption_gap`: the stated assumptions are vacuous or encode the conclusion.",
        "",
        "## Topic review",
        "",
        "| ID | Primary theorem | Intended invariant | Assumption review | Non-vacuity review | Acceptance probe | Disposition |",
        "| --- | --- | --- | --- | --- | --- | --- |",
    ]
    for row in data["topics"]:
        lines.append(
            "| "
            + " | ".join(
                _cell(row[field])
                for field in (
                    "id",
                    "primary_theorem",
                    "invariant",
                    "assumption_review",
                    "non_vacuity",
                    "acceptance_probe",
                    "disposition",
                )
            )
            + " |"
        )
    lines.extend(
        [
            "",
            "## Source links",
            "",
            "- [Maintained audit data](../config/theorem_maturity.yaml)",
            "- [Catalogue metadata](../config/topics.yaml)",
            "- [Lean body registry](../src/fep_lean/catalogue/registry.py)",
            "- [Family-owned Lean bodies](../src/fep_lean/catalogue/bodies/)",
            "- [Native verification command](cli-reference.md)",
            "",
        ]
    )
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--write", action="store_true", help="write the generated Markdown projection"
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail without writing when the generated projection is stale",
    )
    args = parser.parse_args(argv)
    data = validate_audit()
    if args.write and args.check:
        parser.error("--write and --check are mutually exclusive")
    if args.write:
        OUTPUT_PATH.write_text(render_markdown(data), encoding="utf-8")
        print(f"Wrote {OUTPUT_PATH}")
    elif args.check:
        expected = render_markdown(data)
        try:
            current = OUTPUT_PATH.read_text(encoding="utf-8")
        except OSError:
            current = ""
        if current != expected:
            print(f"STALE: {OUTPUT_PATH.relative_to(ROOT)}", file=sys.stderr)
            return 1
        print("OK: theorem maturity projection is current")
    else:
        print(f"OK: {len(data['topics'])} theorem-maturity rows validated")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
